---
permalink: linux-administration/concept_guidelines_forsnapshot_copycreation.html 
sidebar: sidebar 
keywords: snap, snapdrive, snapshot, copy, create 
summary: UNIX용 SnapDrive를 사용하여 스냅샷 복사본을 생성하는 동안 다음 사항을 고려하십시오. 볼륨당 최대 255개의 스냅샷 복사본을 유지할 수 있고, SnapDrive for UNIX는 생성하는 스냅샷 복사본만 지원하고, 루트 디스크 그룹의 스냅샷 복사본과 부팅 디바이스 또는 스왑 디바이스를 생성할 수 없으며, SnapDrive for UNIX에서는 충돌 일관성을 유지하기 위해 고정 작업이 필요합니다. 
---
= 스냅샷 복사본 생성 지침
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
UNIX용 SnapDrive를 사용하여 스냅샷 복사본을 생성하는 동안 다음 사항을 고려하십시오. 볼륨당 최대 255개의 스냅샷 복사본을 유지할 수 있고, SnapDrive for UNIX는 생성하는 스냅샷 복사본만 지원하고, 루트 디스크 그룹의 스냅샷 복사본과 부팅 디바이스 또는 스왑 디바이스를 생성할 수 없으며, SnapDrive for UNIX에서는 충돌 일관성을 유지하기 위해 고정 작업이 필요합니다.

스냅샷 복사본을 생성하는 명령을 입력할 때 다음 지침을 따르십시오.

* 스토리지 시스템 볼륨당 최대 255개의 스냅샷 복사본을 유지할 수 있습니다. 이 제한은 스토리지 시스템에 의해 설정됩니다. 총 수는 다른 툴이 이러한 스냅샷 복사본을 사용하는지 여부에 따라 다를 수 있습니다.
+
스냅샷 복사본 수가 최대 제한에 도달하면 스냅샷 생성 작업이 실패합니다. 더 이상 SnapDrive for UNIX를 사용하려면 이전 Snapshot 복사본 중 일부를 삭제해야 합니다.

* SnapDrive for UNIX는 생성하지 않는 스냅샷 복사본을 지원하지 않습니다. 예를 들어, 스토리지 시스템 콘솔에서 생성된 스냅샷 복사본은 지원하지 않습니다. 그러한 경우 파일 시스템 내의 일관성이 보장되지 않을 수 있습니다.
* UNIX용 SnapDrive를 사용하여 다음과 같은 스냅샷 복사본을 생성할 수 없습니다.
+
** 루트 디스크 그룹
+
LVM에 대한 루트 디스크 그룹의 스냅샷 복사본을 생성하려고 하면 스냅샷 생성 작업이 실패합니다.

** 장치를 부팅하거나 장치를 바꿉니다
+
SnapDrive for UNIX는 시스템 부팅 디바이스나 시스템 스왑 디바이스의 스냅샷 복제본을 사용하지 않습니다.



* 스냅샷 복사본이 여러 스토리지 시스템 또는 스토리지 시스템 볼륨에 걸쳐 있는 경우 SnapDrive for UNIX에서는 충돌 일관성을 보장하기 위해 고정 작업이 필요합니다. 고정 작업이 제공되지 않는 구성에서 스냅샷 복사본을 생성하는 방법에 대한 자세한 내용은 을 참조하십시오.

