---
permalink: linux-administration/concept_guidelines_forconnectingsnapshot_copies.html 
sidebar: sidebar 
keywords: snap, snapdrive, connect, snapshot, copy, guidelines 
summary: 스냅샷 복사본에 연결할 때는 지침을 따릅니다. 
---
= 스냅샷 복사본 연결 지침
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스냅샷 복사본에 연결할 때는 지침을 따릅니다.

* SnapDrive snap connect 명령은 UNIX용 SnapDrive 4.2에서 생성된 Snapshot 복제본에서만 작동합니다.
* 비소스 호스트에서 UNIX용 SnapDrive 4.1은 Linux LVM1 또는 LVM2를 사용하여 스냅샷 연결 작업을 지원합니다. 하지만 LUN이 Linux LVM1 볼륨 관리자의 일부인 경우 원래 호스트에서 스냅샷 연결 작업을 지원하지 않습니다.
* 원래 호스트에서 SnapDrive for UNIX는 이전 버전의 SnapDrive for UNIX에서 생성된 스냅샷 복사본의 연결 및 복원을 지원합니다.
+

NOTE: Linux에서 생성된 호스트에서 스냅샷 연결 작업은 Linux LVM2와 SnapDrive for UNIX에서 생성한 스냅샷 복사본에서만 작동합니다.

* Linux 호스트에서 접속하는 스냅샷 복사본에 LUN이 포함되어 있거나 Linux LVM1을 활성화하지 않고 생성된 파일 시스템이 있는 LUN이 포함된 경우 'SnapDrive snap connect' 명령이 지원됩니다. SnapDrive for UNIX는 Linux LVM1을 사용하여 생성된 Linux 엔터티에 대해 'SnapDrive snap connect' 명령을 지원하지 않습니다.
+
SnapDrive snap connect 명령을 사용하면 Linux 호스트에서 디스크 그룹의 이름을 바꿀 수 없습니다. 예를 들어, 'SnapDrive snap connect -dg dg1copy -snapname 토스터: /vol/vol1:dg1snapshot' 명령은 지원되지 않습니다

* NFS 디렉토리 트리에 대한 읽기 및 쓰기 액세스의 경우 'SnapDrive snap connect' 명령은 Data ONTAP FlexVol 볼륨 기능을 사용하므로 Data ONTAP 7.3 이상이 필요합니다. Data ONTAP 7.1을 사용하는 구성은 NFS 파일 또는 디렉토리 트리를 연결할 수 있지만 읽기 전용 액세스 권한이 제공됩니다.
* 스냅샷 연결 작업 중에 "enable-split-clone" 구성 변수 값을 "on" 또는 "sync"로 설정하고 스냅샷 연결 해제 작업 중에 "off"로 설정하면 UNIX용 SnapDrive는 스냅샷 복사본에 있는 원래 볼륨 또는 LUN을 삭제하지 않습니다.
* vfiler 장치에 있는 볼륨 또는 LUN의 스냅샷 복사본에 연결하려면 Data ONTAP 7.2.2 구성 옵션 ' vfiler.vol_clone_ZAPI_ALLOW '를 ""on""으로 설정해야 합니다.
* 호스트 구성이 다른 호스트에서는 스냅샷 연결 작업이 지원되지 않습니다.
* 물리적 스토리지 시스템 또는 vFiler 유닛의 루트 볼륨에 연결하는 데 사용되는 "SnapDrive snap connect" 명령은 Data ONTAP가 루트 볼륨 복제를 허용하지 않기 때문에 실패합니다.

