---
permalink: linux-administration/concept_informationrequired_forusing_the_snapdrive_snapcreate_command.html 
sidebar: sidebar 
keywords: create, command, snap, snapdrive, snapshot 
summary: 스냅샷 복사본을 생성할 때 캡처할 스토리지 엔터티를 결정하고 스냅샷 복사본의 이름을 지정해야 합니다. 
---
= SnapDrive snap create 명령을 사용하는 데 필요한 정보입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스냅샷 복사본을 생성할 때 캡처할 스토리지 엔터티를 결정하고 스냅샷 복사본의 이름을 지정해야 합니다.

다음 표에는 'SnapDrive snap create' 명령을 사용할 때 필요한 정보가 나와 있습니다.

|===
| 요구 사항/옵션 | 인수 


 a| 
스냅샷 복사본에 캡처할 스토리지 개체의 유형을 확인합니다. LUN에서 직접 생성된 NFS 엔터티, LUN, 파일 시스템, 단일 명령줄에서 LVM 엔터티를 지정할 수 있습니다.

해당 엔터티의 이름을 적절한 인수로 제공합니다. 이는 file_spec 인수 값입니다.

* 호스트 볼륨 또는 파일 사양이 있는 디스크 그룹을 지정하면 인수가 스토리지 시스템의 디스크 그룹 집합으로 변환됩니다. SnapDrive for UNIX는 엔터티가 호스트 볼륨 또는 파일 시스템이더라도 엔터티가 포함된 전체 디스크 그룹을 생성합니다.
* NFS 마운트 지점인 파일 사양을 지정하는 경우 인수는 스토리지 시스템 볼륨의 디렉토리 트리로 변환됩니다.
* LUN 또는 파일 시스템이 있는 LUN을 지정하는 경우 인수는 LUN이나 파일 시스템이 있는 LUN으로 변환됩니다.
+

NOTE: 스토리지 엔터티로는 '-vg', '-dg', '-fs', '-lvol', '-hostvol' 등의 특수 문자를 지정할 수 없습니다. 그러나 '-fs', '-lvol', '-hostvol' 같은 스토리지 엔터티에는 슬래시(/)가 허용됩니다.





 a| 
LUN('-lun file_spec')
 a| 
LUN의 이름입니다

스토리지 시스템, 볼륨 및 LUN의 이름을 포함해야 합니다.



 a| 
디스크 그룹('-dgfile_spec') 또는 볼륨 그룹('-vg file_spec')
 a| 
디스크 또는 볼륨 그룹의 이름입니다



 a| 
파일 시스템('-fs file_spec')
 a| 
filesystem_name 을 선택합니다



 a| 
호스트 볼륨('-hostvolfile_spec') 또는 논리 볼륨('-lvolfile_spec')
 a| 
호스트 또는 논리 볼륨의 이름입니다


NOTE: 요청된 볼륨과 해당 볼륨이 포함된 디스크 그룹(예: '-hostvol dg3/acct_volume')을 모두 제공해야 합니다.



 a| 
스냅샷 사본 이름('-snapnamesnap_name')
 a| 
스냅샷 copy_name입니다



 a| 
스냅샷 복사본의 이름을 지정합니다. 이것은 스토리지 시스템과 스냅샷 복사본 이름이 있는 볼륨을 포함하는 이름의 긴 버전이거나 스냅샷 복사본 이름인 짧은 버전이 될 수 있습니다.


NOTE: '스냅샷 이름'에 지정된 값이 200자를 초과하지 않도록 해야 합니다.



 a| 
``무관’’
 a| 
~



 a| 
선택 사항: 스냅샷 복사본이 생성될 때 종속 쓰기가 없는 스토리지 엔터티의 스냅샷 복사본을 생성하기 위해 SnapDrive for UNIX는 개별 스토리지 엔터티의 장애 발생 시 정합성이 보장되는 스냅샷 복사본을 생성하지만 엔터티가 서로 정합성이 보장되도록 하지는 않습니다.



 a| 
``힘’’
 a| 
~



 a| 
``코프프롬프트’’
 a| 
~



 a| 
선택 사항: 기존 스냅샷 복사본을 덮어쓸지 결정합니다. 이 옵션이 없으면 기존 스냅샷 복사본의 이름을 제공하면 이 작업이 중지됩니다. 이 옵션을 제공하고 기존 스냅샷 복사본의 이름을 지정하면 스냅샷 복사본을 덮어쓸지 확인하는 메시지가 표시됩니다. SnapDrive for UNIX에서 프롬프트를 표시하지 않으려면 '-nop프롬프트' 옵션도 포함합니다. ('-not프롬프트' 옵션을 사용하려면 반드시 '-force' 옵션을 포함해야 합니다.)



 a| 
'-fstype'입니다
 a| 
'_type_'



 a| 
'-vmtype'입니다
 a| 
'_type_'



 a| 
선택 사항: UNIX용 SnapDrive 작업에 사용할 파일 시스템 및 볼륨 관리자의 유형을 지정합니다.

|===