---
permalink: linux-administration/concept_volume_based_snaprestore_command.html 
sidebar: sidebar 
keywords: snap, snapdrive, snaprestore, volume, command 
summary: 이 섹션에서는 명령 및 볼륨 기반 SnapRestore를 사용하는 옵션에 대해 설명합니다. 
---
= volume-based SnapRestore 명령
:icons: font
:imagesdir: ../media/


[role="lead"]
이 섹션에서는 명령 및 볼륨 기반 SnapRestore를 사용하는 옵션에 대해 설명합니다.

'-vbsr' 옵션이 스냅 복구 CLI에 추가되어 볼륨 기반 SnapRestore를 선택할 수 있습니다. 다음 명령 구문을 사용하여 볼륨 기반 SnapRestore를 사용하여 복원을 수행합니다.

[listing]
----
snapdrive snap restore {-lun | -dg | -vg | -hostvol |
-lvol | -fs |-file} file_spec [file_spec ...] [{-lun | -dg |
-vg | -hostvol | -lvol | -fs -file} file_spec [file_spec ...]
...] -snapname snap_name [-force [-noprompt]][{-reserve |
-noreserve}]
[-vbsr [execute | preview]]
----
'-vbsr'과 함께 인수를 제공하지 않으면 기본 출력은 'preview' 옵션의 기본 출력입니다. 사용자가 오버라이드할 수 있는 모든 필수 점검의 상세 출력을 가능하게 하는 `-verbose' 옵션이 사용됩니다. '-verbose' 옵션이 제공되지 않은 경우 기본 출력에는 실패한 검사의 결과가 표시됩니다.

볼륨 기반 SnapRestore를 실행하는 동안 확인 메시지가 표시되지 않도록 하려면 '-nop프롬프트' 및 '-force' 옵션과 함께 'snap restore-vbsr execute' 명령을 사용할 수 있습니다. 다음 표에서는 에서 제공하는 옵션에 따라 SnapDrive for UNIX 동작에 대해 설명합니다.

|===
| S.N. | -vbsr 실행 | 하중 | -not프롬프트 | 결과 


 a| 
1.
 a| 
아니요
 a| 
해당 없음
 a| 
해당 없음
 a| 
미리보기 모드가 기본 모드입니다. 모든 검사가 수행되어 각 검사에 대한 보고서가 생성됩니다.



 a| 
2.
 a| 
예
 a| 
아니요
 a| 
아니요
 a| 
모든 검사가 수행됩니다. 사용자가 재정의할 수 있는 필수 검사에 실패하면 SnapDrive for UNIX에서 오류 메시지를 표시합니다.



 a| 
3.
 a| 
예
 a| 
예
 a| 
아니요
 a| 
모든 검사가 수행됩니다. 필수 검사에 실패하면 SnapDrive for UNIX에서 오류 메시지를 표시합니다. 사용자가 재정의할 수 있는지 확인하는 데 실패하면 SnapDrive for UNIX에서 메시지를 표시합니다.



 a| 
4.
 a| 
예
 a| 
예
 a| 
예
 a| 
모든 검사가 수행됩니다. 필수 검사에 실패하면 SnapDrive for UNIX에서 오류 메시지를 표시합니다. 사용자가 재정의할 수 있는지 확인하는 데 실패하면 SnapDrive for UNIX에서 메시지를 표시하지 않습니다.

|===