---
permalink: linux-administration/concept_multiple_operations_manager_servers.html 
sidebar: sidebar 
keywords: snap, snapdrive, console, servers, operations, manager, multiple 
summary: UNIX용 SnapDrive는 여러 Operations Manager 콘솔 서버를 지원합니다. 이 기능은 여러 Operations Manager 콘솔 서버에서 스토리지 시스템 그룹을 관리할 때 필요합니다. UNIX용 SnapDrive는 운영 관리자 콘솔 서버가 UNIX용 SnapDrive에서 구성된 순서와 동일한 순서로 Operations Manager 콘솔 서버에 연결합니다. SnapDrive config list 명령을 실행하여 구성 순서를 확인할 수 있습니다. 
---
= 여러 Operations Manager 콘솔 서버
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
UNIX용 SnapDrive는 여러 Operations Manager 콘솔 서버를 지원합니다. 이 기능은 여러 Operations Manager 콘솔 서버에서 스토리지 시스템 그룹을 관리할 때 필요합니다. UNIX용 SnapDrive는 운영 관리자 콘솔 서버가 UNIX용 SnapDrive에서 구성된 순서와 동일한 순서로 Operations Manager 콘솔 서버에 연결합니다. 'SnapDrive config list' 명령어를 실행하여 구성 순서를 확인할 수 있다.

다음 예에서는 여러 Operations Manager 콘솔 서버의 출력을 보여 줍니다.

[listing]
----
# snapdrive config list
username    appliance name     appliance type
---------------------------------------------
root        storage_array1     StorageSystem
root        storage_array2     StorageSystem
sd-admin    ops_mngr_server1   DFM
sd-admin    ops_mngr_server2   DFM
----
앞의 예제에서 storage_array1은 ops_mgr_server1에 의해 관리되고 storage_array2는 ops_mgr_server2에 의해 관리됩니다. 이 예에서는 UNIX용 SnapDrive가 ops_mgr_server1에 먼저 연결합니다. ops_mgr_server1에서 액세스를 확인할 수 없는 경우 SnapDrive for UNIX contacts ops_mgr_server2에 연결합니다.

UNIX용 SnapDrive는 다음 조건에서만 두 번째 Operations Manager 콘솔에 연결합니다.

* 첫 번째 Operations Manager 콘솔에서 액세스를 확인할 수 없는 경우 이 상황은 첫 번째 Operations Manager 콘솔에서 스토리지 시스템을 관리하지 않기 때문에 발생할 수 있습니다.
* 첫 번째 Operations Manager 콘솔이 다운된 경우

