---
permalink: linux-administration/concept_how_the_snapdrivesnap_connect_command_works.html 
sidebar: sidebar 
keywords: snap, snapdrive, connect, command, import, host 
summary: SnapDrive snap connect 명령을 사용하면 지정한 엔터티의 스토리지를 클론하고 해당 스토리지를 호스트로 가져옵니다. 
---
= SnapDrive snap connect 명령의 작동 방식
:icons: font
:imagesdir: ../media/


[role="lead"]
'SnapDrive snap connect' 명령을 사용하면 지정한 엔터티의 스토리지를 클론하고 이를 호스트로 가져옵니다.

* LUN("-lun")이 포함된 스냅샷 복사본을 지정하는 경우 SnapDrive for UNIX는 LUN의 새 복사본을 호스트에 매핑합니다. SnapDrive snap connect 명령을 사용하여 다른 스토리지 엔터티("-vg", "dg", "-fs", "-lvol" 또는 "-hostvol")와 동일한 명령줄에서 LUN을 지정할 수는 없습니다.
* LUN에 직접 상주하는 파일 시스템을 지정하는 경우 SnapDrive for UNIX는 LUN을 호스트에 매핑하고 파일 시스템을 마운트합니다.
* 소스 마운트 지점이 'Snap connect' 명령에서 상대 경로 이름으로 지정된 경우 SnapDrive for UNIX는 CLI에서 지정한 대상 마운트 지점을 무시하고 'source_mount_point_<N>' 형식의 내부 명명 규칙을 사용하여 대상 마운트 지점의 이름을 지정합니다.
* 디스크 그룹이 포함된 스냅샷 복사본이나 디스크 그룹의 일부인 호스트 볼륨 또는 파일 시스템을 지정하는 경우 'SnapDrive snap connect' 명령은 전체 타겟 디스크 그룹을 연결합니다. 연결을 위해 SnapDrive for UNIX는 대상 디스크 그룹의 모든 논리 볼륨을 다시 활성화하고 모든 파일 시스템을 논리 볼륨에 마운트합니다.
* '스냅 접속' 명령으로 'autorename' 옵션을 지정하면 호스트 볼륨과 파일 시스템의 이름이 항상 변경됩니다. 디스크 그룹은 호스트에 이미 있는 경우에만 이름이 변경됩니다.
* NFS 디렉토리 트리가 포함된 스냅샷 복사본을 지정하는 경우 SnapDrive for UNIX는 NFS 디렉토리 트리가 포함된 FlexVol 볼륨의 클론을 생성합니다. 그런 다음 SnapDrive for UNIX가 볼륨을 호스트에 연결하고 NFS 파일 시스템을 마운트합니다. 디렉토리 트리 내에서 SnapDrive for UNIX는 스냅샷 복사본을 생성한 후 생성한 새 NFS 파일 또는 디렉토리를 삭제합니다. SnapDrive for UNIX는 'napconnect-nfs-removedirectories' 구성 옵션이 On으로 설정되어 있는 경우, 연결한 NFS 디렉토리 외부에 있는 FlexVol 볼륨에서 파일 또는 디렉토리를 삭제합니다.
* -readonly 옵션을 사용하여 NFS 디렉토리 트리가 포함된 스냅샷 복사본을 연결하는 경우 SnapDrive for UNIX는 클론을 생성하지 않고 디렉토리의 스냅샷 복사본을 직접 마운트합니다. SnapDrive snap connect 명령을 사용하여 NFS 마운트 지점을 비 NFS 엔터티와 동일한 명령줄에 지정할 수 없습니다. 즉, -vg, -dg, -fs, -lvol 또는 -hostvol 옵션을 사용할 수 있습니다.



NOTE: vFiler 환경의 '-split' 옵션을 사용하는 'snap connect' 작업은 Data ONTAP 7.3 이상에서 지원됩니다.
