---
permalink: linux-administration/concept_what_access_control_settings_are.html 
sidebar: sidebar 
keywords: access, control, settings, snap, snapdrive, user, storage, files 
summary: 사용자 액세스를 확인하기 위해 SnapDrive for UNIX는 스토리지 시스템의 루트 볼륨에 있는 두 개의 사용 권한 파일 중 하나를 확인합니다. 액세스 제어를 평가하려면 해당 파일에 설정된 규칙을 확인해야 합니다. 
---
= 액세스 제어 설정은 무엇입니까
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
사용자 액세스를 확인하기 위해 SnapDrive for UNIX는 스토리지 시스템의 루트 볼륨에 있는 두 개의 사용 권한 파일 중 하나를 확인합니다. 액세스 제어를 평가하려면 해당 파일에 설정된 규칙을 확인해야 합니다.

* 'DHOST-NAME.prbac' 파일은 디렉토리 '/vol/vol0/sdprbac'(SnapDrive 사용 권한 역할 기반 액세스 제어)에 있습니다.
+
파일 이름은 DHOST-NAME.prbac입니다. 여기서, '_host-name_'은 사용 권한이 적용되는 호스트의 이름입니다. 스토리지 시스템에 접속된 각 호스트에 대한 사용 권한 파일이 있을 수 있습니다. "SnapDrive config access" 명령을 사용하여 특정 스토리지 시스템에서 호스트에 사용할 수 있는 권한에 대한 정보를 표시할 수 있습니다.

+
DHOST-NAME.prbac이 존재하지 않는 경우, 'dsgeneric.prbac' 파일을 사용하여 액세스 권한을 확인한다.

* 'sdgeneric.prbac' 파일도 '/vol/vol0/sdprbac' 디렉토리에 있습니다.
+
파일 이름 'dsgeneric.prbac'은 스토리지 시스템의 DHOST-NAME.prbac 파일에 액세스할 수 없는 여러 호스트에 대한 기본 액세스 설정으로 사용됩니다.



/vol/vol0/sdprbac 경로에서 사용할 수 있는 DHOST-NAME.prbac 및 sdgeneric.prbac 파일이 모두 있는 경우, 'dsgeneric.prbac' 파일에 제공된 값을 덮어쓰므로 'DHOST-NAME.prbac'을 사용하여 액세스 권한을 확인합니다.

bothsdhost-name.prbac 및 sdgeneric.prbac 파일이 없는 경우, 'sapdrive.conf' 파일에 정의된 구성 변수 "_all-access-if-RBAC-unspecified_"를 확인하십시오.

지정된 호스트에서 지정된 vFiler 장치로 액세스 제어를 설정하는 것은 수동 작업입니다. 해당 호스트의 액세스는 영향을 받는 vFiler 유닛의 루트 볼륨에 있는 파일에 의해 제어됩니다. 이 파일에는 gethostname(3)이 반환한 "_host-name_"이 영향을 받는 호스트의 이름인 "/vol/<vfiler root volume>/sdprbac/sdhost-name.prbac"이 포함되어 있습니다. 이 파일을 액세스할 수 있는 호스트에서 이 파일을 읽을 수 있지만 쓸 수 없도록 해야 합니다.


NOTE: 호스트 이름을 확인하려면 호스트 이름 명령을 실행합니다.

파일이 비어 있거나 읽을 수 없거나 형식이 잘못된 경우 UNIX용 SnapDrive는 호스트 액세스 권한을 해당 작업에 부여하지 않습니다.

지정된 호스트에서 지정된 Vserver 장치에 대한 액세스 제어를 수동으로 설정하는 작업입니다. 특정 호스트의 액세스는 영향을 받는 Vserver 장치의 루트 볼륨에 상주하는 파일에 의해 제어됩니다. 이 파일은 이름이 '/vol/<vserver root volume>/sdhost-name.prbac'입니다. 여기서 host-name은 'gethostname(3)'에서 반환한 영향을 받는 호스트의 이름입니다. 이 파일을 액세스할 수 있는 호스트에서 이 파일을 읽을 수 있지만 쓸 수 없도록 해야 합니다.

[NOTE]
====
호스트 시스템에서 SVM 루트 볼륨을 마운트하고 ' *.prbac' 파일을 생성하려면 다음 명령을 실행합니다.

'* mount <vservername>:/<mntpoint> * '

====
파일이 없으면 SnapDrive for UNIX는 'sapdrive.conf' 파일에서 구성 변수 '_all-access-if-RBAC-unspecified_'를 확인합니다. 이 변수가 "On"(기본값)으로 설정되어 있으면 호스트가 해당 스토리지 시스템에서 이러한 모든 작업을 완벽하게 액세스할 수 있습니다. 변수가 "off"로 설정되어 있으면 SnapDrive for UNIX는 해당 스토리지 시스템에서 액세스 제어가 적용되는 작업을 수행할 수 있는 호스트 권한을 거부합니다.
