---
permalink: linux-administration/concept_crash_consistency_with_data_ontap_7_2_and_later.html 
sidebar: sidebar 
keywords: snap, snapdrive, crash, ontap, consistency, fences 
summary: UNIX용 SnapDrive는 Data ONTAP 7.2 이상 버전에서 제공하는 정합성 보장 그룹에 대한 지원을 사용하여 여러 볼륨에 걸쳐 있는 모든 스냅샷 복사본의 충돌 일관성을 유지합니다. 
---
= Data ONTAP 7.2 이상과 일관성 충돌
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
UNIX용 SnapDrive는 Data ONTAP 7.2 이상 버전에서 제공하는 정합성 보장 그룹에 대한 지원을 사용하여 여러 볼륨에 걸쳐 있는 모든 스냅샷 복사본의 충돌 일관성을 유지합니다.

Data ONTAP 버전 7.2 이상에서 일관성 그룹 및 스토리지 시스템 펜싱을 지원합니다. SnapDrive for UNIX는 이러한 기능을 사용하여 여러 볼륨에 걸쳐 있는 모든 Snapshot 복제본이 충돌의 일관성을 유지하도록 보장합니다.

여러 볼륨에 걸쳐 장애 발생 시 정합성이 보장되는 스냅샷 복사본을 생성하기 위해 UNIX용 SnapDrive는 다음을 수행합니다.

* Fence는 스토리지 요소가 포함된 모든 볼륨에 대한 입출력을 중지시킵니다.
* 각 볼륨의 스냅샷 복사본을 만듭니다.


볼륨을 울타리로 하고 스냅샷 복사본을 생성하는 데 걸리는 시간은 제한되어 있으며 Data ONTAP에서 제어합니다.

sapdrive.conf 파일의 ' * snapcreate-cg-timeout * ' 매개 변수는 스토리지 시스템 펜싱을 허용할 Data ONTAP 제한 범위 내의 시간을 지정합니다. 긴급, 중간 또는 여유 간격을 지정할 수 있습니다. 스토리지 시스템에서 펜싱 작업을 완료하는 데 허용되는 시간보다 더 많은 시간이 필요한 경우 SnapDrive for UNIX는 이전 Data ONTAP 7.2 버전의 정합성 보장 방법을 사용하여 스냅샷 복사본을 생성합니다. 스냅샷 복사본을 생성할 때 '-nfilerfence' 옵션을 사용하여 이 방법을 지정할 수도 있습니다.

Data ONTAP 7.2 및 이전 Data ONTAP 버전을 모두 사용하는 스토리지 시스템에 대해 스냅샷 복사본을 요청하면 SnapDrive for UNIX에서는 7.2 이전의 Data ONTAP 버전에 대한 일관성 방법을 사용하여 스냅샷 복사본도 생성합니다.
