---
permalink: linux-administration/concept_checks_that_can_be_overridden_by_the_user.html 
sidebar: sidebar 
keywords: snap, snapdrive, override, check 
summary: 볼륨 기반 SnapRestore를 수행하기 전에 SnapDrive for UNIX는 사용자가 -force 옵션을 사용하여 재정의할 수 있는지 일부 검사를 수행합니다. 볼륨 기반 SnapRestore를 안전하게 사용하려면 이러한 점검이 필요합니다. 
---
= 사용자가 재정의할 수 있는 검사
:icons: font
:imagesdir: ../media/


[role="lead"]
볼륨 기반 SnapRestore를 수행하기 전에 SnapDrive for UNIX는 사용자가 '-force' 옵션을 사용하여 재정의할 수 있는지 일부 검사를 수행합니다. 볼륨 기반 SnapRestore를 안전하게 사용하려면 이러한 점검이 필요합니다.

시스템에서 수행하는 다양한 검사를 따르는 것이 좋지만 '-force' 옵션을 사용하여 이러한 검사를 재정의할 수 있습니다.

볼륨 기반 SnapRestore 검사를 위해 UNIX용 다음 SnapDrive를 재정의할 수 있습니다.

* SnapDrive for UNIX는 장애 발생 시 정합성이 보장되지 않는 스냅샷 복사본의 LUN을 확인합니다. 스냅샷 복사본에서 애플리케이션 정합성이 보장되지 않는 LUN을 발견하면 경고 메시지가 표시됩니다.
* SnapDrive for UNIX는 스냅샷 복사본을 생성한 후 생성된 활성 볼륨에 추가 LUN이 있는지 확인합니다. SnapDrive for UNIX에서 추가 LUN을 찾으면 활성 볼륨의 추가 LUN이 손실된다는 경고가 표시됩니다.
* SnapDrive for UNIX에서 새 스냅샷 복사본이 있는지 확인합니다. 이러한 새 스냅샷 복사본은 복원되지 않으며 손실됩니다.
* SnapDrive for UNIX는 볼륨에서 일반 파일(로컬 호스트에서 볼 수 있는 파일)을 확인합니다.
* SnapDrive for UNIX에서 NFS 내보내기를 확인합니다.
* SnapDrive for UNIX에서 CIFS 공유를 확인합니다.


스냅샷 복사본이 UNIX용 SnapDrive 3.0 이전 버전을 사용하여 생성된 경우 볼륨 기반 SnapRestore 미리 보기에서는 앞에서 언급한 목록의 처음 두 검사를 수행할 수 없습니다. '-force' 옵션을 제공한 경우 볼륨 기반 SnapRestore 실행 중에 이러한 검사를 오버라이드 하고 진행하라는 메시지가 표시됩니다.
