---
permalink: linux-administration/concept_what_rbac_in_snapdrive_for_unix_is.html 
sidebar: sidebar 
keywords: snap, snapdrive, rbac, access, control, role, storage, limited, user 
summary: RBAC에서는 SnapDrive 관리자가 다양한 SnapDrive 작업을 위해 스토리지 시스템에 대한 액세스를 제한할 수 있습니다. 스토리지 작업에 대한 이 제한되거나 전체 액세스는 사용자에게 할당된 역할에 따라 달라집니다. 
---
= UNIX용 SnapDrive의 역할 기반 액세스 제어(RBAC)는 무엇입니까
:icons: font
:imagesdir: ../media/


[role="lead"]
RBAC에서는 SnapDrive 관리자가 다양한 SnapDrive 작업을 위해 스토리지 시스템에 대한 액세스를 제한할 수 있습니다. 스토리지 작업에 대한 이 제한되거나 전체 액세스는 사용자에게 할당된 역할에 따라 달라집니다.

UNIX 이상 버전의 SnapDrive 4.0에서는 UNIX용 모든 SnapDrive 작업에 대해 RBAC 액세스 검사가 필요합니다. 이 동작을 통해 스토리지 관리자는 할당된 역할에 따라 SnapDrive 사용자가 수행할 수 있는 작업을 제한할 수 있습니다. RBAC는 운영 관리자 인프라를 사용하여 구현됩니다. UNIX용 SnapDrive 4.0 이전 릴리즈에서는 액세스 제어가 제한적이며 루트 사용자만 UNIX용 SnapDrive 작업을 수행할 수 있었습니다. UNIX 이상용 SnapDrive 4.0은 Operations Manager 콘솔의 RBAC 인프라를 사용하여 비루트 로컬 사용자 및 NIS(Network Information System) 사용자를 지원합니다. UNIX용 SnapDrive는 스토리지 시스템의 루트 암호를 요구하지 않으며, SD-<hostname> 사용자를 사용하여 스토리지 시스템과 통신합니다.

기본적으로 Operations Manager 콘솔 RBAC 기능은 사용되지 않습니다. 'sapdrive.conf' 파일에서 '_RBAC-method=DFM_' 변수를 설정하고 UNIX 데몬용 SnapDrive를 다시 시작하여 RBAC 기능을 켜야 합니다.

이 기능을 사용하려면 다음 요구사항을 충족해야 합니다.

* Operations Manager 콘솔 3.7 이상
* Operations Manager 콘솔 서버는 SnapDrive 호스트 및 스토리지 시스템을 포함하는 IP 네트워크에 존재하고 구성해야 합니다.
* SnapDrive 설치 중에 Operations Manager 콘솔 통신 설정을 구성해야 합니다.
* UNIX용 SnapDrive 데몬이 실행되고 있어야 합니다.

