---
permalink: linux-administration/concept_supported_partition_devices.html 
sidebar: sidebar 
keywords: snap, snapdrive, support, storage, partitioning, multipathing 
summary: UNIX용 SnapDrive 5.0 이상은 다중 경로 및 비 다중 경로 환경을 위해 Linux에서 스토리지 파티셔닝을 제공합니다. 
---
= 지원되는 파티션 장치
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
UNIX용 SnapDrive 5.0 이상은 다중 경로 및 비 다중 경로 환경을 위해 Linux에서 스토리지 파티셔닝을 제공합니다.

지침을 따라 UNIX용 SnapDrive를 사용하여 스토리지 디바이스를 파티셔닝해야 합니다.

Linux에서 논리 볼륨 관리자를 사용하는 경우 분할되지 않은 LUN을 사용해야 합니다.

다음 표는 파티션 정보와 다른 운영 체제에서 사용할 수 있는 방법을 제공합니다.

|===
| 운영 체제 | 단일 파티션 | 다중 파티션 | 비 분할 장치 | 파일 시스템 또는 원시 디바이스 


 a| 
Red Hat Enterprise Linux 5배

또는

Oracle Enterprise Linux 5배
 a| 
예
 a| 
아니요
 a| 
아니요
 a| 
EXT3 *



 a| 
Red Hat Enterprise Linux 6x

또는

Oracle Enterprise Linux 6x
 a| 
예
 a| 
아니요
 a| 
아니요
 a| 
ext3 또는 ext4 *



 a| 
SUSE Linux Enterprise Server 11
 a| 
예
 a| 
아니요
 a| 
아니요
 a| 
EXT3 *



 a| 
SUSE Linux Enterprise Server 10
 a| 
아니요
 a| 
아니요
 a| 
예
 a| 
Ext3 ***



 a| 
Red Hat Enterprise Linux 5x 이상

또는

Oracle Enterprise Linux 5x 이상
 a| 
예
 a| 
아니요
 a| 
예
 a| 
ASM 및 ASMlib**



 a| 
SUSE Linux Enterprise Server 10 SP4

또는

SUSE Linux Enterprise Server 11
 a| 
예
 a| 
아니요
 a| 
예
 a| 
ASM 및 ASMlib**



 a| 
SUSE Linux Enterprise Server 10 SP4 이상

또는

SUSE Linux Enterprise Server 11
 a| 
예
 a| 
아니요
 a| 
아니요
 a| 
ASMlib 없이 ASM ****



 a| 
*

비 MPIO 환경의 경우, ' * sfdisk-us-f-L-q/dev/_device_name_ *' 명령을 입력합니다

MPIO 환경의 경우 다음 명령을 입력합니다.

* '* sfdisk-us-f-L-q/dev/_device_name_ *'
* '* kpartx-a-p p /dev/mapper/_device_name_ *'




 a| 
**

비 MPIO 환경의 경우 다음 명령을 입력합니다: `* fdisk /dev/_device_name_*'

MPIO 환경의 경우 다음 명령을 입력합니다.

* '* fdisk/dev/mapper/_device_name_ * '
* '* kpartx-a-p p /dev/mapper/_device_name_ *'




 a| 
***

해당 없음.



 a| 
\****

MPIO 환경의 경우 다음 명령을 입력합니다.

* '* kpartx-a-p p p/dev/$kernel*'


|===
* 일반 고려 사항 *

UNIX용 SnapDrive 4.2에서 생성된 스냅샷 복제본은 분할된 디바이스를 기반으로 합니다. 이러한 스냅샷 복사본은 SnapDrive for UNIX 5.0 이상 버전에서 복원, 연결 및 지원할 수 있습니다.
