---
permalink: linux-administration/concept_unable_to_restore_a_snapshot_copy.html 
sidebar: sidebar 
keywords: snap, snapdrive, snapshot, restore, command, issuelun, scsi 
summary: SnapDrive 스냅 복구 명령의 스냅샷 복사본 복구 기능에 영향을 미치는 조건은 거의 없습니다. 
---
= 스냅샷 복사본을 복원할 수 없습니다
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapDrive 스냅 복구 명령의 스냅샷 복사본 복구 기능에 영향을 미치는 조건은 거의 없습니다.

* 'SnapDrive snap restore' 명령은 다음 작업을 수행할 수 있어야 합니다.
+
** 모든 디스크 그룹에서 LUN 목록을 쿼리합니다.
** SCSI 명령을 통해 모든 LUN을 쿼리합니다. "SnapDrive snap restore" 명령이 성공하려면 호스트 볼륨과 파일 시스템을 사용하고 마운트할 필요가 없습니다.


* 액세스 권한을 통해 호스트에서 해당 스토리지 시스템에 대한 정보의 스냅샷 복사본을 생성하고 복구할 수 있어야 합니다.
* NFS 마운트 디렉토리를 마운트하려면 호스트에 올바르게 내보내야 합니다.



NOTE: LUN을 디스크 그룹에 추가하거나 디스크 그룹에서 제거한 후에는 항상 다른 스냅샷 복사본을 만들어야 합니다.

* 스냅샷 복사본을 생성한 후 디스크 그룹에 호스트 볼륨 또는 파일 시스템을 추가한 다음 스냅샷 복사본을 복원하려고 하면 오류 메시지가 표시됩니다. 이 상황에서 복원 작업이 성공하려면 명령줄에 "force" 옵션("-f")을 포함시켜야 합니다.
+

NOTE: 스냅샷 복사본을 생성한 후 추가하는 호스트 볼륨 및 파일 시스템은 스냅샷 복사본을 생성 및 복원할 때 더 이상 액세스할 수 없습니다.

* 스냅샷 복사본을 생성한 후 호스트 볼륨 또는 파일 시스템의 이름을 바꾸거나 마운트 지점을 변경한 다음 복원하려고 하면 복원 작업이 실패합니다. 이 상황에서 복원 작업이 성공하려면 명령줄에 "force" 옵션("-f")을 포함시켜야 합니다.
+

NOTE: '-f' 옵션을 신중하게 사용하면 덮어쓰지 않을 항목을 실수로 덮어쓰지 않도록 할 수 있습니다.

* 스냅샷 복사본을 생성한 후 LUN의 이름을 바꾼 다음 해당 스냅샷 복사본을 복원하려고 하면 복원 작업이 실패합니다. LUN의 이름을 바꾼 후에는 새 스냅샷 복사본을 만들어야 합니다.
+

NOTE: 스냅샷 복원 작업을 시작한 후 작업을 중지하지 마십시오. 이 작업을 중단하면 시스템이 일관되지 않은 상태가 될 수 있습니다. 그런 다음 수동 복구를 수행해야 할 수 있습니다.


