---
permalink: linux-administration/reference_informationrequired_for_the_storagecreate_operation.html 
sidebar: sidebar 
keywords: snap, snapdrive, storage, create, operation 
summary: 스토리지 생성 작업을 완료할 때 일부 정보를 제공해야 합니다. 
---
= 스토리지 생성 작업에 필요한 정보입니다
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 생성 작업을 완료할 때 일부 정보를 제공해야 합니다.

다음 표에는 'SnapDrive storage create' 명령을 사용하여 스토리지를 생성할 때 제공해야 하는 정보가 정리되어 있습니다.

|===
| 요구 사항 | 인수 


 a| 
프로비저닝할 스토리지의 유형을 결정합니다. 입력한 명령에 따라 다음 중 하나를 생성할 수 있습니다.

* LUN을 클릭합니다
+
하나 이상의 LUN을 생성하는 경우 첫 번째 인수는 긴 형식의 LUN 이름을 사용해야 합니다. 이 이름은 스토리지 시스템 이름, 볼륨 이름 및 볼륨 내의 LUN 이름을 지정합니다.

+
새 LUN이 이전 LUN과 동일한 스토리지 시스템 및 볼륨에 있는 경우 LUN 이름(짧은 이름)만 사용하여 추가 LUN을 지정할 수 있습니다. 그렇지 않으면 새 스토리지 시스템 이름과 볼륨 이름(또는 볼륨 이름)을 지정하여 이전 값을 바꿀 수 있습니다.

* LUN에 직접 생성된 파일 시스템입니다
+
LUN에 파일 시스템을 생성하는 경우 첫 번째 인수는 '_-fs_' 마운트 지점이어야 합니다. 스토리지 시스템 및 볼륨의 LUN에 파일 시스템을 생성하려면 '_-filervol_' 인수를 사용하여 스토리지 시스템 및 볼륨의 이름을 지정합니다. 특정 LUN에 파일 시스템을 생성하려면 '_-lun_' 인수를 사용하여 스토리지 시스템 이름, 볼륨 이름 및 LUN 이름을 지정합니다. 또한 호스트 LVM을 활성화하지 않고 LUN에 파일 시스템을 생성하려면 '-nolvm' 옵션을 포함해야 합니다.

+
기본적으로 SnapDrive for UNIX는 LUN에 대한 호스트 준비 및 검색과 관련된 모든 작업을 자동으로 수행하고 매핑 및 연결을 수행합니다.

+
Linux 호스트에서 LUN을 생성하는 경우 SnapDrive for UNIX는 다음 작업을 수행합니다.

+
** LUN을 생성합니다.
** LUN을 하나의 파티션으로 구성합니다.





NOTE: SLES10 업데이트 2를 사용하는 경우 원시 디바이스를 사용하여 파일 시스템을 생성합니다.

* 호스트 볼륨 및 파일 시스템이 있는 LVM 디스크 그룹
+
디스크 또는 볼륨 그룹, 파일 시스템 또는 호스트 또는 논리 볼륨을 지정할 때 SnapDrive for UNIX는 사용자가 지정하는 엔터티를 생성하는 데 필요한 모든 작업을 수행합니다. LUN을 명시적으로 지정하거나 스토리지 시스템 및 볼륨 정보를 제공하면 SnapDrive for UNIX에서 자동으로 LUN을 생성할 수 있습니다.

+
파일 시스템과 같은 엔터티를 생성하는 경우 디스크 또는 볼륨 그룹에 대한 값을 제공할 필요가 없습니다. UNIX용 SnapDrive에서 자동으로 하나를 생성합니다.





 a| 
* LUN(-LUN)

 a| 
' * long_lun_name * '



 a| 
* 추가 LUN

 a| 
' * lun_name * '(긴 형태 또는 짧은 형태)



 a| 
* 디스크 그룹('-dg * DgName * ') 또는 볼륨 그룹('-vg * vgname * ')

 a| 
'* disk*' 또는 '* volume group name*'



 a| 
SnapDrive for UNIX는 "-DG" 옵션으로 입력한 값에 따라 LUN을 보유할 디스크 또는 볼륨 그룹을 생성합니다. 그룹에 대해 제공한 이름이 없어야 합니다.



 a| 
* 호스트 볼륨('-hostvol * file_spec * ') 또는 논리 볼륨('-lvol * file_spec * ')

 a| 
'* 호스트*' 또는 '* 논리적 볼륨 이름*'



 a| 
* 파일 시스템('-fs * file_spec * ')

 a| 
'* filesystem_name*'



 a| 
-놀람
 a| 
~



 a| 
* 필수: * LUN에 직접 상주하는 파일 시스템을 생성하는 경우 '-nolvm' 옵션을 지정합니다.



 a| 
* LUN 크기('-lunsize')

 a| 
' * size * '



 a| 
* 디스크 그룹 크기('-dgsize')
* 볼륨 그룹 크기('-vgsize')

 a| 
' * size * '



 a| 
생성할 각 엔터티에 대한 크기(바이트 또는 기타 데이터 단위)를 지정합니다. LVM 개체의 크기는 요청한 LUN의 집계된 크기에 따라 달라집니다.

호스트 엔터티의 크기를 제어하려면 '-dgsize' 옵션을 사용하여 기본 디스크 그룹의 크기(바이트)를 지정합니다.



 a| 
* 스토리지 시스템 볼륨의 경로("-filervol")

 a| 
'* long_filer_path*'



 a| 
* '*-LUN*'

 a| 
' * long_lun_path * '



 a| 
SnapDrive for UNIX에서 LUN을 자동으로 생성할 스토리지 시스템과 해당 볼륨을 지정합니다.

* '-filervol' 옵션을 사용하여 LUN을 생성할 스토리지 시스템 및 볼륨을 지정합니다.
+
LUN을 지정하지 마십시오. SnapDrive for UNIX는 이러한 형식의 "SnapDrive storage create" 명령을 사용할 때 자동으로 LUN을 생성합니다. 시스템 기본값을 사용하여 LUN ID와 각 LUN 크기를 확인합니다. 연결된 디스크/볼륨 그룹의 이름은 호스트 볼륨 또는 파일 시스템의 이름을 기반으로 합니다.

* '-lun' 옵션을 사용하여 사용할 LUN의 이름을 지정하십시오.




 a| 
파일 시스템 유형('-fstype')
 a| 
' * 유형 * '



 a| 
파일 시스템을 생성하는 경우 파일 시스템 유형을 나타내는 문자열을 제공하십시오.

UNIX용 SnapDrive는 Linux('_ext4_' 또는 'ext3'을 허용합니다


NOTE: 기본적으로 UNIX용 SnapDrive는 호스트 플랫폼에 대해 파일 시스템 유형이 하나만 있는 경우 이 값을 제공합니다. 이 경우 입력할 필요가 없습니다.



 a| 
'-vmtype'입니다
 a| 
' * 유형 * '



 a| 
*선택 사항:* UNIX용 SnapDrive 작업에 사용할 볼륨 관리자 유형을 지정합니다.



 a| 
``반성파’’
 a| 
' * 옵션 이름 및 값 * '



 a| 
``문어’
 a| 
' * 옵션 이름 및 값 * '



 a| 
노persist
 a| 
~



 a| 
'-reserve|-noreserve'입니다
 a| 
~



 a| 
* 선택 사항: * 파일 시스템을 생성하는 경우 다음 옵션을 지정할 수 있습니다.

* 파일 시스템을 생성하는 데 사용되는 호스트 명령에 전달할 옵션을 지정하려면 '-fspts'를 사용합니다. 예를 들어, mkfs 명령이 사용할 옵션을 제공할 수 있습니다. 일반적으로 제공하는 값은 따옴표로 묶은 문자열이어야 하며 명령에 전달할 정확한 텍스트를 포함해야 합니다.
* 호스트 마운트 명령에 전달할 옵션(예: 호스트 시스템 로깅 동작 지정)을 지정하려면 `-mntopt'를 사용합니다. 지정하는 옵션은 호스트 파일 시스템 테이블 파일에 저장됩니다. 허용되는 옵션은 호스트 파일 시스템 유형에 따라 다릅니다.
+
'-mntopts' 인수는 ''t' 명령 '-o' 플래그를 사용하여 지정하는 파일 시스템 '-type' 옵션입니다. '_-mntopts_'에 '-o' 플래그를 포함시키지 마십시오. 예를 들어, 시퀀스 -mntopts tmplog는 문자열 -o tmplog를 -t tmplog에 전달하여 tmplog를 새 명령행에 삽입합니다.

+
enable-mount-with-netdev 설정 파라미터의 값이 off(기본값)로 설정되어 있으면 SnapDrive storage create 명령에서 -mntopts_netdev를 수동으로 지정해야 합니다. 그러나 값을 On으로 변경하면 SnapDrive storage create 명령을 실행하면 자동으로 `-mnttopts_netdev'가 실행됩니다.

+

NOTE: 스토리지 및 스냅 작업에 대해 잘못된 `_-mntopts_' 옵션을 전달하는 경우 UNIX용 SnapDrive는 이러한 잘못된 마운트 옵션의 유효성을 검사하지 않습니다.

* 호스트의 파일 시스템 마운트 테이블 파일(예: Linux의 fstab)에 항목을 추가하지 않고 파일 시스템을 생성하려면 -nopist를 사용합니다. 기본적으로 'SnapDrive storage create' 명령은 영구 마운트를 생성합니다. Linux 호스트에서 LVM 스토리지 엔터티를 생성하면 SnapDrive for UNIX가 스토리지를 자동으로 생성하고 파일 시스템을 마운트한 다음 호스트 파일 시스템 테이블에 파일 시스템에 대한 항목을 배치합니다. Linux 시스템에서 UNIX용 SnapDrive는 호스트 파일 시스템 테이블에 UUID를 추가합니다.
* '-reserve|-noreserve'를 사용하여 공간 예약을 생성하거나 생성하지 않고 스토리지를 생성합니다.




 a| 
* iGroup 이름("*-igroup *")

 a| 
' * IG_NAME * '



 a| 
* 선택 사항: * igroup 이름을 제공하는 대신 호스트에서 기본 igroup을 사용하는 것이 좋습니다.

|===