---
permalink: linux-administration/reference_product_overview.html 
sidebar: sidebar 
keywords: snap, snapdrive, product, overview, unix, data, management, snapshot 
summary: UNIX용 SnapDrive는 UNIX 환경을 위한 호스트 기반 스토리지 및 데이터 관리 솔루션입니다. SnapDrive for UNIX는 간소화된 스토리지 프로비저닝과 파일 시스템의 일관된 Snapshot 복사본을 통해 데이터 관리를 단순화하고, 데이터 가용성을 향상하며, 애플리케이션 데이터의 안정성을 높여줍니다. 
---
= 제품 개요
:icons: font
:imagesdir: ../media/


[role="lead"]
UNIX용 SnapDrive는 UNIX 환경을 위한 호스트 기반 스토리지 및 데이터 관리 솔루션입니다. SnapDrive for UNIX는 간소화된 스토리지 프로비저닝과 파일 시스템의 일관된 Snapshot 복사본을 통해 데이터 관리를 단순화하고, 데이터 가용성을 향상하며, 애플리케이션 데이터의 안정성을 높여줍니다.

UNIX용 SnapDrive를 독립 실행형 제품으로 사용하거나 UNIX에서 실행되는 다른 SnapManager 제품과 함께 사용할 수 있습니다. SnapDrive for UNIX와 SnapManager를 함께 구축하면 애플리케이션 정합성이 보장되는 데이터 백업을 생성할 수 있습니다.



== SnapDrive 하이라이트

UNIX용 SnapDrive를 사용하면 스토리지 관리 작업을 단순화할 수 있습니다. UNIX용 SnapDrive를 사용하여 수행할 수 있는 작업은 다음과 같습니다.

* Clustered Data ONTAPNetApp Snapshot 기술을 사용하여 스냅샷 복사본 생성
+
SnapDrive for UNIX를 사용하면 파일 시스템, 볼륨 그룹, 호스트 볼륨 또는 LUN의 스냅샷 복사본을 생성 및 삭제하고 스냅샷 복사본에서 스토리지 엔터티를 클론 복제할 수 있습니다.

* 애플리케이션 또는 호스트 다운타임이 거의 또는 전혀 없는 스토리지 프로비저닝 및 관리
+
SnapDrive for UNIX를 사용하면 호스트 클러스터 환경에서 디스크 그룹, 호스트 볼륨, 파일 시스템 및 LUN을 비롯한 스토리지 구성 요소를 생성하고 삭제할 수 있습니다. SnapDrive for UNIX를 사용하면 스토리지를 확장하고, 호스트에 스토리지를 연결하고, 호스트에서 스토리지의 연결을 끊을 수도 있습니다.

* 스토리지 관리자가 할당된 역할에 따라 SnapDrive 사용자가 수행할 수 있는 작업을 제한할 수 있도록 역할 기반 액세스 제어 제공


SnapDrive는 이러한 주요 기능 외에도 다음과 같은 이점을 제공합니다.

* 향상된 클론 분할 작업
* VBSR(볼륨 기반 SnapRestore)
* CLI(Command-Line Interface) 옵션
* 데이터 수집 유틸리티
* 스토리지 시스템의 이름 바꾸기 지원
* Linux 게스트 운영 체제에서 Fibre Channel RDM LUN 지원

