---
permalink: linux-administration/reference_exit_status_values.html 
sidebar: sidebar 
keywords: snap, snapdrive, exit, status, error, value 
summary: 각 종료 상태 값에는 오류 이름과 연관된 유형이 있습니다. 종료 상태 값, 오류 이름, 유형 및 설명에 대한 자세한 내용은 표를 참조하십시오. 
---
= 종료 상태 값
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
각 종료 상태 값에는 오류 이름과 연관된 유형이 있습니다. 종료 상태 값, 오류 이름, 유형 및 설명에 대한 자세한 내용은 표를 참조하십시오.

다음 표에는 종료 상태 값에 대한 정보가 나와 있습니다. 종료 상태 값은 순차적으로 번호가 매겨집니다. SnapDrive for UNIX에서 현재 오류를 구현하지 않는 경우 해당 종료 상태 값은 테이블에 포함되지 않습니다. 따라서 숫자에 약간의 차이가 있을 수 있습니다.

|===
| 종료 값 | 오류 이름 | 유형 | 설명 


 a| 
1
 a| 
지원되지 않습니다
 a| 
명령 오류입니다
 a| 
이 버전의 UNIX용 SnapDrive에서 지원되지 않는 함수가 호출되었습니다.



 a| 
2
 a| 
메모리가 없습니다
 a| 
치명적
 a| 
시스템의 메모리가 부족합니다. SnapDrive for UNIX는 메모리가 충분히 확보되어 작동할 때까지 계속할 수 없습니다. 실행 중인 다른 응용 프로그램이 과도한 메모리를 사용하고 있지 않은지 확인합니다.



 a| 
3
 a| 
명령이 잘못되었습니다
 a| 
명령 오류입니다
 a| 
잘못된 명령을 실행했습니다. 이는 입력한 명령의 텍스트에 있는 구문 오류일 수 있습니다.



 a| 
4
 a| 
이미 있습니다
 a| 
명령 오류입니다
 a| 
이미 존재하는 항목을 생성하도록 요청했습니다. 일반적으로 이 오류는 스냅샷 복사본을 생성할 스토리지 시스템 볼륨에 없어야 하는 스냅샷 복사본 이름을 나타냅니다.



 a| 
5
 a| 
스레드를 만들지 못했습니다
 a| 
관리자 오류입니다
 a| 
UNIX용 SnapDrive에서 프로세스 스레드를 생성할 수 없습니다. 시스템에서 실행 중인 다른 프로세스를 확인하여 충분한 스레드 리소스를 사용할 수 있는지 확인합니다.



 a| 
6
 a| 
찾을 수 없습니다
 a| 
명령 오류입니다
 a| 
존재하지 않는 UNIX용 SnapDrive 명령줄에 파일, 데이터 그룹, 호스트 볼륨, 파일 시스템 또는 기타 인수를 포함했습니다.



 a| 
7
 a| 
마운트된 파일 시스템이 아닙니다
 a| 
명령 오류입니다
 a| 
액세스하려는 파일 시스템이 유효한 파일 시스템이 아니거나 마운트되지 않았습니다.



 a| 
9
 a| 
볼륨 관리자 오류입니다
 a| 
명령 오류입니다
 a| 
볼륨 관리자에 액세스할 때 오류가 반환되었습니다. 오류 및 이유에 대한 자세한 내용은 특정 오류 메시지를 참조하십시오.



 a| 
10
 a| 
잘못된 이름입니다
 a| 
명령 오류입니다
 a| 
올바른 형식이 아닌 이름을 명령줄에 제공했습니다.

예를 들어, 스토리지 시스템 볼륨이 'filer:/vol/vol_name'으로 지정되지 않았습니다. 이 메시지는 스토리지 시스템 또는 볼륨 관리자 기반 이름에 잘못된 문자가 지정된 경우에도 발생합니다.



 a| 
11
 a| 
장치를 찾을 수 없습니다
 a| 
관리자 오류입니다
 a| 
UNIX용 SnapDrive에서는 스냅샷 복사본을 생성할 디스크 그룹의 LUN에 액세스할 수 없습니다.

호스트와 스토리지 시스템 모두에서 모든 LUN의 상태를 확인합니다. 또한 스토리지 시스템 볼륨이 온라인 상태인지, 스토리지 시스템이 호스트에 연결되어 있는지 확인합니다.



 a| 
12
 a| 
사용 중입니다
 a| 
명령 오류입니다
 a| 
LUN 디바이스, 파일, 디렉토리, 디스크 그룹, 호스트 볼륨, 또는 다른 엔티티가 사용 중입니다.

이는 일반적으로 명령을 다시 시도할 때 없어지는 치명적이지 않은 오류입니다. 리소스 또는 프로세스가 중단되어 SnapDrive for UNIX에서 사용할 수 없는 개체가 사용 중임을 나타내는 경우도 있습니다.

또한, 스냅샷 복사본을 성공적으로 생성할 수 있도록 I/O 트래픽이 너무 많은 기간 동안 스냅샷 복사본을 만들려고 시도할 수 있습니다.



 a| 
13
 a| 
초기화할 수 없습니다
 a| 
치명적
 a| 
UNIX용 SnapDrive가 필요한 타사 자료를 초기화할 수 없습니다. 이는 파일 시스템, 볼륨 관리자, 호스트 클러스터 소프트웨어, 다중 경로 소프트웨어 등을 나타낼 수 있습니다.



 a| 
14
 a| 
SnapDrive 사용 중
 a| 
SnapDrive 사용 중
 a| 
다른 사용자 또는 프로세스가 UNIX용 SnapDrive에 작업을 수행하도록 요청한 동시에 동일한 호스트 또는 스토리지 시스템에서 작업을 수행하고 있습니다. 작업을 다시 시도하십시오.

때때로 이 메시지는 다른 프로세스가 중단되어 이를 제거해야 함을 의미합니다.


NOTE: 경우에 따라 스냅샷 복원 작업에 시간이 오래 걸릴 수 있습니다. 멈춘 것으로 생각하는 프로세스가 스냅샷 복원 작업이 완료될 때까지 기다리는 것이 아닌지 확인합니다.



 a| 
15
 a| 
구성 파일 오류
 a| 
치명적
 a| 
SnapDrive.conf 파일에 유효하지 않거나 부적절하거나 일관되지 않은 항목이 있습니다. 자세한 내용은 특정 오류 메시지를 참조하십시오. UNIX용 SnapDrive를 계속하려면 이 파일을 수정해야 합니다.



 a| 
17
 a| 
잘못된 권한
 a| 
명령 오류입니다
 a| 
이 명령을 실행할 권한이 없습니다. UNIX용 SnapDrive를 실행하려면 루트로 로그인해야 합니다.



 a| 
18
 a| 
파일러가 없습니다
 a| 
관리자 오류입니다
 a| 
UNIX용 SnapDrive는 이 명령에 필요한 스토리지 시스템에 접속할 수 없습니다. 오류 메시지에 표시된 스토리지 시스템에 대한 접속을 확인하십시오.



 a| 
19
 a| 
파일러 로그인이 잘못되었습니다
 a| 
관리자 오류입니다
 a| 
SnapDrive for UNIX는 사용자가 제공한 로그인 정보를 사용하여 스토리지 시스템에 로그인할 수 없습니다.



 a| 
20
 a| 
잘못된 라이센스입니다
 a| 
관리자 오류입니다
 a| 
UNIX용 SnapDrive 서비스 요구 사항을 이 스토리지 시스템에서 실행할 수 있는 라이센스가 없습니다.



 a| 
22
 a| 
fs를 고정할 수 없습니다
 a| 
관리자 오류입니다
 a| 
SnapDrive for UNIX에서 스냅샷 복사본을 만들기 위해 지정된 파일 시스템을 동결할 수 없기 때문에 스냅샷 생성 작업이 실패했습니다. 시스템 입출력 트래픽이 파일 시스템을 동결할 수 있을 만큼 충분히 밝는지 확인한 후 명령을 재시도하십시오.



 a| 
27
 a| 
일관되지 않은 스냅샷 복사본이 있습니다
 a| 
관리자 오류입니다
 a| 
디스크 그룹의 이미지가 일관되지 않은 스냅샷 복사본에서 복원을 요청했기 때문에 스냅샷 복원 작업이 실패했습니다. 다음과 같은 경우 일관되지 않은 이미지가 발생할 수 있습니다.

* UNIX용 SnapDrive를 사용하여 스냅샷 복사본을 만들지는 않았습니다.
* 스냅샷 생성 작업이 정합성 보장 비트를 설정하기 전에 중단되어 심각한 시스템 장애 발생 시 정리할 수 없습니다.
* 스냅샷 복사본이 생성된 후 일부 유형의 데이터 문제가 발생했습니다.




 a| 
28
 a| 
HBA에 장애가 발생했습니다
 a| 
관리자 오류입니다
 a| 
SnapDrive for UNIX에서 HBA에서 정보를 검색하는 동안 오류가 발생했습니다.



 a| 
29
 a| 
잘못된 메타데이터
 a| 
관리자 오류입니다
 a| 
UNIX용 SnapDrive에서 스냅샷 복사본을 생성할 때 작성한 스냅샷 복사본 메타데이터에 오류가 발생했습니다.



 a| 
30
 a| 
Snapshot 복사본 메타데이터 없음
 a| 
관리자 오류입니다
 a| 
메타데이터에는 요청된 디스크 그룹이 모두 포함되어 있지 않으므로 UNIX용 SnapDrive에서 스냅샷 복원 작업을 수행할 수 없습니다.



 a| 
31
 a| 
잘못된 암호 파일입니다
 a| 
관리자 오류입니다
 a| 
암호 파일에 잘못된 항목이 있습니다. 이 스토리지 시스템의 로그인 항목을 삭제하려면 'SnapDrive config delete' 명령을 사용하십시오. 그런 다음 'SnapDrive config set_user_name_' 명령을 사용하여 로그인 정보를 다시 입력합니다.



 a| 
33
 a| 
암호 파일 항목이 없습니다
 a| 
관리자 오류입니다
 a| 
암호 파일에 이 스토리지 시스템에 대한 항목이 없습니다. UNIX용 SnapDrive를 실행해야 하는 모든 스토리지 시스템에 대해 "SnapDrive config set_username filername_" 명령을 실행합니다. 그런 다음 이 작업을 다시 시도하십시오.



 a| 
34
 a| 
NetAPPLUN이 아닙니다
 a| 
관리자 오류입니다
 a| 
UNIX용 SnapDrive 명령에서 NetApp 스토리지 시스템에 없는 LUN이 발생했습니다.



 a| 
35
 a| 
사용자가 중단되었습니다
 a| 
관리자 오류입니다
 a| 
시스템에서 작업을 확인하라는 메시지를 표시했고 작업을 수행하지 않으려는 것으로 표시했습니다.



 a| 
36
 a| 
I/O 스트림 오류입니다
 a| 
관리자 오류입니다
 a| 
시스템 입력 또는 시스템 출력 루틴에서 SnapDrive for UNIX가 이해하지 못한 오류가 반환되었습니다.

SnapDrive.DC를 실행하고 NetApp 기술 지원 부서에 해당 정보를 보내 복구 완료를 위해 수행할 단계를 결정할 수 있도록 합니다.



 a| 
37
 a| 
파일 시스템이 가득 찼습니다
 a| 
관리자 오류입니다
 a| 
파일 시스템에 공간이 부족하여 파일 쓰기 시도가 실패했습니다. 적절한 파일 시스템에서 충분한 공간을 확보하면 UNIX용 SnapDrive를 계속 진행할 수 있습니다.



 a| 
38
 a| 
파일 오류
 a| 
관리자 오류입니다
 a| 
UNIX용 SnapDrive가 시스템 구성 파일 또는 임시 파일을 읽거나 쓰는 동안 I/O 오류가 발생했습니다.



 a| 
39
 a| 
디스크 그룹이 중복됩니다
 a| 
명령 오류입니다
 a| 
디스크 그룹을 활성화하려고 할 때 UNIX용 SnapDrive에 중복된 부 노드 번호가 있습니다.



 a| 
40
 a| 
파일 시스템 해동에 실패했습니다.
 a| 
관리자 오류입니다
 a| 
파일 시스템의 시스템 작업으로 인해 스냅 생성 명령이 실패했습니다. 이 문제는 일반적으로 스냅샷 복사본에 필요한 UNIX용 SnapDrive 파일 시스템이 중지되어 스냅샷 복사본이 완료되기 전에 시간 초과되는 경우에 발생합니다.



 a| 
43
 a| 
이름이 이미 사용 중입니다
 a| 
명령 오류입니다
 a| 
UNIX용 SnapDrive가 디스크 그룹, 호스트 볼륨, 파일 시스템 또는 LUN 생성을 시도했지만 이름이 이미 사용 중입니다. 수정하려면 사용 중이 아닌 이름을 선택하고 UNIX용 SnapDrive 명령을 다시 입력합니다.



 a| 
44
 a| 
파일 시스템 관리자 오류입니다
 a| 
치명적
 a| 
UNIX용 SnapDrive에서 다음과 같은 경우 파일 시스템에서 예상치 못한 오류가 발생했습니다.

* 파일 시스템을 생성하려고 합니다
* 파일 시스템 마운트 테이블에 항목을 만들어 부팅 시 파일 시스템을 자동으로 마운트합니다.


이 코드와 함께 표시되는 오류 메시지 텍스트는 파일 시스템에서 발생한 오류를 설명합니다. 메시지를 녹음하고 NetApp 기술 지원 부서에 보내서 복구를 완료하기 위해 수행해야 할 단계를 결정하는 데 도움을 줄 수 있습니다.



 a| 
45
 a| 
마운트 지점 오류입니다
 a| 
관리자 오류입니다
 a| 
파일 시스템 마운트 지점 지점이 시스템 마운트 테이블 파일에 나타납니다. 이 문제를 해결하려면 마운트 테이블에 사용 중이거나 나열되지 않은 마운트 지점을 선택하고 SnapDrive for UNIX 명령을 다시 입력합니다.



 a| 
46
 a| 
LUN을 찾을 수 없습니다
 a| 
명령 오류입니다
 a| 
UNIX용 SnapDrive 명령이 스토리지 시스템에 없는 LUN에 액세스하려고 했습니다.

문제를 해결하려면 LUN이 있고 LUN 이름이 올바르게 입력되었는지 확인하십시오.



 a| 
47
 a| 
이니시에이터 그룹을 찾을 수 없습니다
 a| 
관리자 오류입니다
 a| 
스토리지 시스템 이니시에이터 그룹을 예상대로 액세스할 수 없습니다. 따라서 UNIX용 SnapDrive는 현재 작업을 완료할 수 없습니다.

특정 오류 메시지는 문제를 해결하기 위해 수행해야 하는 단계와 문제에 대해 설명합니다. 문제를 해결한 다음 명령을 반복합니다.



 a| 
48
 a| 
개체가 오프라인 상태입니다
 a| 
관리자 오류입니다
 a| 
UNIX용 SnapDrive가 개체(예: 볼륨)에 액세스를 시도했지만 개체가 오프라인 상태여서 실패했습니다.



 a| 
49
 a| 
충돌하는 요소
 a| 
명령 오류입니다
 a| 
UNIX용 SnapDrive가 igroup 작성을 시도했지만 동일한 이름의 igroup을 발견했습니다.



 a| 
50
 a| 
정리 오류입니다
 a| 
치명적
 a| 
UNIX용 SnapDrive에 제거해야 하지만 여전히 남아 있는 항목이 있습니다.



 a| 
51
 a| 
디스크 그룹 ID가 충돌합니다
 a| 
명령 오류입니다
 a| 
SnapDrive snap connect 명령을 통해 기존 디스크 그룹과 충돌하는 디스크 그룹 ID가 요청되었습니다.

이는 대개 원래 호스트에서 SnapDrive snap connect 명령을 지원하지 않는 시스템에서 시도한다는 것을 의미합니다. 이 문제를 해결하려면 다른 호스트에서 작업을 시도하십시오.



 a| 
52
 a| 
LUN이 호스트에 매핑되지 않았습니다
 a| 
관리자 오류입니다
 a| 
LUN이 어떤 호스트에도 매핑되지 않았습니다. 즉, 스토리지 시스템 이니시에이터 그룹에 속하지 않습니다. LUN을 액세스할 수 있으려면 SnapDrive for UNIX 외부의 현재 호스트에 매핑되어야 합니다.



 a| 
53
 a| 
LUN이 로컬 호스트에 매핑되지 않았습니다
 a| 
관리자 오류입니다
 a| 
LUN이 현재 호스트에 매핑되지 않았습니다. 즉, 현재 호스트의 이니시에이터를 포함하는 스토리지 시스템 이니시에이터 그룹에 속하지 않습니다. LUN을 액세스할 수 있으려면 SnapDrive for UNIX 외부의 현재 호스트에 매핑되어야 합니다.



 a| 
54
 a| 
LUN이 외부 igroup을 사용하여 매핑되어 있습니다
 a| 
관리자 오류입니다
 a| 
LUN은 외부 스토리지 시스템 이니시에이터 그룹을 사용하여 매핑됩니다. 다시 말해, 로컬 호스트에서 찾을 수 없는 이니시에이터만 포함된 스토리지 시스템 igroup에 속해 있습니다.

따라서 UNIX용 SnapDrive에서는 LUN을 삭제할 수 없습니다.

UNIX용 SnapDrive를 사용하여 LUN을 삭제하려면 LUN이 로컬 igroup에만 속해 있어야 합니다. 즉, 로컬 호스트에 있는 이니시에이터만 포함된 igroup입니다.



 a| 
55
 a| 
LUN이 혼합 igroup을 사용하여 매핑되어 있습니다
 a| 
관리자 오류입니다
 a| 
LUN은 혼합 스토리지 시스템 이니시에이터 그룹을 사용하여 매핑됩니다. 다시 말해, 로컬 호스트에서 찾은 이니시에이터와 이니시에이터가 모두 없는 스토리지 시스템 igroup에 속해 있습니다.

따라서 UNIX용 SnapDrive에서는 LUN의 연결을 끊을 수 없습니다.

UNIX용 SnapDrive를 사용하여 LUN을 분리하려면 LUN이 로컬 igroup 또는 외부 igroup에만 속해 있어야 하며 Igroup이 혼합되지 않아야 합니다. (로컬 igroup에는 로컬 호스트에 있는 이니시에이터만 포함되어 있으며, 외부 igroup에는 로컬 호스트에서 이니시에이터를 찾을 수 없습니다.)



 a| 
56
 a| 
스냅샷 복사본을 복원하지 못했습니다
 a| 
관리자 오류입니다
 a| 
SnapDrive for UNIX에서 스냅샷 복원 작업을 시도했지만 스냅샷 복사본의 LUN을 복원하지 않고 오류가 발생했습니다.

특정 오류 메시지는 문제를 해결하기 위해 수행해야 하는 단계와 문제에 대해 설명합니다. 문제를 해결한 다음 명령을 반복합니다.



 a| 
58
 a| 
호스트를 재부팅해야 합니다
 a| 
관리자 오류입니다
 a| 
내부 데이터를 업데이트하려면 호스트 운영 체제를 재부팅해야 합니다. SnapDrive for UNIX가 이 업데이트를 위해 호스트를 준비했지만 현재 작업을 완료할 수 없습니다.

호스트를 재부팅한 다음 이 메시지가 나타나는 SnapDrive for UNIX 명령줄을 다시 입력하십시오. 재부팅 후 작업을 완료할 수 있습니다.



 a| 
59
 a| 
호스트, LUN 준비가 필요합니다
 a| 
관리자 오류입니다
 a| 
현재 작업을 완료하려면 호스트 운영 체제에 내부 데이터를 업데이트해야 합니다. 이 업데이트는 새 LUN을 생성할 수 있도록 해야 합니다.

SnapDrive for UNIX는 'napdrive.conf' variable'_enable-implicit-host-preparation_'이 ""off""로 설정되어 있기 때문에 프로비저닝을 위한 자동 호스트 준비가 비활성화되어 있기 때문에 업데이트를 수행할 수 없습니다.

자동 호스트 준비가 비활성화된 경우 SnapDrive config prepare LUNs 명령을 사용하여 호스트에서 LUN을 프로비저닝하거나 준비 단계를 수동으로 수행해야 합니다.

이 오류 메시지를 방지하려면, 'sapdrive.conf' 파일에서 '_enable-implicit-host-preparation_' 값을 ""on""으로 설정하십시오.



 a| 
62
 a| 
비어 있지 않습니다
 a| 
명령 오류입니다
 a| 
UNIX용 SnapDrive가 스토리지 시스템 볼륨 또는 디렉토리를 제거할 수 없기 때문에 오류가 발생했습니다. 다른 사용자나 다른 프로세스가 SnapDrive가 삭제하려고 하는 동일한 디렉토리에 파일을 정확하게 동시에 생성할 때 이 문제가 발생할 수 있습니다. 이 오류를 방지하려면 한 번에 한 명의 사용자만 스토리지 시스템 볼륨에서 작업해야 합니다.



 a| 
63
 a| 
시간 초과가 만료되었습니다
 a| 
명령 오류입니다
 a| 
UNIX용 SnapDrive가 50분의 제한 시간 내에 LUN을 복구할 수 없기 때문에 오류가 발생했습니다.

메시지를 녹음하고 NetApp 기술 지원 부서에 보내서 복구를 완료하기 위해 수행해야 할 단계를 결정하는 데 도움을 줄 수 있습니다.



 a| 
64
 a| 
서비스가 실행되고 있지 않습니다
 a| 
관리자 오류입니다
 a| 
UNIX용 SnapDrive 명령이 NFS 엔터티를 지정했고 스토리지 시스템에서 NFS 서비스를 실행하지 않아 오류가 발생했습니다.



 a| 
126을 참조하십시오
 a| 
알 수 없는 오류입니다
 a| 
관리자 오류입니다
 a| 
심각할 수 있는 알 수 없는 오류가 발생했습니다. 'napdrive.dc' 유틸리티를 실행하고 그 결과를 NetApp 기술 지원 팀에 전송하여 분석을 합니다.



 a| 
127로 표시됩니다
 a| 
내부 오류입니다
 a| 
치명적
 a| 
UNIX용 SnapDrive 내부 오류가 발생했습니다. 'napdrive.dc'를 실행하고 그 결과를 NetApp 기술 지원 팀에 보내 분석을 수행합니다.

|===