---
permalink: linux-administration/task_enabling_and_disabling_log_files.html 
sidebar: sidebar 
keywords: snap, snapdrive, enable, disable, log, file, name 
summary: 로그 파일을 활성화하려면 활성화할 로그 파일의 이름-값 쌍의 값으로 파일 이름을 지정합니다. 파일을 비활성화하려면 로그 파일 이름 매개 변수의 값을 입력하지 마십시오. 
---
= 로그 파일 활성화 및 비활성화
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
로그 파일을 활성화하려면 활성화할 로그 파일의 이름-값 쌍의 값으로 파일 이름을 지정합니다. 파일을 비활성화하려면 로그 파일 이름 매개 변수의 값을 입력하지 마십시오.

루트 사용자로 로그인해야 합니다.

.단계
. 텍스트 편집기에서 'napdrive.conf' 파일을 엽니다.
. 로그 파일을 활성화하거나 비활성화하려면 적절한 옵션을 선택합니다.
+
|===
| 원하는 작업 | 그러면... 


 a| 
* 로그 파일 활성화 *
 a| 
 Specify a file name as the value in the name-value pair of the log file you want to enable. SnapDrive for UNIX only writes log files if it has the name of a file to write to. The default names for the log files are as follows:
** 감사 로그:'d-audit.log'
** 복구 로그:'d-recovery.log'
** 추적 로그:'d-trace.log'



NOTE: 이러한 파일의 경로는 호스트 운영 체제에 따라 다를 수 있습니다.



 a| 
* 로그 파일 비활성화 *
 a| 
 Do not enter a value for the log file name parameter. If you do not supply a value, there is no file name to which SnapDrive for UNIX can write the log information.
* 예제 * 이 예제에서는 감사 로그 파일을 비활성화합니다. 'audit-log-file=""

|===
. 변경 사항을 모두 적용한 후 'napdrive.conf' 파일을 저장합니다.
+
SnapDrive for UNIX는 시작할 때마다 이 파일을 자동으로 검사합니다. 변경 사항을 적용하려면 SnapDrive for UNIX 데몬을 다시 시작해야 합니다.


