---
permalink: linux-administration/task_setting_values_in_the_snapdrive_conf_file.html 
sidebar: sidebar 
keywords: snap, snapdrive, conf, value, name 
summary: SnapDrive.conf 파일에서 값을 변경하거나 새 이름 값 쌍을 추가할 수 있습니다. 
---
= SnapDrive.conf 파일에서 값을 설정합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
'napdrive.conf' 파일에서 값을 변경하거나 새 이름-값 쌍을 추가할 수 있습니다.

루트 사용자로 로그인해야 합니다.

.단계
. 'napdrive.conf' 파일을 백업합니다.
. 텍스트 편집기에서 'napdrive.conf' 파일을 엽니다.
. 이름 값 쌍을 추가하려면 다음 형식을 사용합니다.
+
``config-option-name=value value#선택적 comment*'

+
'_config-option-name_'은 감사 로그 파일과 같이 구성하려는 변수의 이름입니다. '_value_'는 이 옵션에 지정할 값입니다.

+
이름-값 쌍이 있는 주석을 포함하려면 주석 앞에 숫자 기호(#)를 붙입니다.

+
한 줄에 하나의 이름-값 쌍만 입력해야 합니다.

+
이름이나 값에 문자열을 사용하는 경우 문자열을 작은따옴표(''') 또는 큰따옴표(")로 묶습니다. 전체 이름-값 쌍 또는 값 주위에 따옴표를 배치할 수 있습니다. 다음 예제에서는 이름-값 쌍을 사용하여 따옴표 및 주석을 사용하는 방법을 보여 줍니다.

+
"*""config-option-one=string with white space"#double quotes around the pair *"

+
"* config-option-two="string with white space"#큰따옴표 * 값 *

+
(* config-option-2B="'공백을 사용한 추적'#값 주위의 작은따옴표 * "

. 이름 값 쌍을 수정하려면 현재 값을 새 값으로 바꿉니다.
+
아래 단계에 따라 기본값을 파일에 기록했는지 확인하십시오.

+
.. 수정할 줄에 기호(#)를 추가합니다.
.. 선을 복사합니다.
.. 숫자 기호(#)를 제거하여 복사한 텍스트를 활성화합니다.
.. 값을 수정합니다.


+
감사 로그 파일을 사용하지 않도록 설정하는 등의 빈 값을 지정하려면 큰따옴표(" ")를 입력합니다.

. 변경한 후 파일을 저장합니다.
+
SnapDrive for UNIX는 시작할 때마다 이 파일을 자동으로 검사합니다. 변경 사항은 다음에 시작될 때 적용됩니다.

. 'drapsed restart' 명령을 사용하여 UNIX용 SnapDrive 데몬을 다시 시작합니다.
+
'napdrive.conf' 파일 변경 내용을 적용하려면 데몬을 다시 시작해야 합니다.


