---
permalink: linux-administration/task_enabling_multipathing.html 
sidebar: sidebar 
keywords: snap, snapdrive, multipathing, enable, hba 
summary: UNIX용 SnapDrive에서 다중 경로를 사용하려면 HBA 설치 및 시작을 포함하는 단계를 완료해야 합니다. 타사 다중 경로 솔루션을 사용하는 경우 HBA 공급업체의 웹 사이트에서 소프트웨어 및 애플리케이션 패키지를 다운로드해야 합니다. 
---
= 다중 경로 설정
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
UNIX용 SnapDrive에서 다중 경로를 사용하려면 HBA 설치 및 시작을 포함하는 단계를 완료해야 합니다. 비 NetApp 다중 경로 솔루션을 사용하는 경우 HBA 공급업체의 웹 사이트에서 소프트웨어 및 애플리케이션 패키지를 다운로드해야 합니다.

시스템에서 최신 버전의 FC 및 iSCSI 시스템 구성 요소를 실행 중이어야 합니다.

http://mysupport.netapp.com/matrix["NetApp 상호 운용성 매트릭스 툴"]

.단계
. 적절한 Host Utilities 소프트웨어를 설치하기 전에 지원되는 HBA를 설치합니다.
+

NOTE: UNIX용 SnapDrive는 멀티벤더 HBA를 지원합니다.

. HBA 서비스를 시작합니다.
+
HBA 서비스가 실행되고 있지 않으면 SnapDrive for UNIX 명령을 실행할 때 SnapDrive storage create와 SnapDrive config prepare LUNs와 같은 다음 오류 메시지가 표시됩니다.

+
[listing]
----
0001-876 Admin error: HBA assistant not found
----
+
필요한 경로 수가 실행 중인지 확인해야 합니다. Host Utilities 소프트웨어에 포함된 'Anlun' 유틸리티를 사용하여 경로를 확인할 수 있습니다. 예를 들어 FC 다중 경로 구성에서 'show fcp show adapter-v' 명령을 사용할 수 있습니다.

+
다음 예에서는 작동 중인 호스트(포트 상태)에 연결된 HBA 포트 2개(fcd0 및 fcd1)가 있습니다. HBA 또는 iSCSI 이니시에이터만 사용할 수 있으며 타겟 LUN에 대한 경로를 두 개 이상 제공하여 다중 경로를 구성해야 합니다.

+
[listing]
----
# sanlun fcp show adapter -v
adapter name: fcd0
WWPN: 50060b000038c428
WWNN: 50060b000038c429
driver name: fcd
model: A6826A
model description: Fibre Channel Mass Storage Adapter
(PCI/PCI-X)
serial number: Not Available
hardware version: 3
driver version: @(#) libfcd.a HP Fibre Channel
ISP 23xx & 24xx Driver B.11.23.04
/ux/core/isu/FCD/kern/src/common/wsio/fcd_init.c:Oct 18
2005,08:19:50
firmware version: 3.3.18
Number of ports: 1 of 2
port type: Fabric
port state: Operational
supported speed: 2 GBit/sec
negotiated speed: 2 GBit/sec
OS device name: /dev/fcd0
adapter name: fcd1
WWPN: 50060b000038c42a
WWNN: 50060b000038c42b
driver name: fcd
model: A6826A
model description: Fibre Channel Mass Storage Adapter
(PCI/PCI-X)
serial number: Not Available
hardware version: 3
driver version: @(#) libfcd.a HP Fibre Channel
ISP 23xx & 24xx Driver B.11.23.04
/ux/core/isu/FCD/kern/src/common/wsio/fcd_init.c:Oct 18
2005,08:19:50
firmware version: 3.3.18
Number of ports: 2 of 2 port type: Fabric
port state: Operational
supported speed: 2 GBit/sec
negotiated speed: 2 GBit/sec
OS device name: /dev/fcd1
----
+
호스트에서 다중 경로가 설정되어 있으면 동일한 LUN에 대해 여러 경로가 표시됩니다. 'show all' 명령을 사용하여 경로를 확인할 수 있습니다. 다음 예에서는 동일한 LUN에 대한 여러 경로를 찾을 수 있습니다('fish:/vol/vol1/lun').

+
[listing]
----
 [root@lnx221-75 ~]# sanlun lun show
filer:        lun-pathname device filename adapter protocol lun size lun state
f960-221-167: /vol/vol1/lun1 /dev/sdd host5 FCP 100m (104857600)      GOOD
f960-221-167: /vol/vol1/lun1 /dev/sdc host6 FCP 100m (104857600)      GOOD
----
. SnapDrive for UNIX 또는 Host Utilities에서 타사 경로 다중화 솔루션을 지원하는 경우 HBA 공급업체의 웹 사이트에서 HBA 드라이버 소프트웨어 패키지 및 애플리케이션 패키지를 다운로드하십시오.* QLogic*: QLogic HBA의 경우 로 이동하십시오 http://support.qlogic.com/[]. OEM 모델에서 NetApp을 선택합니다. 지원 매트릭스에 나열된 드라이버 버전을 찾아 다운로드합니다. * Emulex: * Emulex HBA의 경우 로 이동합니다 http://www.emulex.com/ts/index.html[]. 다운로드 에서 NetApp 을 선택합니다. 지원 매트릭스에 나열된 드라이버 버전을 찾아 다운로드합니다. 또한 동일한 위치에서 Emulex 응용 프로그램 패키지를 다운로드합니다.
+
QLogic 어댑터를 FC 접속과 함께 사용하는 경우 QLogic 웹 사이트에서 QLogic rescan 스크립트를 다운로드하여 '/root' 경로(예: '/root/dynamic-lun-rescan.sh')로 복사하십시오. QLogic 재검색 스크립트는 사용자 확인을 요청합니다. UNIX용 SnapDrive는 이 확인 단계에서 무기한 중단될 수 있습니다. 스크립트의 변수 '_QL_DISABLE_WARNING_'을 '1'로 설정하면 이 확인을 피할 수 있습니다.

+
이전 버전의 UNIX용 SnapDrive에서는 공급업체별 SCSI 재검색 스크립트를 사용하여 FC를 통해 LUN을 검사함으로써 공급업체별 스크립트를 "/root/dynamic-lun-rescan.sh"에 복사했습니다. 이 기능은 RHEL 5U3까지 사용할 수 있습니다.

+
RHEL 5U4/SLES 10SP2 이상 버전의 경우 재검색 스크립트는 현재 '/usr/bin' 디렉토리에 있습니다. 디렉토리에 rescan 스크립트가 없는 경우 'G3_utils' 패키지와 함께 제공됩니다.

+

NOTE: RHEL(Red Hat Enterprise Linux) 및 OEL(Oracle Enterprise Linux) 버전에서 'sG3_utils' 및 'sG3_utils-libs' 라이브러리를 사용할 수 있는지 확인해야 합니다. 그러나 Scsci utility.rpm 패키지에서 SLES(SUSE Linux Enterprise Server) 버전용 SG3_utils 라이브러리를 사용할 수 있습니다.

. FC 구성에서는 스위치 조닝 구성을 사용하여 호스트 HBA 포트와 타겟 포트를 조닝(zoning)합니다.
. 적절한 FC 스위치를 설치하고 설정합니다.
. SnapDrive에서 UNIX 스택 요구 사항을 확인합니다.
. UNIX용 SnapDrive를 설치하거나 업그레이드합니다.
. UNIX용 SnapDrive 설치를 확인합니다.
. 'napdrive.conf' 파일 경로를 찾습니다.
. 'napdrive.conf' 파일에서 다음 구성 변수를 구성합니다.
+
** '_multipathing-type_'
** '_default-transport_'
** `_''
** '_vmtype_'
+
모든 호스트에서 다중 경로 유형, 전송 유형, 파일 시스템 및 볼륨 관리자 유형은 상호 종속적입니다. 다음 표는 가능한 모든 조합을 설명합니다.

+
|===
| 호스트 플랫폼 | 기본 전송 유형입니다 | 다중 경로 유형입니다 | fstype 을 선택합니다 | vmtype입니다 


 a| 
리눅스
 a| 
iSCSI
 a| 
네이티브엠피오
 a| 
ext4 또는 ext3
 a| 
LVM



 a| 
iSCSI
 a| 
없음
 a| 
ext4 또는 ext3
 a| 
LVM



 a| 
FCP
 a| 
없음
 a| 
ext4 또는 ext3
 a| 
LVM



 a| 
FCP
 a| 
네이티브엠피오
 a| 
ext4 또는 ext3
 a| 
LVM

|===
+
위의 표에는 '_multipathing-type_', '_default-transport_', '_fstype_', '_vmtype_' 설정 변수의 지원되는 값이 나와 있습니다.

+

NOTE: 전송 프로토콜이 "iSCSI"이고 다중경로 유형이 "없음"으로 설정된 경우 다중 경로 데몬을 중지하고 SnapDrive for UNIX 명령을 실행해야 합니다.



. 'napdrive.conf' 파일을 저장합니다.
+
SnapDrive for UNIX는 시작할 때마다 이 파일을 자동으로 검사합니다. 변경 사항을 적용하려면 SnapDrive for UNIX 데몬을 다시 시작해야 합니다.



* 관련 정보 *

xref:concept_snaprestore_and_snapconnect_operations_do_not_work_in_linux_after_multipathing_migration.adoc[다중 경로 유형 마이그레이션 후 Linux에서 SnapRestore 및 Snapconnect 작업이 작동하지 않습니다]

http://mysupport.netapp.com["NetApp 지원"]

https://mysupport.netapp.com/NOW/products/interoperability["NetApp 상호 운용성"]

https://library.netapp.com/ecm/ecm_download_file/ECMLP2547936["Linux Unified Host Utilities 7.1 설치 가이드"]
