---
permalink: linux-administration/task_setting_up_access_control_permission.html 
sidebar: sidebar 
keywords: snap, snapdrive, access, control, permission, directory 
summary: 스토리지 시스템의 루트 볼륨에 특수 디렉토리와 파일을 생성하여 SnapDrive for UNIX에서 액세스 제어 권한을 설정할 수 있습니다. 
---
= 액세스 제어 권한을 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 시스템의 루트 볼륨에 특수 디렉토리와 파일을 생성하여 SnapDrive for UNIX에서 액세스 제어 권한을 설정할 수 있습니다.

루트 사용자로 로그인했는지 확인합니다.

.단계
. 대상 스토리지 시스템의 루트 볼륨에 'dsprbac' 디렉토리를 생성합니다.
+
루트 볼륨을 액세스 가능하게 만드는 한 가지 방법은 NFS를 사용하여 볼륨을 마운트하는 것입니다.

. 'dsprbac' 디렉토리에 권한 파일을 작성합니다. 다음 내용이 참인지 확인하십시오.
+
** 파일 이름은 DHOST-NAME.prbac이어야 합니다. 여기서 host-name은 액세스 권한을 지정하는 호스트의 이름입니다.
** UNIX용 SnapDrive에서 읽을 수는 있지만 수정할 수는 없도록 파일을 읽기 전용으로 설정해야 합니다.


+
dev-sun1 액세스 권한을 호스트에게 부여하려면 스토리지 시스템에 '/vol/vol1/sdprbac/sddev-sun1.prbac' 파일을 생성합니다

. 해당 호스트에 대한 파일의 권한을 설정합니다.
+
파일에 다음 형식을 사용해야 합니다.

+
** 하나의 권한 수준만 지정할 수 있습니다. 호스트에 모든 작업에 대한 전체 액세스 권한을 부여하려면 ALL ACCESS 문자열을 입력합니다.
** 권한 문자열은 파일에서 첫 번째 문자열이어야 합니다. 권한 문자열이 첫 번째 줄에 없으면 파일 형식이 유효하지 않습니다.
** 권한 문자열은 대/소문자를 구분하지 않습니다.
** 사용 권한 문자열 앞에 공백이 없어야 합니다.
** 설명은 허용되지 않습니다.
+
이러한 유효한 권한 문자열은 다음과 같은 액세스 수준을 허용합니다.

** 없음 -- 호스트에 스토리지 시스템에 대한 액세스 권한이 없습니다.
** 스냅 생성 -- 호스트에서 스냅샷 복사본을 생성할 수 있습니다.
** 스냅 사용 -- 호스트에서 스냅샷 복사본을 삭제하고 이름을 바꿀 수 있습니다.
** 모두 스냅 -- 호스트에서 스냅샷 복사본을 생성, 복구, 삭제 및 이름 변경할 수 있습니다.
** 스토리지 생성 삭제 -- 호스트는 스토리지를 생성, 크기 조정 및 삭제할 수 있습니다.
** 스토리지 사용 -- 호스트는 스토리지를 연결 및 연결 해제할 수 있으며 스토리지에서 클론 분할 추정치 및 클론 분할 시작을 수행할 수도 있습니다.
** 스토리지 모두 -- 호스트는 스토리지를 생성, 삭제, 연결 및 연결 해제할 수 있으며 스토리지에서 클론 분할 추정치 및 클론 분할 시작을 수행할 수도 있습니다.
** 모든 액세스 -- 호스트는 UNIX용 이전의 모든 SnapDrive 작업에 액세스할 수 있습니다.
+
이러한 각 사용 권한 문자열은 서로 다릅니다. 스냅 사용을 지정하는 경우 호스트는 스냅샷 복사본을 삭제하거나 이름을 바꿀 수 있지만 스냅샷 복사본을 생성하거나 스토리지 프로비저닝 작업을 수행하거나 복구할 수는 없습니다.



+
설정한 권한에 관계없이 호스트는 표시 및 목록 작업을 수행할 수 있습니다.

. 다음 명령을 입력하여 액세스 권한을 확인합니다.
+
'* SnapDrive 구성 액세스에는 filer_name*이 표시됩니다


