---
permalink: linux-installation-7mode/reference_where_to_go_next.html 
sidebar: sidebar 
keywords: snap, snapdrive, after, configure, create, copy 
summary: 'UNIX용 SnapDrive를 구성하고 스냅샷 복사본을 생성한 후에는 복원 작업을 수행하고 스냅샷 복사본을 연결하고 클론을 생성할 수 있습니다. 역할 기반 액세스 제어\(RBAC\), 향상된 클론 분할 및 볼륨 기반 SnapRestore와 같은 다른 중요한 SnapDrive 기능을 탐색할 수도 있습니다.' 
---
= 다음 단계로 넘어갑니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
UNIX용 SnapDrive를 구성하고 스냅샷 복사본을 생성한 후에는 복원 작업을 수행하고 스냅샷 복사본을 연결하고 클론을 생성할 수 있습니다. 역할 기반 액세스 제어(RBAC), 고급 클론 분할, 볼륨 기반 SnapRestore와 같은 다른 중요한 SnapDrive 기능을 탐색할 수도 있습니다.

이러한 기능에 대한 자세한 내용과 UNIX용 SnapDrive에 대한 릴리스 관련 정보는 NetApp Support 사이트 에서 제공되는 다음 문서를 참조하십시오.

* link:../linux-administration/index.html["Linux용 UNIX용 SnapDrive 5.3.2 관리 가이드"]
+
구축이 완료된 후 UNIX용 SnapDrive에서 다양한 기능을 구성하는 방법에 대해 설명합니다. 이 주제에는 igroup 구성, UNIX용 SnapDrive 구성, RBAC 구성 및 데이터 수집 유틸리티를 사용하여 UNIX용 SnapDrive의 문제를 진단하는 방법이 포함되어 있습니다.

* https://library.netapp.com/ecm/ecm_download_file/ECMLP2849339["UNIX용 SnapDrive 5.3.2 릴리스 노트(AIX, Linux 및 Solaris)"]
+
UNIX용 SnapDrive 5.3.2의 새로운 기능, 중요 주의 사항, 알려진 문제 및 제한 사항에 대해 설명합니다.

* https://library.netapp.com/ecm/ecm_download_file/ECMP12471545["7-Mode로 운영되는 UNIX용 Data ONTAP 3.4 Oracle 설치 및 설정 가이드 SnapManager"]
+
UNIX 환경에서 7-Mode를 사용하는 Oracle용 SnapManager를 구축하기 위해 수행해야 하는 초기 작업에 대해 설명합니다. 제품 설치 및 구성 방법과 데이터베이스 백업 방법이 포함되어 있습니다.

* link:https://www.netapp.com/pdf.html?item=/media/16322-tr-4212.pdf["NetApp 기술 보고서 4212: SnapDrive for UNIX 5.3 모범 사례 가이드"]
+
UNIX용 SnapDrive Best Practice에 대해 설명합니다.


