---
permalink: aix/concept_considerations_for_network_file_system.html 
sidebar: sidebar 
keywords: snap, snapdrive, guidelines, nfs, configuration 
summary: 'UNIX용 SnapDrive를 설치하기 전에 네트워크 파일 시스템\(NFS\) 서비스가 실행되는 위치와 스토리지 시스템 디렉토리를 내보낼 위치를 고려해야 합니다. NFS 클라이언트 권한 및 인터페이스 읽기-쓰기 권한을 확인해야 합니다.' 
---
= NFS 구성에 대한 지침입니다
:icons: font
:imagesdir: ../media/


[role="lead"]
UNIX용 SnapDrive를 설치하기 전에 NFS(네트워크 파일 시스템) 서비스가 실행되는 위치와 스토리지 시스템 디렉토리를 내보낼 위치를 고려해야 합니다. NFS 클라이언트 권한 및 인터페이스 읽기-쓰기 권한을 확인해야 합니다.

UNIX용 SnapDrive를 사용하여 NFS 마운트 디렉토리를 복구하거나 연결할 경우 스토리지 시스템 디렉토리를 호스트로 올바르게 내보내야 합니다. 호스트에 스토리지 시스템을 액세스할 수 있는 여러 IP 인터페이스가 있는 경우 각 IP 인터페이스로 디렉토리를 올바르게 내보내야 합니다.

UNIX용 SnapDrive는 이러한 모든 인터페이스에 읽기/쓰기 권한이 없거나, '-readonly' 옵션이 있는 SnapDrive 스냅 접속의 경우 또는 적어도 읽기 전용 권한이 없는 경우 경고를 발행합니다. 이들 인터페이스 중 디렉터리에 액세스할 수 있는 권한이 없으면 SnapDrive snap restore 및 SnapDrive snap connect 명령이 실패합니다.

SFSR(Single File SnapRestore)을 루트 사용자로 수행하는 경우 스토리지 시스템 디렉토리를 호스트에서 읽기-쓰기 권한으로 내보내야 하며 다음과 같은 내보내기 규칙을 설정해야 합니다.

* 7-Mode로 운영되는 Data ONTAP의 ``rw=<hostname>, root=<hostname>'
* Clustered Data ONTAP의 'rwrule=sys,rorule=sys,superuser=sys'


* 관련 정보 *

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.cdot-famg-nfs/home.html["ONTAP 9 NFS 참조"]

https://library.netapp.com/ecm/ecm_download_file/ECMP1401220["7-Mode용 Data ONTAP 8.2 파일 액세스 및 프로토콜 관리 가이드 를 참조하십시오"]
