---
permalink: aix/concept_informationrequired_forusing_the_snapdrive_snapconnect_command.html 
sidebar: sidebar 
keywords: snap, snapdrive, connect, command, required, information 
summary: 스냅샷 복사본에 연결하려면 스토리지 개체의 유형을 확인하고 스냅샷 복사본을 NFS 디렉토리 트리와 함께 Data ONTAP 7.3 구성 등에 연결합니다. 
---
= SnapDrive snap connect 명령을 사용하는 데 필요한 정보입니다
:icons: font
:imagesdir: ../media/


[role="lead"]
스냅샷 복사본에 연결하려면 스토리지 개체의 유형을 확인하고 스냅샷 복사본을 NFS 디렉토리 트리와 함께 Data ONTAP 7.3 구성 등에 연결합니다.

다음 표는 SnapDrive snap connect 명령을 사용할 때 제공해야 하는 정보를 제공합니다.


NOTE: 'Snap connect' 작업에는 AIX 기반의 vximport용 Storage Foundation Enterprise 라이센스가 필요합니다.

|===
| 요구 사항/옵션 | 인수 


 a| 
스냅샷 복사본을 연결하는 데 사용할 스토리지 엔터티의 유형을 결정하고 해당 개체의 이름을 적절한 인수로 제공합니다. 이것은 '_src_fspec_' 인수의 값입니다.

* LUN의 스냅샷 복사본을 연결하는 경우 SnapDrive for UNIX는 사용자가 지정한 LUN을 연결합니다. 같은 명령줄에 -vg, -dg, -fs, -lvol 또는 -hostvol 옵션과 함께 -lun 옵션을 사용할 수 없습니다. lun_name 또는 qtree_name/lun_name 형식으로 LUN의 짧은 이름을 지정할 수 있습니다.
* LUN에 직접 생성된 파일 시스템의 스냅샷 복사본을 연결하는 경우 SnapDrive for UNIX는 파일 시스템이 있는 LUN을 연결합니다.
* 호스트 볼륨 또는 파일 사양이 있는 디스크 그룹의 스냅샷 복사본을 연결하면 인수가 스토리지 시스템의 디스크 그룹 집합으로 변환됩니다. SnapDrive for UNIX는 엔터티가 호스트 볼륨 또는 파일 시스템이더라도 엔터티가 포함된 전체 디스크 그룹을 연결합니다.
* NFS 파일 시스템의 스냅샷 복사본을 연결하는 경우 인수는 NFS 디렉토리 트리로 변환됩니다. SnapDrive for UNIX는 볼륨의 FlexClone을 생성하고 스냅샷 복사본에 지정되지 않은 디렉토리 트리를 제거한 다음 NFS 디렉토리 트리를 연결 및 마운트합니다. NFS 마운트 지점을 지정하는 경우 동일한 명령줄에 NFS가 아닌 엔터티('-vg', '-dg', '-fs', '-lvol' 또는 '-hostvol')를 지정할 수 없습니다.
+

NOTE: UNIX용 SnapDrive는 마운트 지점 레벨에서 심볼 링크를 지원하지 않습니다.





 a| 
LUN('-lun_file_spec_')
 a| 
_LUN의 짧은 이름입니다. _



 a| 
'_s_lun_name_'은 '-snapname_long_snap_name_'에 있는 LUN을 지정합니다. 짧은 lun_name이 필요합니다. 스토리지 시스템 또는 스토리지 시스템 볼륨 이름은 포함할 수 없습니다. '_d_lun_name_'은 LUN이 연결되는 이름을 지정합니다. 짧은 '_LUN_NAME_'이(가) 필요합니다. 스토리지 시스템 또는 스토리지 시스템 볼륨 이름은 포함할 수 없습니다. '_d_lun_name_'을(를) 지정해야 합니다



 a| 
디스크 그룹('-dg_file_spec_') 또는 볼륨 그룹('-vg_file_spec_')
 a| 
_ 디스크 또는 볼륨 그룹의 이름 _



 a| 
파일 시스템('-fs_file_spec_')
 a| 
_ 파일 시스템의 이름 _



 a| 
호스트 볼륨('-hostvol_file_spec_') 또는 논리 볼륨('-lvol_file_spec_')
 a| 
_호스트 또는 논리적 볼륨의 이름 _



 a| 
NFS 디렉토리 트리를 사용하여 스냅샷 복사본을 Data ONTAP 7.3 구성에 연결합니다.

* 구성에서 Data ONTAP 7.3 이상 버전의 FlexVol를 기존(Data ONTAP 아님) 볼륨과 함께 사용하는 경우 이 옵션을 지정하여 읽기 전용 액세스(필수)로 스냅샷 복사본을 연결해야 합니다.
* 구성에서 Data ONTAP 7.3 이상 및 FlexVol 볼륨을 사용하는 경우 UNIX용 SnapDrive는 자동으로 읽기-쓰기 액세스를 제공합니다. 읽기 전용(선택 사항)으로 액세스를 제한하려는 경우에만 이 옵션을 지정합니다.




 a| 
읽기 전용입니다
 a| 
_읽기 전용 권한 설정 _



 a| 
선택 사항: 스토리지 엔티티가 연결된 후 대상 엔터티에 액세스할 수 있는 이름을 지정합니다. SnapDrive for UNIX는 이 이름을 사용하여 대상 엔터티를 연결합니다. 이것은 '_dest_file_spec_' 주장입니다.

이 이름을 생략하면 'Snap connect' 명령은 '_src_fspec_'에 입력한 값을 사용합니다.



 a| 
대상 요소의 이름입니다
 a| 
'_dest_file_spec_'



 a| 
선택 사항: 대상 스토리지 엔터티의 이름을 지정합니다. 이 정보를 '_dest_fspec/src_fspec_' 쌍의 일부로 포함했다면 여기에 입력하지 않아도 됩니다.

이 정보가 "_dest_fspec/src_fspec_" 쌍의 일부가 아닌 경우 "-destxx" 옵션을 사용하여 대상 스토리지 엔터티의 이름을 지정할 수 있습니다. 예를 들어, '-fs' 옵션은 대상 마운트 지점만 명명하므로 '-destdg' 옵션을 사용하여 대상 디스크 그룹을 지정할 수 있습니다.

대상 디스크 그룹에서 엔터티를 연결하는 데 필요한 이름을 지정하지 않으면 'SnapDrive snap connect' 명령은 소스 디스크 그룹의 이름을 사용합니다.

대상 디스크 그룹의 엔터티를 연결하는 데 필요한 이름을 지정하지 않으면 'Snap connect' 명령은 소스 디스크 그룹의 이름을 사용합니다. 이 이름을 사용할 수 없는 경우 명령 프롬프트에 '-autorename'을 포함시키지 않으면 작업이 실패합니다.



 a| 
대상 디스크 그룹('-destdg') 또는 대상 볼륨 그룹('-destvg')
 a| 
'_DgName_'



 a| 
대상 논리 볼륨('-destlv') 또는 대상 호스트 볼륨('-desthv')
 a| 
'_lvname_'



 a| 
스냅샷 복사본의 이름을 지정합니다. 스토리지 시스템 이름, 볼륨 및 스냅샷 복사본 이름을 입력하는 이름의 긴 형식을 사용합니다.



 a| 
스냅샷 사본 이름('-snapname')
 a| 
'_long_snap_name_'



 a| 
노persist
 a| 
~



 a| 
선택 사항: 호스트 파일 시스템 테이블에 항목을 생성하지 않고 스냅샷 복사본을 새 위치에 연결합니다.

* '-nopist' 옵션을 사용하면 호스트 파일 시스템 테이블에 항목을 생성하지 않고 스냅샷 복사본을 새 위치에 연결할 수 있습니다. 기본적으로 SnapDrive for UNIX는 영구 마운트를 생성합니다. 이는 다음을 의미합니다.
+
** AIX 호스트에서 스냅샷 복사본을 연결하면 SnapDrive for UNIX가 파일 시스템을 마운트한 다음 파일 시스템을 구성하는 LUN의 항목을 호스트의 파일 시스템 테이블에 배치합니다.
** NFS 디렉토리 트리가 포함된 스냅샷 복사본을 연결하는 데 '-nopist'를 사용할 수 없습니다.






 a| 
'-reserve|-noreserve'입니다
 a| 
~



 a| 
선택 사항: 공간 예약을 생성하거나 생성하지 않고 스냅샷 복사본을 새 위치에 연결합니다.



 a| 
iGroup 이름('-igroup')
 a| 
'_IG_NAME_'



 a| 
선택 사항: igroup 이름을 제공하는 대신 호스트에서 기본 igroup을 사용하는 것이 좋습니다.



 a| 
'-자동 확장'
 a| 
~



 a| 
볼륨 그룹에 연결할 때 제공해야 하는 정보의 양을 줄이려면 명령 프롬프트에 '-autoexpand' 옵션을 포함합니다. 이 옵션을 사용하면 볼륨 그룹에 있는 논리적 볼륨 또는 파일 시스템의 하위 집합만 이름을 지정할 수 있습니다. 그런 다음 디스크 그룹의 나머지 논리적 볼륨 또는 파일 시스템으로 접속을 확장합니다. 이러한 방식으로 각 논리적 볼륨 또는 파일 시스템을 지정할 필요가 없습니다. SnapDrive for UNIX는 이 정보를 사용하여 대상 엔터티의 이름을 생성합니다.

이 옵션은 명령 프롬프트에 지정된 각 디스크 그룹과 그룹 내의 모든 호스트 LVM 엔티티에 적용됩니다. '-autoexpand' 옵션(기본값)이 없으면 디스크 그룹에 포함된 영향을 받는 모든 호스트 볼륨 및 파일 시스템을 지정하여 전체 디스크 그룹을 연결해야 합니다.


NOTE: 입력한 값이 디스크 그룹인 경우 SnapDrive for UNIX는 디스크 그룹이 접속하고 있는 항목을 알고 있으므로 모든 호스트 볼륨이나 파일 시스템을 입력할 필요가 없습니다.

이 옵션을 포함할 경우 '-autorename' 옵션도 포함하는 것이 좋습니다. '-autoexpand' 옵션이 LVM 엔터티의 대상 사본을 연결해야 하지만 이름이 이미 사용 중이면 명령 프롬프트에 '-autorename' 옵션이 없으면 명령이 실패합니다.



 a| 
autoexpand를 포함하지 않고 명령 프롬프트에서 참조되는 모든 디스크 그룹에 모든 LVM 호스트 볼륨을 지정하지 않으면 명령이 실패합니다(호스트 볼륨 자체 또는 파일 시스템 지정).



 a| 
'-autorename'
 a| 
~



 a| 
autorename 옵션 없이 `-autostexpand' 옵션을 사용하면 LVM 엔터티의 대상 복사본에 대한 기본 이름이 사용 중이면 'snap connect' 명령이 실패합니다. '-autorename' 옵션을 포함하면 기본 이름이 사용 중일 때 SnapDrive for UNIX에서 엔터티의 이름을 바꿉니다. 즉, 명령 프롬프트에서 -autorename 옵션을 사용하면 필요한 모든 이름을 사용할 수 있는지 여부와 관계없이 스냅샷 연결 작업이 계속됩니다.

이 옵션은 명령 프롬프트에 지정된 모든 호스트측 엔터티에 적용됩니다.

명령 프롬프트에 '-autorename' 옵션을 포함하면 해당 옵션을 포함하지 않더라도 -autostExpand 옵션을 나타냅니다.



 a| 
'-스플릿'
 a| 
~



 a| 
스냅샷 연결 및 스냅샷 연결 끊기 작업 중에 클론 복제된 볼륨 또는 LUN을 분할할 수 있습니다.



 a| 
문어
 a| 
~



 a| 
* 선택 사항: * 파일 시스템을 생성하는 경우 다음 옵션을 지정할 수 있습니다.

* 호스트 마운트 명령에 전달할 옵션(예: 호스트 시스템 로깅 동작 지정)을 지정하려면 `-mntopt'를 사용합니다. 지정하는 옵션은 호스트 파일 시스템 테이블 파일에 저장됩니다. 허용되는 옵션은 호스트 파일 시스템 유형에 따라 다릅니다.
* '_-mntopts_' 인수는 mount 명령 '-o' 플래그를 사용하여 지정하는 파일 시스템 '-type' 옵션입니다. '_-mntopts_'에 '-o' 플래그를 포함시키지 마십시오. 예를 들어, sequence-mntopt tmplog는 문자열 '-o tmplog'를 'mount' 명령으로 전달하고 텍스트를 새 명령줄에 삽입합니다.
+

NOTE: 스토리지 및 스냅 작업에 대해 잘못된 `_-mntopts_' 옵션을 전달하는 경우 UNIX용 SnapDrive는 이러한 잘못된 마운트 옵션의 유효성을 검사하지 않습니다.



|===