---
permalink: aix/concept_contents_of_autosupport_message_in_snapdrive_for_unix.html 
sidebar: sidebar 
keywords: snap, snapdrive, autosupport, message, support 
summary: AutoSupport 메시지에는 다음 정보가 포함됩니다. 
---
= AutoSupport 메시지의 내용입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AutoSupport 메시지에는 다음 정보가 포함됩니다.

* 이벤트 소스입니다
* 이벤트 ID입니다
* UNIX용 SnapDrive 버전입니다
* 메시지 상태: 로그 수준 메시지(예: 경고 1개, 위험 2개, 오류 3개, 경고 4개, 알림 5개) 6을 참조하십시오. 7은 디버그용 입니다
* 호스트 이름입니다
* 호스트 운영 체제입니다
* 호스트 운영 체제의 릴리스 버전입니다
* 스토리지 시스템의 이름입니다
* Protection Manager/역할 기반 액세스 제어 사용
* 오류 범주입니다
* AutoSupport 플래그 메시지 항목을 false로 설정합니다
* Host Multipathing type:'napdrive.conf' 파일에 설정된 값이 기록됩니다. 구성 값이 잘못되어 비서가 로드되지 않으면 호스트 경로 다중화 유형이 기록되지 않습니다.
* 호스트 가상화 사용: VMware 게스트 운영 체제에만 캡처됩니다.
* Protocol:'napdrive.conf' 파일에서 '_default-transport_'에 대해 구성된 값입니다.
* 보호 설정: SnapDrive DFM(Data Fabric Manager)이 UNIX용 OnCommand로 구성된 경우 값 '_Yes_'가 기록됩니다.
+

NOTE: SnapDrive for UNIX는 OnCommand DFM이 사용 중인지 여부를 확인하지 않습니다.



'SnapDrive storage show-all' 명령을 실행하면 다음과 같은 추가 정보를 사용할 수 있습니다.

* 프로토콜 유형(FCP/iSCSI): LUN을 생성하는 데 사용되는 프로토콜(있는 경우)
* 접속된 LUN의 수입니다
* 디스크 또는 볼륨 그룹의 수입니다
* 파일 사양 수
* 호스트 볼륨 수입니다



NOTE: UNIX용 SnapDrive에서 AutoSupport를 사용하도록 설정한 경우 작업 실패 시 EVM(이벤트 관리 시스템) 스토리지 시스템에 오류 메시지가 기록됩니다. 오류 메시지에 (<,>, &, ','," 등의 특수 문자가 포함된 경우 r), 왜곡된 값이 스토리지 시스템의 EMS 로그 보기에 표시됩니다.
