---
permalink: aix/concept_what_snapdrive_for_unix_is.html 
sidebar: sidebar 
keywords: snap, snapdrive, storage, management, provisioning 
summary: UNIX용 SnapDrive는 스토리지 관리 작업을 단순화합니다. SnapDrive for UNIX는 스냅샷 기술을 사용하여 공유 또는 비공유 스토리지 시스템에 저장된 데이터의 이미지를 생성합니다. 또한 SnapDrive는 스토리지 프로비저닝을 지원합니다. 
---
= UNIX용 SnapDrive의 기능
:icons: font
:imagesdir: ../media/


[role="lead"]
UNIX용 SnapDrive는 스토리지 관리 작업을 단순화합니다. SnapDrive for UNIX는 스냅샷 기술을 사용하여 공유 또는 비공유 스토리지 시스템에 저장된 데이터의 이미지를 생성합니다. 또한 SnapDrive는 스토리지 프로비저닝을 지원합니다.

UNIX용 SnapDrive를 사용하여 다음 작업을 수행할 수 있습니다.

* ** 데이터 백업 및 복원:** UNIX용 SnapDrive를 사용하면 스냅샷 기술을 사용하여 스토리지 시스템에 저장된 호스트 데이터의 이미지(스냅샷 복사본)를 만들 수 있습니다. 이 스냅샷 복사본은 나중에 복원할 수 있는 데이터 복사본을 제공합니다. 스냅샷 복사본의 데이터는 한 스토리지 시스템에 존재하거나 여러 스토리지 시스템과 해당 볼륨에 걸쳐 있을 수 있습니다. 이러한 스토리지 시스템은 HA 쌍, 노드 로컬 파일 시스템 또는 디스크 그룹, 호스트 클러스터 환경의 LUN일 수 있습니다.
* * 스토리지 관리: * 호스트 클러스터 및 비 클러스터 환경의 디스크 그룹, 호스트 볼륨, 파일 시스템 및 LUN을 비롯한 스토리지 구성 요소를 생성하고 삭제할 수 있습니다. UNIX용 SnapDrive를 사용하면 스토리지를 확장하고 호스트에 연결한 다음 연결을 끊어 이 스토리지를 관리할 수 있습니다.
* ** 역할 기반 액세스 제어:** UNIX용 SnapDrive는 역할 기반 액세스 제어(RBAC)를 제공합니다. RBAC에서는 SnapDrive 관리자가 다양한 SnapDrive 작업을 위해 스토리지 시스템에 대한 액세스를 제한할 수 있습니다. 스토리지 작업에 대한 이 액세스는 사용자에게 할당된 역할에 따라 달라집니다. 스토리지 관리자는 RBAC를 사용하여 SnapDrive 사용자가 할당된 역할에 따라 수행할 수 있는 작업을 제한할 수 있습니다.

