---
permalink: aix/concept_types_of_logs.html 
sidebar: sidebar 
keywords: snap, snapdrive, log, type, troubleshoot 
summary: UNIX용 SnapDrive는 다양한 유형의 로그 파일을 지원하므로 UNIX용 SnapDrive가 예상대로 작동하지 않을 때 문제를 해결하는 데 도움이 됩니다. 
---
= 로그 유형
:icons: font
:imagesdir: ../media/


[role="lead"]
UNIX용 SnapDrive는 다양한 유형의 로그 파일을 지원하므로 UNIX용 SnapDrive가 예상대로 작동하지 않을 때 문제를 해결하는 데 도움이 됩니다.

* 감사 로그
+
UNIX용 SnapDrive는 모든 명령과 반환 코드를 감사 로그에 기록합니다. UNIX용 SnapDrive는 명령을 시작할 때 항목을 만들고 명령이 완료되면 다른 명령을 입력합니다. 나중에 입력할 때는 명령의 상태와 완료 시간이 모두 포함됩니다.

* 복구 로그
+
UNIX용 일부 SnapDrive 작업의 경우 중단된 경우 시스템이 일관되지 않거나 사용 가능한 상태가 되지 않을 수 있습니다. 이 상황은 사용자가 프로그램을 종료하거나 작업 중에 호스트가 충돌하는 경우에 발생할 수 있습니다. 복구 로그에는 스냅 복구 작업의 단계가 포함되어 있습니다. 기술 지원 부서에서 수동 복구 프로세스를 지원할 수 있도록 수행된 단계 및 진행 상황을 문서화합니다.

* 추적 로그
+
SnapDrive for UNIX는 문제 진단에 유용한 정보를 보고합니다. 문제가 있는 경우 NetApp 기술 지원 부서에서 이 로그 파일을 요청할 수 있습니다.

+
UNIX용 SnapDrive 4.0에는 UNIX용 SnapDrive 데몬 서비스가 도입되었습니다. SnapDrive for UNIX 명령을 실행하려면 데몬이 실행되고 있어야 합니다. 명령이 병렬로 실행되는 경우에도 각 개별 명령에 대해 데몬 추적을 수행해야 합니다. 로그 파일의 위치와 이름은 '/var/log/sd-trace.log'입니다. 이러한 추적 파일에는 명령 관련 추적 항목만 있습니다. 데몬 실행을 위한 추적 로그는 다른 추적 파일 '/var/log/sd-daemon-trace.log'에 기록됩니다.


