---
permalink: aix/concept_about_the_data_collection_utility.html 
sidebar: sidebar 
keywords: snap, snapdrive, data, collection, utility 
summary: 'SnapDrive for UNIX는 UNIX용 SnapDrive, SnapDrive 구성 검사기 및 시스템 설정에 대한 진단 정보를 수집하는 데이터 수집 유틸리티 \(SnapDrive.DC\)를 제공합니다.' 
---
= 데이터 수집 유틸리티에 대해 설명합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
UNIX용 SnapDrive는 UNIX용 SnapDrive, SnapDrive 구성 검사기 및 시스템 설정에 대한 진단 정보를 수집하는 데이터 수집 유틸리티('napdrive.dc')를 제공합니다.

이 작업은 NetApp 진단 유틸리티를 실행하고 UNIX용 SnapDrive 로그 파일을 특수 디렉토리에 복사하여 수행합니다. 그런 다음 이 정보가 포함된 압축 파일을 생성하고 분석을 위해 NetApp 기술 지원 팀에 전송할 수 있습니다.

UNIX용 SnapDrive 5.0에서는 '-dump' 및 '-dumpall' 옵션이 구현됩니다. '-dump' 옵션은 SnapDrive 명령의 첫 번째 로그를 수집하고 '-dumpall' 옵션은 SnapDrive 명령의 모든 로그를 수집합니다. dump 또는 -dumpall 옵션을 사용하여 SnapDrive 작업을 수행하면, 'napdrive.dc'가 생성되고 압축된 파일 위치가 나열됩니다. tar 파일은 SnapDrive 명령의 모든 로그 정보를 수집하며, tar 파일의 압축을 풀고 해당 위치에서 파일을 검색할 수 있습니다.

SnapDrive storage show, SnapDrive storage create, SnapDrive storage delete, SnapDrive snap create, SnapDrive snap connect 등 SnapDrive 명령에 대해 dump 또는 dumpall 옵션이 구현되어 있다. SnapDrive snap disconnect, SnapDrive snap restore, SnapDrive clone split estimate, SnapDrive clone split start 등의 작업이 있습니다.


NOTE: 스토리지 시스템의 로그인 정보가 포함된 파일은 복사하지 않습니다. 또한 구성을 변경하지 않습니다.
