---
permalink: aix/concept_informationrequired_forusing_the_snapdrive_snaprestore_command.html 
sidebar: sidebar 
keywords: snap, snapdrive, restore, command, information, required 
summary: 스냅샷 복사본을 복원하려면 복원할 스토리지 엔터티를 결정하고 스냅샷 복사본의 이름을 지정하는 방법 등을 수행합니다. 
---
= SnapDrive snap restore 명령을 사용하는 데 필요한 정보입니다
:icons: font
:imagesdir: ../media/


[role="lead"]
스냅샷 복사본을 복원하려면 복원할 스토리지 엔터티를 결정하고 스냅샷 복사본의 이름을 지정하는 방법 등을 수행합니다.

다음 표는 SnapDrive snap restore 명령을 사용할 때 제공해야 하는 정보를 제공합니다.

|===
| 요구 사항/옵션 | 인수 


 a| 
복원하려는 스토리지 엔터티의 유형을 결정하고 적절한 인수를 사용하여 해당 개체의 이름을 입력합니다.

* 복구할 호스트 볼륨이나 파일 시스템을 지정하면 해당 인수가 포함된 디스크 그룹으로 변환됩니다. 그런 다음 UNIX용 SnapDrive가 전체 디스크 그룹을 복구합니다. SnapDrive for UNIX는 해당 디스크 그룹의 호스트 볼륨에 있는 파일 시스템을 동결하고 해당 디스크 그룹에 LUN이 포함된 모든 스토리지 시스템 볼륨의 스냅샷 복사본을 만듭니다.
* NFS 마운트 지점인 파일 사양을 지정하는 경우 인수는 디렉토리 트리로 변환됩니다. UNIX용 SnapDrive는 NFS 디렉토리 트리 또는 파일만 복구합니다. 디렉토리 트리 내에서 SnapDrive for UNIX는 스냅샷 복사본을 생성한 후 생성한 새 NFS 파일 또는 디렉토리를 삭제합니다. 이렇게 하면 복원된 디렉토리 트리의 상태가 트리의 스냅샷 복사본이 생성된 상태와 동일하게 됩니다.
* LUN을 복구하는 경우 UNIX용 SnapDrive는 사용자가 지정한 LUN을 복구합니다.
* LUN에서 직접 생성된 파일 시스템을 복구하는 경우 UNIX용 SnapDrive는 LUN과 파일 시스템을 복구합니다.
* 스냅샷 복사본에 여러 스토리지 시스템 볼륨에 걸쳐 있는 스토리지 엔터티가 포함되어 있는 경우 해당 스냅샷 복사본의 모든 엔터티를 복원할 수 있습니다.




 a| 
LUN('-lun_file_spec_')
 a| 
_LUN의 이름입니다. 스토리지 시스템, 볼륨 및 LUN의 이름을 포함해야 합니다. _



 a| 
디스크 그룹('-dg_file_spec_c') 또는 볼륨 그룹('-vg_file_spec_')
 a| 
_ 디스크 또는 볼륨 그룹의 이름 _



 a| 
파일 시스템('-fs_file_spec_')
 a| 
_ 파일 시스템의 이름 _



 a| 
파일('-file_file_spec_')
 a| 
_NFS 파일의 이름 _



 a| 
호스트 볼륨('-hostvol_file_spec_') 또는 논리 볼륨('-lvol_file_spec_')
 a| 
호스트 또는 논리적 볼륨의 _이름입니다. 요청된 볼륨과 해당 볼륨이 포함된 디스크 그룹을 모두 제공해야 합니다(예: -hostvol dg3/acct_volume._)



 a| 
스냅샷 복사본의 이름을 지정합니다. 명령 프롬프트에서 현재 제공하는 '_FILE_SPEC_' 인수 중 로컬 호스트에 있는 인수가 있으면 간단한 형태의 스냅샷 복사본 이름을 사용할 수 있습니다.

호스트에 '_file_spec_' 인수가 없으면 스토리지 시스템 이름, 볼륨 및 스냅샷 복사본 이름을 입력하는 긴 형태의 스냅샷 복사본 이름을 사용해야 합니다. 스냅샷 복사본에 긴 이름을 사용하고 명령 프롬프트에서 경로 이름이 스토리지 시스템 및/또는 스토리지 볼륨 정보와 일치하지 않으면 SnapDrive for UNIX가 실패합니다. 다음은 긴 Snapshot 복제본 이름 "big_filer:/vol/account_vol:snap_20031115"의 예입니다

때때로 '_FILE_SPEC_' 인수에 제공된 값이 호스트에 없을 수 있습니다. 예를 들어 파일 시스템을 마운트 해제하거나 내보내기, 이식 또는 제거하여 디스크 그룹을 제거한 경우 해당 파일 시스템이나 디스크 그룹은 '_file_spec_' 인수의 값이 될 수 있습니다. 그러나 존재하지 않는 값으로 간주됩니다. SnapDrive for UNIX는 존재하지 않는 '_file_spec_'의 스냅샷 복제본을 복구할 수 있지만 긴 스냅샷 사본 이름을 사용해야 합니다.

여러 스토리지 시스템 및 볼륨에 걸쳐 있는 Snapshot 복제본을 복원하거나 존재하지 않는 '_file_spec_' 인수를 포함하는 경우 UNIX용 SnapDrive는 명령줄에서 비일관성을 허용합니다. 기존의 '_FILE_SPEC_' 인수는 허용하지 않습니다. 여러 스토리지 시스템의 스냅샷 복사본에서 스토리지 엔터티를 하나만 복구하려는 경우 지정한 스냅샷 복사본이 스토리지 엔터티가 포함된 스토리지 시스템과 동일한 스토리지 시스템에 있지 않아도 됩니다.

같은 스냅샷 복사본 이름의 짧은 형식은 스토리지 시스템과 스토리지 시스템 볼륨 이름을 생략하므로 '_SNAP_20031115_'로 표시됩니다



 a| 
스냅샷 사본 이름('-snapname')
 a| 
'_SNAP_NAME_'



 a| 
이름은 '_mysnap1_'과 같은 짧은 이름이거나 스토리지 시스템 이름, 볼륨 및 스냅샷 복사본 이름이 포함된 긴 이름일 수 있습니다.

일반적으로 짧은 이름을 사용하는 것이 좋습니다. '_FILE_SPEC_' 인수가 존재하지 않는 경우 즉, 호스트에 더 이상 존재하지 않는 것입니다. '_FILE_SPEC_' 인수의 설명을 참조하십시오. 그런 다음 스냅샷 복사본에 대해 긴 이름을 사용해야 합니다.



 a| 
'-reserve|-noreserve'입니다
 a| 



 a| 
선택 사항: 스냅샷 복사본을 복원할 때 UNIX용 SnapDrive에서 공간 예약을 생성하려는 경우



 a| 
``힘’’
 a| 
~



 a| 
``코프프롬프트’’
 a| 
~



 a| 
선택 사항: 기존 스냅샷 복사본을 덮어쓸지 결정합니다. 이 옵션이 없으면 기존 스냅샷 복사본의 이름을 제공하면 이 작업이 중지됩니다. 이 옵션을 제공하고 기존 스냅샷 복사본의 이름을 지정하면 스냅샷 복사본을 덮어쓸지 묻는 메시지가 표시됩니다. SnapDrive for UNIX에서 프롬프트를 표시하지 않으려면 '-nop프롬프트' 옵션도 포함합니다. (not프롬프트 옵션을 사용하려면 항상 '-force' 옵션을 포함해야 합니다.)

마지막 스냅샷 복사본 이후 구성이 변경된 디스크 그룹을 복원하려는 경우 명령 프롬프트에 '-force' 옵션을 포함해야 합니다. 예를 들어, 스냅샷 복사본을 생성한 이후에 디스크에 데이터가 스트라이핑되는 방식을 변경한 경우 '-force' 옵션을 포함해야 합니다. '-force' 옵션이 없으면 이 작업이 실패합니다. 이 옵션은 '-nop프롬프트' 옵션을 포함하지 않는 한 작업을 계속할 것인지 확인하는 메시지를 표시합니다.


NOTE: LUN을 추가하거나 삭제하면 '-force' 옵션을 포함하더라도 복원 작업이 실패합니다.



 a| 
문어
 a| 
~



 a| 
* 선택 사항: * 파일 시스템을 생성하는 경우 다음 옵션을 지정할 수 있습니다.

* 호스트 마운트 명령에 전달할 옵션(예: 호스트 시스템 로깅 동작 지정)을 지정하려면 `-mntopt'를 사용합니다. 지정하는 옵션은 호스트 파일 시스템 테이블 파일에 저장됩니다. 허용되는 옵션은 호스트 파일 시스템 유형에 따라 다릅니다.
* '_-mntopts_' 인수는 mount 명령 '-o' 플래그를 사용하여 지정하는 파일 시스템 '-type' 옵션입니다. '_-mntopts_' 인수에 -o 플래그를 포함하지 마십시오. 예를 들어, sequence-mntopt tmplog는 문자열 '-o tmplog'를 'mount' 명령으로 전달하고 텍스트를 새 명령줄에 삽입합니다.
+

NOTE: 스토리지 및 스냅 작업에 대해 잘못된 `_-mntopts_' 옵션을 전달하는 경우 UNIX용 SnapDrive는 이러한 잘못된 마운트 옵션의 유효성을 검사하지 않습니다.



|===