---
permalink: aix/task_installing_snapdrive_for_unix_on_an_aix_host.html 
sidebar: sidebar 
keywords: snap, snapdrive, install, aix, host, unix 
summary: '시스템 관리 인터페이스 도구 \(SMIT\)를 사용하여 AIX 호스트에 UNIX용 SnapDrive를 설치할 수 있습니다.' 
---
= AIX 호스트에 UNIX용 SnapDrive 설치
:icons: font
:imagesdir: ../media/


[role="lead"]
SMIT(시스템 관리 인터페이스 툴)를 사용하여 AIX 호스트에 UNIX용 SnapDrive를 설치할 수 있습니다.

루트 사용자로 로그인되어 있는지 확인해야 합니다.


IMPORTANT: UNIX용 SnapDrive가 설치된 디렉토리를 삭제하지 마십시오. 디렉토리를 삭제하면 데몬을 시작 및 중지하는 데 문제가 발생할 수 있습니다.

.단계
. NetApp Support 사이트에서 소프트웨어를 다운로드하십시오.
. 압축되지 않은 "NetApp.SnapDrive_AIX_5_2.z 파일"을 저장한 디렉토리로 이동합니다.
. 다음 명령을 실행하여 SMIT를 시작합니다.
+
'* SMIT*'

. 소프트웨어 설치 및 유지 관리 * 옵션을 선택합니다.
. 다음 화면에서 * 소프트웨어 설치 및 업데이트 * 메뉴 옵션을 선택합니다.
. 소프트웨어 설치 화면에서 다음 방법 중 하나로 소프트웨어의 위치를 지정합니다.
+
** 소프트웨어 위치의 경로를 수동으로 입력합니다.
** F4 키를 눌러 옵션 목록을 표시합니다.


+
F4 방법을 사용하려면 다음 단계를 수행하십시오.

+
.. F4 를 누릅니다.
.. 설치할 소프트웨어를 묻는 메시지가 나타나면 다음을 입력합니다.
+
``NetApp.SnapDrive *’’.

.. 계속할지 취소할지 묻는 메시지가 나타나면 Enter 키를 눌러 설치를 완료합니다.


. 'lslpp -l netapp.SnapDrive' 명령을 사용하여 소프트웨어 패키지 설치를 확인합니다.
. 시스템에 대해 SnapDrive for UNIX를 구성하여 설치를 완료합니다.
+
이 정보의 대부분은 기본적으로 설정되지만 다음 정보를 지정해야 합니다.

+
.. 스토리지 시스템의 로그인 정보입니다
.. AutoSupport 설정
.. FC 프로토콜을 사용하는지 또는 iSCSI 프로토콜을 사용하는지 여부에 따라 다음 옵션인 UNIX용 SnapDrive에 대한 올바른 구성 값을 설정합니다.
+
*** '기본 운송'
+
프로토콜에 따라 FCP 또는 iSCSI를 선택합니다.

*** 다중경로-유형
+
FC의 경우 다음 값 중 하나로 설정합니다.

+
**** 내기MPIO
**** dmp'입니다






+
iSCSI의 경우 이를 네이티브MPIO 또는 DMP로 설정합니다.


