---
permalink: aix/task_creating_an_lvm_a_vxvm_entity_and_settingup_the_lunautomatically.html 
sidebar: sidebar 
keywords: snap, snapdrive, lv, lun, create, automatically 
summary: 호스트에서 파일 시스템, 논리 볼륨 또는 디스크 그룹과 같은 엔터티를 생성하고 SnapDrive for UNIX가 연결된 LUN을 자동으로 생성하도록 할 수 있습니다. 
---
= LVM 엔티티를 생성하고 LUN을 자동으로 설정합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
호스트에서 파일 시스템, 논리 볼륨 또는 디스크 그룹과 같은 엔터티를 생성하고 SnapDrive for UNIX가 연결된 LUN을 자동으로 생성하도록 할 수 있습니다.

* 'host_lvm_fspec' 인수를 사용하면 파일 시스템, 논리 볼륨 또는 디스크 그룹을 생성할지 여부를 지정할 수 있습니다. 이 인수에는 세 가지 일반적인 형식이 있습니다. 사용할 형식은 만들려는 요소에 따라 다릅니다.
+
파일 시스템을 생성하려면 "-fs file_spec [-fstype] [-fsopts options] [-mntopts options] [-nopstist] [-npersist] [-hostvol file_spec] [-dG_name] 형식을 사용합니다

+
논리적 또는 호스트 볼륨을 생성하려면 다음 형식을 사용합니다.

+
'*[-hostvol file_spec]_file_spec_[-dg_dg_name_] *'

+
디스크 또는 볼륨 그룹을 생성하려면 다음 형식을 사용합니다.

+
'*-DG__DG_NAME___ *'

* 파일 시스템을 생성하는 경우 호스트 볼륨 사양, 디스크 그룹 사양 또는 두 사양을 모두 포함하여 파일 시스템이 상주하는 호스트 볼륨 및 디스크 그룹을 나타낼 수도 있습니다. 이러한 사양을 포함하지 않으면 SnapDrive for UNIX에서 자동으로 호스트 볼륨과 디스크 그룹 또는 둘 모두에 대한 이름을 생성합니다.
* 호스트 볼륨을 지정하면 SnapDrive for UNIX에서 연결된 호스트 볼륨을 생성합니다. 이 형식은 SnapDrive for UNIX가 호스트 볼륨을 생성할 때 지원하는 유일한 형식이지만 기존의 스트라이핑된 호스트 볼륨을 조작할 수 있습니다.


.단계
. 명령줄에 다음 명령을 입력합니다.
+
``SnapDrive storage create_host_vxVM_fspec_-filervol_long_filer_path_-dgsize[-igroup_IG_name[IG_name...]]_[{-reserve|-noreserve}] *

+
SnapDrive for UNIX는 사용자가 지정한 호스트 엔터티를 생성하고 지정한 스토리지 시스템에 LUN을 생성합니다. 각 LUN에 대해 호스트 준비 및 검색과 관련된 모든 작업을 수행할 뿐만 아니라 LUN을 호스트 엔티티에 매핑 및 연결합니다.


