---
permalink: aix/task_starting_the_volume_or_lun_clone_split_start.html 
sidebar: sidebar 
keywords: snap, snapdrive, start, volume, clone, lun, split 
summary: 볼륨 클론 또는 LUN 클론 분할 작업을 시작할 수 있습니다. 
---
= 볼륨 클론 또는 LUN 클론 분할 시작
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
볼륨 클론 또는 LUN 클론 분할 작업을 시작할 수 있습니다.

.단계
. 다음 명령을 입력하여 볼륨 클론 또는 LUN 클론 분할을 시작합니다.
+
"*#SnapDrive 클론 분할 시작[-lun]_long_lun_name_[_long_lun_name_...] | [{-DG|-vg|-fs|-hostvol|-lvol}_file_spec_[_file_spec_...]] [-force] [-nop프롬프트] [-dump|-dumpall] *

+
스토리지 상태가 사용 불가 로 표시될 때 다음 옵션을 사용할 수 있습니다.

+
** '-force' 옵션을 사용하면 클론 분할 작업을 강제로 시작하고 작업이 시작되었다는 확인 메시지를 받을 수 있습니다.
** 확인 메시지를 받지 않고 '-force' 옵션과 함께 '-nop프롬프트'를 사용하여 클론 분할 시작 작업을 시작할 수 있습니다.


+

NOTE: 진행 중인 클론 분할 작업을 중지한 직후에 다른 클론 분할 작업을 시작하면 작업이 실패할 수 있습니다. 이 문제는 스토리지 시스템이 중지 작업을 동기화할 수 있도록 클론 분할 작업의 시작과 중지 사이의 지연으로 충분하지 않은 경우에 발생할 수 있습니다.



다음 예에서는 볼륨 클론을 분할하는 방법을 표시합니다.

[listing]
----
# snapdrive clone split start -fs /mnt/my_mnt4_0 /mnt/my_mnt3_0
Resource    Container  Required Available Storage
                       Space(MB)Space(MB) Status
--------------------------------------------------
/mnt/my_mnt4_0 f3050-220 3295   66033 AVAILABLE
             -111:aggr0
/mnt/my_mnt3_0 f3050-220  293   37707 AVAILABLE
             -112:aggr1

Job ID: B265Dbv8gh
Clone-Split for "/mnt/my_mnt4_0" is started
Clone-Split for "/mnt/my_mnt3_0" is started
----
다음 예에서는 '_-force_' 옵션을 사용하여 클론을 분할하는 방법을 보여 줍니다.

[listing]
----
# snapdrive clone split start -fs /mnt/my_mnt5 /mnt/my_mnt6 -force
Resource    Container Required  Available Storage
                      Space(MB) Space(MB) Status
----------------------------------------------------
/mnt/my_mnt5 f3050-220 1198   20033   AVAILABLE
             -111:aggr0
/mnt/my_mnt6 f3050-220  3294  2196  NOT AVAILABLE
             -112:aggr1
Not enough space available for Clone-Split.  Do you want to continue (y/n)?y
Clone-Split for "/mnt/my_mnt5" is started
Clone-Split for "/mnt/my_mnt6" is started
----
다음 예에서는 '_-nop프롬프트_' 옵션을 사용하여 클론을 직접 시작하는 방법을 보여 줍니다. 즉, 확인 메시지가 없습니다.

[listing]
----
# snapdrive clone split start -fs /mnt/my_mnt5 /mnt/my_mnt6 -force -noprompt
Resource    Container  Required  Available Storage
                       Space(MB) Space(MB) Status
-----------------------------------------------------
/mnt/my_mnt5 f3050-220  1198     20033   AVAILABLE
             -111:aggr0
/mnt/my_mnt6 f3050-220  3294     2196  NOT AVAILABLE
             -112:aggr1
Clone-Split for "/mnt/my_mnt5" is started
Clone-Split for "/mnt/my_mnt6" is started
----