---
permalink: aix/task_displaying_asnapshot_copy.html 
sidebar: sidebar 
keywords: snap, snapdrive, display, snapshot, copy 
summary: SnapDrive snap show 또는 list 명령은 스냅샷 복사본이 생성되는 스토리지 시스템의 이름, 호스트 이름, 날짜 및 시간 등을 표시합니다. 
---
= 스냅샷 복사본 표시
:icons: font
:imagesdir: ../media/


[role="lead"]
"SnapDrive snap show" 또는 "list" 명령은 스냅샷 복사본이 생성되는 스토리지 시스템의 이름, 호스트 이름, 날짜 및 시간 등을 표시합니다.

.단계
. 스냅샷 복사본을 표시하려면 다음 명령 구문을 입력합니다.
+
``SnapDrive snap show[-snapname]_long_snap_name_[_snap_name_...] [-verbose] *



이 작업은 최소한 스냅샷 복사본에 대한 다음 정보를 표시합니다.

* 스냅샷 복사본이 생성되는 스토리지 시스템의 이름입니다
* 스냅샷 복사본을 생성한 호스트의 이름입니다
* 스토리지 시스템의 LUN에 대한 경로입니다
* 스냅샷 복사본이 생성된 날짜 및 시간입니다
* 스냅샷 복사본의 이름입니다
* 스냅샷 복사본에 포함된 디스크 그룹의 이름입니다


* 예 *: 'SnapDrive snap show' 명령의 예는 다음과 같습니다.

[listing]
----
# snapdrive snap show -snapname toaster:/vol/vol2:snapA snapX snapY

# snapdrive snap show -verbose toaster:/vol/vol2:snapA /vol/vol3:snapB snapC

# snapdrive snap show toaster:/vol/vol2:snapA

# snapdrive snap list -dg dg1 dg2
----
* 예 *: 이 예에서는 와일드카드를 사용하여 특정 볼륨에서 사용 가능한 스냅샷 복사본에 대한 정보를 표시합니다.

[listing]
----
# snapdrive snap show toaster:/vol/vol1:*
snap name host date
snapped
------------------------------------------------------------------
-------------
toaster:/vol/vol1:sss1 DBserver Mar 12
16:19 dg1
toaster:/vol/vol1:testdg DBserver Mar 12
15:35 dg1
toaster:/vol/vol1:t1 DBserver Mar 10
18:06 dg1
toaster:/vol/vol1:hp_1 HPserver Mar 8
19:01 vg01
toaster:/vol/vol1:r3 DBserver Mar 8
13:39 rdg1
toaster:/vol/vol1:r1 DBserver Mar 8
13:20 rdg1
toaster:/vol/vol1:snap2 DBserver Mar 8
11:51 rdg1toaster:/vol/vol1:snap_p1 DBserver
Mar 8 10:18 rdg1
----
* 예 *: 이 예에서 AIX 호스트의 명령줄에 '-verbose' 옵션이 사용됩니다.

[listing]
----
# snapdrive snap list betty:/vol/vol1:testsnap -v
snap name host date
snapped
------------------------------------------------------------------
-------------
betty:/vol/vol1:testsnap aix198-75 Jul 31
10:43 test1_SdDg
host OS: AIX 3 5
snapshot name: testsnap
Volume Manager: aixlvm 5.3
disk group: test1_SdDg
host volume: test1_SdHv
file system: test1_SdHv file system type: jfs2
mountpoint:
/mnt/test1
lun path dev paths
-------------------------------------------------------
betty:/vol/vol1/aix198-75_luntest1_SdLun /dev/hdisk32
----
* 예 *: 이 예제에는 UNIX용 SnapDrive로 생성되지 않은 AIX 호스트의 스냅샷 복사본에 대한 메시지가 포함되어 있습니다.

[listing]
----
# snapdrive snap show -filer toaster
snap name host date
snapped
------------------------------------------------------------------
-------------
toaster:/vol/vol1:hourly.0 non-snapdrive snapshot
toaster:/vol/vol1:hourly.0 non-snapdrive snapshot
toaster:/vol/vol1:snap1 DBserver1 Oct 01 13:42 dg1
dg2
toaster:/vol/vol1:snap2 DBserver2 Oct 10 13:40
DBdg/hvol1
toaster:/vol/vol1:snap3 DBserver3 Oct 31 13:45
DBdg
----
이 예에서는 'SnapDrive snap show' 명령과 '-verbose' 옵션을 사용하여 AIX 호스트에서 LVM 기반 파일 시스템의 스냅샷 복제본을 표시합니다.

[listing]
----
# snapdrive snap show -v -fs /mnt/check_submit/csdg2/hv3_0
snapname host date snapped
------------------------------------------------------------------
-------------
toaster:/vol/vol1:mysnapshot sales-aix Aug 24 10:55 csdg2
host OS: AIX 1 5
snapshot name: mysnapshot
Volume Manager: aixlvm 5.1
disk group: csdg2
host volume: csdg2_log
host volume: csdg2_hv3_0
file system: csdg2_hv3_0 file system type: jfs2 mountpoint:
/mnt/check_submit/csdg2/hv3_0
lun path dev paths
-------------------------------------------------------
spinel:/vol/vol1/check_submit_aix-4 /dev/hdisk4
----
* 예 *: 다음 예에서는 와일드카드를 사용합니다.

[listing]
----
# snapdrive snap show toaster:/vol/volX:*
# snapdrive snap show -v toaster:/vol/volX:DB1*
filer1:/vol/volY:DB2*
# snapdrive snap show toaster:/vol/vol2:mysnap* /vol/vol2:yoursnap*
hersnap*
# snapdrive snap show toaster:/vol/volX:*
----
* 예제 *: 이 예제에서는 와일드카드를 사용할 수 없습니다. 와일드카드가 끝 부분에 배치되지 않고 이름 중간에 있기 때문입니다.

[listing]
----
# snap show toaster:/vol/vol1:my*snap
----