---
permalink: aix/task_estimating_the_storage_space_to_split_a_volume_clone.html 
sidebar: sidebar 
keywords: snap, snapdrive, split, volume, clone 
summary: '클론 분할 추정치를 사용하면 볼륨 클론을 분할하는 데 필요한 스토리지 공간(MB\)을 추정할 수 있습니다. SnapDrive for UNIX에서 제공하는 클론 분할 예측에 따라 볼륨 클론을 분할할 공간 가용성을 결정할 수 있습니다.' 
---
= 볼륨 클론을 분할할 스토리지 공간 추정
:icons: font
:imagesdir: ../media/


[role="lead"]
클론 분할 추정치를 사용하면 볼륨 클론을 분할하는 데 필요한 스토리지 공간(MB)을 추정할 수 있습니다. SnapDrive for UNIX에서 제공하는 클론 분할 예측에 따라 볼륨 클론을 분할할 공간 가용성을 결정할 수 있습니다.

.단계
. 다음 명령을 입력하여 볼륨 클론을 분할하는 데 필요한 스토리지 공간을 예측합니다.
+
(* SnapDrive 클론 분할 예상 [-LUN]_Long_LUN_name_[long___lun_name__...] | [{-DG|-vg|-fs|-hostvol|-lvol}_file_spec_[_file_spec_...]] [-snapname_long_snap_name_] {-volclone|-lunclone}] [-v|-verbose] [-dump|-dumpall] *

+
이 작업은 다음 정보를 표시합니다.

+
** 리소스 이름입니다
** 컨테이너 - FlexClone에 대한 집계입니다
** Required Space - 볼륨 클론을 분할하는 데 필요한 공간입니다
** 사용 가능한 공간 - 컨테이너에서 사용 가능한 공간입니다
** Storage Status - 볼륨 클론 분할에 사용할 수 있는 공간을 나타냅니다
** Owned Space - 볼륨 클론이 차지하는 공간입니다
** 공유 공간 - 볼륨 클론이 상위 항목과 함께 차지하는 공간입니다


+
'-verbose' 옵션을 사용하면 소유공간과 공유 공간이 표시됩니다.



다음 예에서는 볼륨 클론을 분할할 스토리지 공간을 예측합니다.

[listing]
----
# snapdrive clone split estimate -fs /mnt/my_mnt1 -fs /mnt/my_mnt2
Resource     Container  Required Available  Storage
                        Space(MB) Space(MB) Status
/mnt/my_mnt1  f3050-220  400      61500    AVAILABLE
              -111:aggr0
/mnt/my_mnt2  f3050-220  3292     1129     NOT AVAILABLE
              -112:aggr1
----
모든 파일 사양에 대해 SnapDrive for UNIX는 볼륨 클론을 분할하기 위해 스토리지 시스템에서 사용할 수 있는 필수 공간을 결정합니다. 여기서, '/mnt/my_mnt1' 파일 사양은 분할하는 데 필요한 공간이 있으므로 저장소 상태가 사용 가능으로 표시됩니다. 반면, '/mnt/my_mnt2' 파일 사양에는 분할할 공간이 없으므로 저장소 상태가 사용 불가 로 표시됩니다.

다음은 '-verbose' 옵션을 사용하는 예입니다. 또는 '-v' 옵션을 사용할 수도 있습니다.

[listing]
----
# snapdrive clone split estimate -fs /mnt/my_mnt1 -verbose
Resource    Container Owned    Shared   Required Available Storage
                      Space(MB)Space(MB)Space(MB)Space(MB) Status
/mnt/my_mnt1 f3050-220 32365  403      403     55875 AVAILABLE
             -111:aggr0
----