---
permalink: aix/task_verifying_the_status_of_clone_split.html 
sidebar: sidebar 
keywords: snap, snapdrive, view, status, volume, lun, clone, split 
summary: 작업 ID 또는 파일 사양을 사용하여 클론 분할 상태를 쿼리할 수 있습니다. UNIX용 SnapDrive는 클론 분할의 현재 상태를 진행 중, 실패 또는 완료로 나타냅니다. 
---
= 볼륨 클론 또는 LUN 클론 분할 상태 보기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
작업 ID 또는 파일 사양을 사용하여 클론 분할 상태를 쿼리할 수 있습니다. UNIX용 SnapDrive는 클론 분할의 현재 상태를 진행 중, 실패 또는 완료로 나타냅니다.

.단계
. 작업 ID 또는 파일 사양을 사용하여 클론 분할 상태를 쿼리하려면 다음 명령을 입력합니다.
+
``SnapDrive 클론 분할 상태[-LUN]_long_lun_name_[_long_lun_name_...] [{-dg|-vg|-fs|-hostvol|-lvol}_file_spec_[_file_spec_...] [-job_<jobid>_] [-all] *



다음 예에서는 작업 ID를 사용하여 클론 분할 상태를 보여 줍니다.

[listing]
----
# snapdrive clone split status -job SVE2oxKXzH
Clone-Split-Status for /fs1-1_3 is 1% Complete
Clone-Split-Status for /fs1_0 is 73% Complete
Clone-Split-Status for /fs1_1 is 73% Complete
Clone-Split-Status for /fs1_2 is 74% Complete
Clone-Split-Status for /fs1_3 is 1% Complete
----
[NOTE]
====
다음 방법 중 하나를 사용하여 클론 분할 진행 상태를 확인할 수 있습니다.

* 를 사용하여 클론을 확인할 수 있습니다
+
'* SnapDrive storage show -fs /mnt/my_mnt * '

+
또는

+
' * SnapDrive storage show -lun_long_lun_pathname_ * '

+
명령. 두 경우 모두 클론 유형은 분할이 완료되지 않은 경우 FlexClone 또는 LUN 클론으로 표시됩니다.

* 스토리지 시스템에 로그인하고 스토리지 시스템 CLI에서 다음 명령을 사용하여 클론 분할 진행 상태를 확인할 수 있습니다.
+
'* vol clone split status_vol_name_ * '" * lun clone split status_lun_name_ * '



====
다음 예에서는 파일 사양을 사용하여 생성된 클론 분할 상태 쿼리를 보여 줍니다.

[listing]
----
# snapdrive clone split status -fs /mnt/my_mnt3 -fs /mnt/my_mnt4
Clone-Split-Status for /mnt/my_mnt3 is 14% Complete
Clone-Split-Status for /mnt/my_mnt4 is 17% Complete
----
다음 예제에서는 실행 중인 클론 분할 상태 쿼리를 보여 줍니다.

[listing]
----
# snapdrive clone split status -all
Job ID: SVE2oxKXzH:
Clone-Split-Status for /fs1-1_3 is 100% Complete
Clone-Split-Status for /fs1_0 is 100% Complete
Clone-Split-Status for /fs1_1 is 100% Complete
Clone-Split-Status for /fs1_2 is 100% Complete
Clone-Split-Status for /fs1_3 is 100% Complete
----
* 작업 세트에서 작업이 제거되고 파일 사양을 사용하여 클론 분할 상태의 상태를 쿼리하면 SnapDrive for UNIX에서 오류 메시지가 로 표시됩니다
+
현재 해당 자원에 대해 진행 중인 분할이 없습니다

* 작업 세트에서 작업이 제거되고 작업 ID를 사용하여 클론 분할의 상태를 쿼리하면 SnapDrive for UNIX에서 오류 메시지가 로 표시됩니다
+
작업 ID가 유효하지 않습니다

* 작업에서 모든 파일 사양이 제거되고 작업 ID를 사용하여 클론 분할 상태를 쿼리하면 UNIX용 SnapDrive가 로 표시됩니다
+
작업 ID가 유효하지 않습니다

+
작업이 작업 세트에서 제거되었기 때문입니다.

* 스토리지 시스템의 공간 부족으로 인해 파일 사양이 실패하면 나머지 파일 사양에 대해 작업이 계속 분할됩니다. 즉, 작업이 작업 대기열에서 삭제되지 않고 전체 작업 결과를 조회할 때까지 작업 상태가 유지됩니다.

