---
permalink: solaris/concept_guidelines_for_restoring_a_snapshot_copy_in_a_host_cluster_environment.html 
sidebar: sidebar 
keywords: snap, snapdrive, snapshot, copy, host, restore 
summary: 스냅샷 복사본을 복원하는 동안 지침을 따릅니다. 
---
= 호스트 클러스터 환경에서 스냅샷 복사본을 복원하기 위한 지침
:icons: font
:imagesdir: ../media/


[role="lead"]
스냅샷 복사본을 복원하는 동안 지침을 따릅니다.

* "SnapDrive snapshot restore" 명령은 호스트 클러스터의 모든 노드에서 실행할 수 있습니다.
* 파일 시스템 또는 디스크 그룹은 활성 상태인 경우 호스트 클러스터의 모든 노드에서 공유해야 합니다.
* LUN 중 하나가 호스트 클러스터 외부의 노드에 매핑된 경우 공유 파일 시스템 또는 디스크 그룹의 스냅샷 복원 작업이 실패합니다. 공유 LUN 중 호스트 클러스터 외부의 노드에 매핑된 LUN이 없는지 확인합니다.
* 스냅샷 생성 작업은 전용 파일 시스템 또는 디스크 그룹에서 수행할 수 있지만 스냅샷 복사본을 공유 모드로 복원하려면 파일 시스템 또는 디스크 그룹이 호스트 클러스터의 특정 노드에 있는 전용 모드에 있지 않아야 합니다. 그렇지 않으면 UNIX용 SnapDrive에서 오류가 발생합니다.
* 파일 시스템 또는 디스크 그룹이 호스트 클러스터에 없는 경우 SnapDrive for UNIX는 스냅샷 복사본에서 LUN을 생성하고 이를 호스트 클러스터의 모든 노드에 매핑하며 디스크 그룹 및 파일 시스템을 활성화합니다. 호스트 클러스터의 모든 노드에 LUN을 매핑한 후 Veritas 클러스터 볼륨 관리자는 호스트 클러스터의 모든 노드 간에 LUN 정보를 새로 고칩니다. 클러스터 노드의 CVM 인스턴스 간에 LUN 정보가 새로 고쳐지기 전에 디스크 그룹 활성화를 시도하면 스냅샷 복원 작업이 실패할 수 있습니다. CVM 새로 고침의 경우 SnapDrive snap restore 명령을 재발급해야 합니다.
* 호스트 클러스터 외부의 노드에서 생성된 스냅샷 복사본은 다음 조건에 해당하는 경우에만 클러스터에서 복원 및 공유할 수 있습니다.
+
** 파일 시스템 또는 디스크 그룹이 호스트 클러스터의 특정 노드에 있는 전용 모드에 없습니다.
** LUN은 호스트 클러스터 외부의 노드에 표시되지 않습니다.


* 하나의 스냅샷 복원 작업에서 공유 및 전용 시스템의 스냅샷 복사본을 복원할 수 없습니다.
* 공유 디스크 그룹이나 파일 시스템에 지정된 '-DeviceType' 전용 옵션 또는 '-DeviceType' 옵션이 없는 상태에서 'SnapDrive snap restore' 명령을 실행하면 여러 노드에 연결된 LUN이 복원된다는 알림이 SnapDrive for UNIX에 표시됩니다.
* 스냅샷 복사본 생성 및 스냅샷 복사본 복원 간에 디스크 그룹 구성이 변경되면 SnapDrive for UNIX에서 구성이 변경되었음을 알려 줍니다.

