---
permalink: solaris/concept_informationrequired_forusing_the_snapdrive_storageconnect_command.html 
sidebar: sidebar 
keywords: snap, snapdrive, storage, connect, command 
summary: SnapDrive storage connect 명령을 사용할 때 제공해야 할 몇 가지 정보가 있습니다. 이 정보는 명령을 올바르게 사용하는 데 도움이 됩니다. 
---
= SnapDrive storage connect 명령을 사용하는 데 필요한 정보입니다
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapDrive storage connect 명령을 사용할 때 제공해야 할 정보가 몇 가지 있습니다. 이 정보는 명령을 올바르게 사용하는 데 도움이 됩니다.

|===
| 요구 사항 | 인수 


 a| 
LUN, LUN에 직접 생성된 파일 시스템 또는 호스트에 연결할 LVM 엔티티를 지정합니다.

* 하나 이상의 LUN을 연결하는 경우 첫 번째 인수는 긴 형식의 LUN 이름을 사용해야 합니다. 이 이름은 스토리지 시스템 이름, 볼륨 이름 및 볼륨 내의 LUN 이름을 지정합니다.
+
새 LUN이 이전 LUN과 동일한 스토리지 시스템 및 볼륨에 있는 경우 추가 LUN을 지정하려면 LUN 이름만 사용할 수 있습니다. 그렇지 않으면 새 스토리지 시스템 이름과 볼륨 이름(또는 볼륨 이름)을 지정하여 이전 값을 바꿀 수 있습니다.

* LUN에 직접 생성된 파일 시스템을 연결하는 경우 긴 형식의 LUN 이름과 함께 '-nolvm' 옵션을 포함해야 합니다.
* LUN을 디스크 그룹, 호스트 볼륨 및 파일 시스템에 연결하는 경우 '-fs' 및 '-hostvol' 옵션을 사용하여 파일 시스템 및 호스트 볼륨을 지정해야 합니다. 호스트 볼륨에는 디스크 그룹의 이름이 포함되어야 합니다.




 a| 
LUN('-lun')
 a| 
'_long_lun_name _'



 a| 
'-lun' 옵션과 함께 제공하는 첫 번째 값에는 스토리지 시스템 이름, 볼륨 및 LUN 이름이 포함되어야 합니다. 동일한 볼륨에 여러 LUN을 접속하려면 첫 번째 경로 이름에 전체 정보를 입력한 후 "-lun" 옵션에 상대 경로 이름을 사용할 수 있습니다. UNIX용 SnapDrive에서 상대 경로 이름이 발견되면 이전 LUN과 동일한 볼륨에서 LUN을 찾습니다. 같은 볼륨에 있지 않은 추가 LUN을 연결하려면 각 LUN의 전체 경로 이름을 입력합니다.



 a| 
추가 LUN
 a| 
'_LUN_name_'(긴 형태 또는 짧은 형태)



 a| 
'-fs'에 지정된 '_file_spec_'은 LUN에 직접 생성된 파일 시스템을 접속할 때 파일 시스템 마운트 지점의 이름입니다.



 a| 
파일 시스템('-fs file-spec')
 a| 
'_filesystem_name_'



 a| 
호스트 LVM을 활성화하지 않고 LUN에 생성된 파일 시스템을 연결하는 데 사용됩니다.



 a| 
'-놀람'
 a| 



 a| 
호스트 볼륨에서 파일 시스템을 연결하려면 다음을 따르십시오.

새 호스트에 연결할 LVM 파일 시스템, 디스크 그룹 및 호스트 볼륨을 식별하는 '-fs_file_spec_' 및 '-hostvol file_spec'을 제공합니다.

접속하는 스토리지 계층에는 디스크 그룹, 호스트 볼륨 및 파일 시스템이 포함되어야 합니다. '-fs'와 '-hostvol'의 값을 지정해야 합니다. '-hostvol' 값에는 디스크 그룹의 이름이 포함되어야 합니다.



 a| 
호스트 볼륨('-hostvol file-spec')
 a| 
'_DISK_GROUP_NAME_' 및 '_HOST_VOLUME_NAME_'



 a| 
선택 사항: 호스트 파일 시스템 테이블에 항목을 만들지 않고 스토리지를 새 위치에 연결하려면 '-nopist' 옵션을 사용합니다. 기본적으로 storage connect 명령은 영구 마운트를 생성합니다. 즉, Solaris 호스트에서 LVM 스토리지 엔터티를 생성하면 SnapDrive for UNIX가 스토리지를 자동으로 생성하고 파일 시스템을 마운트한 다음 파일 시스템에 대한 항목을 호스트 파일 시스템 테이블에 배치합니다.



 a| 
노persist
 a| 
~



 a| 
* 선택 사항: * igroup 이름을 제공하는 대신 호스트에서 기본 igroup을 사용하는 것이 좋습니다.



 a| 
iGroup 이름('-igroup')
 a| 
'_IG_NAME_'



 a| 
'_-DeviceType_'
 a| 
~



 a| 
UNIX용 SnapDrive 작업에 사용할 디바이스 유형을 지정합니다. LUN, 디스크 그룹 및 파일 시스템의 범위를 호스트 클러스터 전체에 지정하는 "공유" 또는 LUN, 디스크 그룹 및 파일 시스템의 범위를 로컬 시스템으로 지정하는 "디디디디케이티드"일 수 있습니다.



 a| 
'-fstype'입니다
 a| 
'_type_'



 a| 
'vmtype'입니다
 a| 
'_type_'



 a| 
*선택 사항:* UNIX용 SnapDrive 작업에 사용할 파일 시스템 및 볼륨 관리자의 유형을 지정합니다.



 a| 
``문어’
 a| 
~



 a| 
* 선택 사항: * 파일 시스템을 생성하는 경우 다음 옵션을 지정할 수 있습니다.

* 호스트 마운트 명령에 전달할 옵션(예: 호스트 시스템 로깅 동작 지정)을 지정하려면 `-mntopt'를 사용합니다. 지정하는 옵션은 호스트 파일 시스템 테이블 파일에 저장됩니다. 허용되는 옵션은 호스트 파일 시스템 유형에 따라 다릅니다.
* '_-mntopt_' 인수는 mount 명령 '-o' 플래그를 사용하여 지정하는 파일 시스템 '-type' 옵션입니다. '-mnttops' 논쟁에 '-o' 플래그를 포함하지 마십시오. 예를 들어, sequence-mntopt tmplog는 문자열 '-o tmplog'를 'mount' 명령으로 전달하고 텍스트를 새 명령줄에 삽입합니다.
+

NOTE: 스토리지 및 스냅 작업에 대해 유효하지 않은 '-mntopts' 옵션을 전달하는 경우 UNIX용 SnapDrive는 이러한 잘못된 마운트 옵션의 유효성을 검사하지 않습니다.



|===