---
permalink: solaris/concept_guidelines_for_storage_create_operation_in_a_host_cluster_environment.html 
sidebar: sidebar 
keywords: snap, snapshot, storage, create, host cluster 
summary: 호스트 클러스터 환경에서 스토리지를 생성할 때는 특정 지침을 따라야 합니다. 
---
= 호스트 클러스터 환경에서 스토리지 생성 작업에 대한 지침
:icons: font
:imagesdir: ../media/


[role="lead"]
호스트 클러스터 환경에서 스토리지를 생성할 때는 특정 지침을 따라야 합니다.

* 호스트 클러스터의 모든 노드에서 'SnapDrive storage create' 명령을 실행할 수 있습니다.
* 스토리지 생성 작업이 성공하려면 다음 중 어느 것도 사실이 아니어야 합니다.
+
** 스토리지 엔터티가 호스트 클러스터의 노드에 있어서는 안 됩니다.
** LUN을 호스트 클러스터의 노드에 매핑하면 안 됩니다.


* '-DeviceType' 전용 또는 '-DeviceType shared' 옵션을 사용하여 특정 노드에 스토리지 엔터티를 생성할 수 있습니다. 전용 모드에 있는 스토리지 엔터티를 생성하는 경우 기본값은 'dedicated'이므로 '-DeviceType' 옵션을 생략할 수 있습니다.
* 파일 시스템의 호스트 클러스터 전체 스토리지 생성은 VxFS(Veritas 파일 시스템)와 함께 Veritas 볼륨 관리자를 사용하는 디스크 그룹에서 지원됩니다. 이 작업은 원시 LUN에서 지원되지 않으며 "-nolvm" 옵션도 지원하지 않습니다.
* 스토리지 생성 작업에서 '-igroup' 옵션이 지원되지 않습니다.
* 다음 상황 중 하나가 발생하면 스토리지 생성 작업이 실패합니다.
+
** 스토리지 엔터티를 생성하는 동안 오류 메시지가 발생하는 경우 SnapDrive for UNIX는 호스트 클러스터의 마스터 노드에서 스토리지 생성 작업을 실행합니다. 공유 스토리지 엔터티를 생성하기 전에 SnapDrive for UNIX는 LUN을 생성하고, LUN을 마스터 노드에 매핑한 다음, LUN을 모든 비마스터 노드에 매핑합니다. SnapDrive for UNIX는 내부적으로 모든 노드의 igroup을 생성하고 관리합니다.
** 호스트 클러스터 볼륨 관리자(CVM)를 시작하기 전에 호스트 클러스터의 노드가 종료되고 재부팅되면 LUN에서 사용하는 공유 디스크 그룹이 노드에서 검색되어야 합니다. 기본적으로 LUN은 FC 포트 주소가 변경되지 않으면 표시되며, 그렇지 않으면 "SnapDrive storage connect" 명령을 사용하여 LUN을 매핑해야 합니다.



