---
permalink: solaris/concept_host_filespec_information_for_a_particular_volume.html 
sidebar: sidebar 
keywords: snap, snapdrive, host, filespec, volume 
summary: 볼륨 복원 미리 보기 보고서의 일부로 UNIX용 SnapDrive에 LUN 매핑 정보가 표시됩니다. 이 표시된 정보는 점검과 관련이 있으며 일반 파일은 되돌려집니다. 특정 볼륨의 LUN을 기반으로 하는 모든 호스트 파일을 찾는 것은 시간이 오래 걸리고 볼륨 복원 프로세스의 속도가 느려집니다. 
---
= 특정 볼륨에 대한 호스트 파일 지정 정보입니다
:icons: font
:imagesdir: ../media/


[role="lead"]
볼륨 복원 미리 보기 보고서의 일부로 UNIX용 SnapDrive에 LUN 매핑 정보가 표시됩니다. 이 표시된 정보는 점검과 관련이 있으며 일반 파일은 되돌려집니다. 특정 볼륨의 LUN을 기반으로 하는 모든 호스트 파일을 찾는 것은 시간이 오래 걸리고 볼륨 복원 프로세스의 속도가 느려집니다.

특정 스토리지 시스템 볼륨에 매핑된 로컬 호스트에 대한 호스트 파일 지정 정보를 알고 싶은 경우 'SnapDrive storage show-filervol<full-volume-name>'을 사용할 수 있습니다. 예를 들면 다음과 같습니다.

[listing]
----
#snapdrive storage show -filervol bart:/vol/volusecase2

Connected LUNs and devices:

 device filename        adapter path    size    proto   state   clone   lun path           backing snapshot
----------------        ------- ----    ----    -----   -----   -----   --------                        ----------------
/dev/sdg                  -     P       100m    iscsi   online   No     bart:/vol/volusecase2/lun5          -

Host devices and file systems:

dg: vbsrfs_1_SdDg               dgtype lvm
hostvol: /dev/mapper/vbsrfs_1_SdDg-vbsrfs_1_SdHv        state: AVAIL
fs: /dev/mapper/vbsrfs_1_SdDg-vbsrfs_1_SdHv     mount point: /mnt/vbsrfs_1 (persistent) fstype ufs

 device filename     adapter path    size    proto   state   clone   lun path           backing snapshot
----------------        ------- ----    ----    -----   -----   -----   --------                        ----------------
/dev/sdbe                 -     P       100m    iscsi   online   No     bart:/vol/volusecase1/lun9_0        -
/dev/sdbf                 -     P       100m    iscsi   online   No     bart:/vol/volusecase2/lun4_0        -

raw device: /dev/sdbr1  mount point: /mnt/fs11 (persistent) fstype ufs

 device filename     adapter path    size    proto   state   clone   lun path           backing snapshot
----------------        ------- ----    ----    -----   -----   -----   --------                        ----------------
/dev/sdbr                 -     P       200m    iscsi   online   No     bart:/vol/volusecase2/fs11_SdLun    -

NFS device: bart:/vol/volusecase1        mount point: /mnt/volusecase1 (non-persistent)

LUNs not connected to this host:

 lun path                                           size   state
 -----------------------------               ------ ------
 bart:/vol/volusecase2/lunotherhost 20m   online
----