---
permalink: solaris/concept_guidelines_for_connecting_snapshot_copies_in_a_host_cluster_environment.html 
sidebar: sidebar 
keywords: snap, snapdrive, guideline, connect, copy, host, cluster, snapshot 
summary: 호스트 클러스터의 모든 노드에서 스냅샷 복사본을 연결할 수 있습니다. 스냅샷 복사본에 연결하는 동안 지침에 따릅니다. 
---
= 호스트 클러스터 환경에서 스냅샷 복사본 연결 지침
:icons: font
:imagesdir: ../media/


[role="lead"]
호스트 클러스터의 모든 노드에서 스냅샷 복사본을 연결할 수 있습니다. 스냅샷 복사본에 연결하는 동안 지침에 따릅니다.

* SnapDrive snapshot connect 명령은 호스트 클러스터의 모든 노드에서 실행할 수 있다. 호스트 클러스터의 비마스터 노드에서 '-DeviceType shared' 옵션으로 'SnapDrive snap connect' 명령을 실행하면 해당 명령이 마스터 노드로 전송되어 실행됩니다. 이렇게 하려면 모든 호스트 클러스터 노드에서 'rsh' 또는 'sh' 액세스(암호 없음) 프롬프트가 허용되는지 확인하십시오.
* 이 작업에 지정된 여러 파일 시스템 및 디스크 그룹은 동일한 디바이스 유형 범위를 가져야 합니다. 즉, 모두 공유되거나 모두 전용이어야 합니다.
* SnapDrive snap connect 명령을 NFS 또는 원시 LUN의 스토리지 엔터티와 함께 사용하는 것은 지원되지 않습니다.
* '-igroup' 옵션은 '-DeviceType' 전용 옵션과 함께 지원되며 'SnapDrive snap connect' 명령의 '-DeviceType' 공유 옵션은 지원하지 않습니다.
* SnapDrive for UNIX는 마스터 노드에서 'SnapDrive snap connect' 명령을 실행합니다. 공유 스토리지 엔터티를 생성하기 전에 마스터 노드에서 LUN을 생성하고 매핑한 다음 마스터가 아닌 모든 노드에 LUN을 매핑합니다. 또한 호스트 클러스터의 모든 노드에 대한 igroup을 생성하고 관리합니다. 이 시퀀스 중에 오류 메시지가 발생하면 스냅샷 연결 작업이 실패합니다.
* 'SnapDrive snap connect' 명령을 사용하여 다음 스토리지 요소를 연결할 수 있습니다.
+
** 호스트 클러스터의 공유 또는 전용 모드에 이미 있는 공유 파일 시스템 또는 디스크 그룹입니다.
** 파일 시스템 또는 디스크 그룹이 호스트 클러스터의 공유 모드에 이미 있는 경우에도 호스트 클러스터의 단일 노드에 대한 전용 파일 시스템 또는 디스크 그룹입니다.
** 호스트 클러스터 외부의 노드에서 생성되는 파일 시스템 또는 디스크 그룹의 스냅샷 복사본입니다.


* 비마스터 노드에 이미 있는 전용 파일 시스템 또는 디스크 그룹은 디스크 그룹의 '-destdg' 옵션과 파일 시스템의 '-autorename' 옵션이 없으면 호스트 클러스터의 공유 모드에서 다시 연결할 수 없습니다.


즉, 호스트 클러스터의 비마스터 노드 중 하나에서 파일 시스템이 이미 전용 모드에 있는 경우 -destdg와 -autorename 옵션을 사용하여 SnapDrive snap connect 명령을 지정하거나 명령에서 대상 파일 시스템을 명시적으로 지정해야 합니다.
