---
permalink: solaris/concept_error_message_format.html 
sidebar: sidebar 
keywords: snap, snapdrive, error, message 
summary: 오류 메시지의 형식은 오류의 원인을 확인하는 데 도움이 됩니다. 
---
= 오류 메시지 형식
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
오류 메시지의 형식은 오류의 원인을 확인하는 데 도움이 됩니다.

UNIX용 SnapDrive는 표준 오류 코드 정보를 반환하며, 이 정보는 초기 오류 조건의 원인에 대한 보다 구체적인 설명을 제공합니다. UNIX용 SnapDrive 오류 메시지는 다음 형식을 따릅니다.

코드 메시지-ID 오류 형식: 메시지 텍스트

* '_return code_' -- 오류 조건의 기본 원인을 나타내는 종료 상태 값에 연결된 UNIX용 SnapDrive 오류 메시지 ID입니다.
* '_message-ID_' -- NetApp 기술 지원에서 오류를 생성한 특정 코드를 찾는 데 사용하는 고유 식별자입니다. NetApp 기술 지원 부서에 전화해야 하는 경우 오류 메시지와 함께 메시지 ID를 기록하는 것이 좋습니다.
* '_error type_' -- UNIX용 SnapDrive에서 발견되는 오류 유형을 지정합니다. 반환 값은 다음과 같습니다.
+
** '_Warning_' -- SnapDrive for UNIX는 명령을 실행했지만 주의가 필요할 수 있는 조건에 대한 경고를 발행했습니다.
** 명령줄의 오류로 인해 UNIX용 SnapDrive가 명령을 실행하지 못했습니다. 명령줄 형식과 변수가 올바른지 확인합니다.
** '_Admin_' -- 시스템 구성의 비호환성 때문에 UNIX용 SnapDrive가 명령을 실행하지 못했습니다. 구성 매개 변수를 검토하려면 시스템 관리자에게 문의하십시오.
** '_Fatal_' -- UNIX용 SnapDrive가 예기치 않은 조건으로 인해 명령을 실행하지 못했습니다. 치명적인 오류는 거의 발생하지 않습니다. 치명적인 오류가 발생하여 이를 해결하는 데 문제가 있는 경우 NetApp 기술 지원 팀에 지원을 요청하십시오.


* '_message text_' -- 오류를 설명하는 정보입니다. 이 텍스트에는 오류에 대한 자세한 정보를 제공하는 다른 구성 요소의 정보가 포함될 수 있습니다. 예를 들어, 디스크 그룹과 같은 명령줄 인수가 누락된 경우 오류 메시지가 누락된 항목을 알려 줍니다. 또는 SnapDrive for UNIX에서 스토리지 시스템을 제어하는 데 사용하는 ONTAP API 관리 에서 오류를 설명하는 데 도움이 되는 추가 텍스트를 제공할 수 있습니다. 이 경우 텍스트는 UNIX용 기본 SnapDrive 오류 메시지에 따릅니다.

