---
permalink: solaris/concept_guidelines_for_disconnecting_snapshot_copies_in_a_host_clusterenvironment.html 
sidebar: sidebar 
keywords: snap, snapdrive, disconnect, snapshot, copy, host, cluster 
summary: NFS 엔티티의 스냅샷 복사본을 분리하는 동안 SnapDrive for UNIX는 파일 시스템을 마운트 해제하고, 파일 시스템에서 마운트 항목을 제거하고, 마운트 지점을 제거하는 등의 기능을 수행합니다. 
---
= 호스트 클러스터 환경에서 스냅샷 복사본의 연결을 끊는 방법을 설명합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
NFS 엔티티의 스냅샷 복사본을 분리하는 동안 SnapDrive for UNIX는 파일 시스템을 마운트 해제하고, 파일 시스템에서 마운트 항목을 제거하고, 마운트 지점을 제거하는 등의 기능을 수행합니다.

* SnapDrive snap disconnect 명령은 호스트 클러스터의 모든 노드에서 실행할 수 있다.
* 스냅샷 연결 해제 작업이 성공하려면 다음 중 하나가 참이어야 합니다.
+
** 스토리지 엔터티는 호스트 클러스터의 모든 노드에서 공유해야 합니다.
** LUN은 호스트 클러스터의 모든 노드에 매핑되어야 합니다.


* '-DeviceType Dedicated' 또는 'Shared' 옵션을 사용하여 특정 노드에서 스토리지 엔터티의 연결을 끊을 수 있습니다. 전용 모드에 있는 저장소 엔터티의 연결을 끊는 경우 기본값은 Dedicated 이므로 명령줄 구문에서 '-DeviceType' 옵션을 생략할 수 있습니다.
* "SnapDrive snap disconnect" 명령은 공유 스토리지 엔터티 또는 LUN이 "dedicated" 옵션과 연결이 끊기거나 전용 스토리지 엔터티 또는 LUN이 공유 옵션과 연결되지 않은 경우 오류를 표시합니다.
* SnapDrive for UNIX는 마스터 노드에서 'SnapDrive snap disconnect' 명령을 실행합니다. 이 경우 스토리지 엔터티가 폐기되고 마스터가 아닌 모든 노드의 LUN 연결이 끊기며 호스트 클러스터의 마스터 노드에서 LUN의 연결이 끊어집니다. 오류가 발생하면 스냅샷 연결 해제 작업이 실패합니다.

