---
permalink: solaris/concept_snapdrive_for_unix_overview.html 
sidebar: sidebar 
keywords: snap, snapdrive, unix 
summary: SnapDrive for UNIX는 간소화된 스토리지 프로비저닝과 파일 시스템의 일관된 Snapshot 복사본을 통해 데이터 관리를 단순화하고 애플리케이션 데이터의 가용성과 안정성을 높여줍니다. 
---
= UNIX용 SnapDrive 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapDrive for UNIX는 간소화된 스토리지 프로비저닝과 파일 시스템의 일관된 Snapshot 복사본을 통해 데이터 관리를 단순화하고 애플리케이션 데이터의 가용성과 안정성을 높여줍니다.

SnapDrive for UNIX는 데이터 백업을 단순화하여 삭제 또는 수정하더라도 데이터를 복구할 수 있도록 합니다. SnapDrive for UNIXuses 스냅샷 기술을 사용하여 UNIX 호스트에 연결된 공유 또는 비공유 스토리지 시스템에서 데이터 이미지를 생성합니다. 스냅샷 복사본을 복원하면 스토리지 시스템의 현재 데이터가 스냅샷 복사본의 데이터로 교체됩니다.

UNIX용 SnapDrive를 사용하면 스토리지 시스템에서 스토리지 프로비저닝을 자동화하여 Oracle SFRAC(Real Application Clusters) 환경의 VERITAS Storage Foundation에서 로컬 노드 및 클러스터 전체 공유 파일 시스템을 모두 관리할 수 있습니다. SnapDrive for UNIX는 호스트 측 애플리케이션 표시 파일, 볼륨 관리자 및 스토리지 시스템 측 LUN(Logical Unit Number)과 같은 전체 스토리지 계층을 관리할 수 있는 스토리지 기능을 제공합니다.

UNIX용 SnapDrive는 역할 기반 액세스 제어를 지원합니다. 스토리지 관리자는 RBAC를 사용하여 사용자가 수행하는 역할과 작업에 따라 스토리지 시스템에 대한 사용자의 액세스를 제한합니다.


NOTE: RBAC를 사용하려면 Operations Manager 콘솔 3.7 이상을 사용해야 합니다.
