---
permalink: solaris/concept_how_snapdrive_forunix_usesautosupport.html 
sidebar: sidebar 
keywords: snap, snadrive, unix, autosupport 
summary: 'AutoSupport 메시지는 SnapDrive.conf 파일에서 autosupport -enabled 옵션이 on 으로 설정된 경우 스토리지 시스템의 EMS 로그 뷰에 기록됩니다. 기본적으로 이 옵션은 SnapDrive.conf 파일에서 On 으로 설정됩니다. UNIX용 SnapDrive는 AutoSupport 메시지를 스토리지 시스템으로 전송하며, 여기서 메시지는 EMS(이벤트 관리 시스템)에 기록됩니다.' 
---
= UNIX용 SnapDrive에서 AutoSupport를 사용하는 방법
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
sapdrive.conf 파일에서 '_autosupport-enabled_' 옵션이 'on'으로 설정되어 있으면 스토리지 시스템의 EMS 로그 보기에 AutoSupport 메시지가 기록됩니다. 기본적으로 이 옵션은 'napdrive.conf' 파일에서 '_on_'으로 설정됩니다. UNIX용 SnapDrive는 AutoSupport 메시지를 스토리지 시스템으로 전송하며, 여기서 메시지는 EMS(이벤트 관리 시스템)에 기록됩니다.

AutoSupport 메시지는 다음과 같은 경우에 전송됩니다.

* 운영 장애로 인해 작업이 중지되면 작업이 실패한 스토리지 시스템으로 AutoSupport 메시지가 전송됩니다.
* 여러 스토리지 시스템이 호스트에 접속되어 있고 둘 이상의 스토리지 시스템에서 운영 장애가 발생하는 경우 SnapDrive for UNIX는 AutoSupport 메시지를 작업에 실패한 특정 스토리지 시스템으로 보냅니다.
* "_SnapDrive config set <username><filername>_"을 사용하여 새 스토리지 컨트롤러를 추가하면 UNIX용 SnapDrive는 지정된 스토리지 시스템으로 AutoSupport 메시지를 보냅니다.
* SnapDrive 데몬이 재시작되거나 시작되면 AutoSupport 메시지가 구성된 스토리지 시스템으로 전송됩니다.
* SnapDrive storage show-all 명령을 실행하면 구성된 모든 스토리지 시스템으로 AutoSupport 메시지가 전송됩니다.
* 스냅 생성 작업이 성공하면 AutoSupport 메시지가 스토리지 시스템으로 전송됩니다.

