---
permalink: solaris/concept_migrating_to_new_vserver_name.html 
sidebar: sidebar 
keywords: snap, snapdrive, vserver, migrate, name 
summary: 이전 SVM에서 새 SVM으로 마이그레이션한 경우, 새 SVM 이름이 호스트 시스템에서 SVM에 대한 SnapDrive 작업을 실행하도록 구성되어 있는지 확인해야 합니다. 
---
= 새 Vserver 이름으로 마이그레이션
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이전 SVM에서 새 SVM으로 마이그레이션한 경우, 새 SVM 이름이 호스트 시스템에서 SVM에 대한 SnapDrive 작업을 실행하도록 구성되어 있는지 확인해야 합니다.

새 Vserver 이름으로 마이그레이션할 때마다 호스트 시스템에서 다음 단계를 수행해야 합니다.

.단계
. 다음 명령을 사용하여 구성된 이전 SVM 이름을 삭제합니다.
+
(* SnapDrive config delete_appliance_name_*)

+
이전에 구성된 SVM 이름이 호스트 시스템에서 제거됩니다.

. 다음 명령을 사용하여 이전에 구성된 SVM에 할당된 포트 세트를 삭제합니다.
+
'* SnapDrive delete_filername_[_filername..._] * '

. 다음 명령을 사용하여 새 SVM 이름을 구성합니다.
+
'* SnapDrive config set_vsadmin filername_[_filername..._] * '

. 다음 명령을 사용하여 포트 세트를 할당합니다.
+
(* SnapDrive add_포트셋_이름_파일 이름 [_filername..._] *

. 다음 명령을 사용하여 새 Vserver 이름을 마이그레이션합니다.
+
``SnapDrive config migrate set_old_entry new_entry_*’



새 SVM으로 마이그레이션한 후에는 호스트 시스템에서 새 Vserver 이름에 대한 SnapDrive 작업을 실행할 준비가 된 것입니다.

* 관련 정보 *

xref:task_migrating_from_old_host_name_to_new_host_name.adoc[이전 스토리지 시스템에서 새 스토리지 시스템으로 마이그레이션]
