---
permalink: solaris/reference_some_configuration_commands.html 
sidebar: sidebar 
keywords: snap, snapdrive, configuration, command 
summary: UNIX용 SnapDrive를 구성하는 데 도움이 되는 명령이 몇 가지 있습니다. 
---
= 일부 구성 명령
:icons: font
:imagesdir: ../media/


[role="lead"]
UNIX용 SnapDrive를 구성하는 데 도움이 되는 명령이 몇 가지 있습니다.

다음 표에는 UNIX용 SnapDrive를 구성하는 데 유용한 추가 명령이 요약되어 있습니다.

|===
| 명령 또는 작업 | 설명 


 a| 
UNIX용 SnapDrive 소프트웨어 버전 구성 및 확인



 a| 
``SnapDrive config show *’’입니다
 a| 
'napdrive.conf' 파일의 값을 확인한다.



 a| 
``SnapDrive version *’’
 a| 
UNIX용 SnapDrive 버전을 확인합니다.



 a| 
``스냅드라이브 시작 *’
 a| 
UNIX용 SnapDrive 데몬을 시작합니다.



 a| 
`* SnapDrive config prepare LUNs-count count_value * '

[-DeviceType{shared|dedicated}]
 a| 
호스트를 준비하여 특정 수의 LUN을 생성하고 생성할 수 있는 LUN을 결정합니다.



 a| 
'* SnapDrive config set-viadmin <user><viadmin_name>*'
 a| 
게스트가 Solaris x86 게스트 OS에서 RDM LUN을 생성할 수 있도록 준비합니다.


NOTE: 호스트 유틸리티 없이 FCP 프로토콜을 사용하여 Solaris x86 호스트에서만 이러한 명령을 사용할 수 있습니다.



 a| 
'* SnapDrive 클론 분할 * '
 a| 
볼륨 클론 또는 LUN 클론의 분할 상태를 예상, 시작, 중지 및 쿼리합니다.



 a| 
``SnapDrive 구성 검사 클러스터 *’
 a| 
Solaris 호스트의 SFRAC 클러스터 환경에서 다음 사항을 확인합니다.

* UNIX용 SnapDrive 버전
* 그룹 멤버십 서비스/Gab(Atomic Broadcast) 구성
* 클러스터 상태입니다
* CVM(호스트 클러스터 볼륨 관리자) 상태입니다
* 호스트 클러스터 노드 내에서 보안 통신을 위해 rsh 또는 ssh를 사용합니다
* 'napdrive.conf' 파일에서 다음과 같은 구성 변수 값을 설정할 때 차이가 있습니다.
+
** `_default-transport=fcp_'
** 다중 경로 - 유형 = DMP






 a| 
'napdrive.conf' 파일에서 변수를 편집합니다.
 a| 
로그 파일의 경로 이름 및 옵션을 변경합니다. UNIX용 SnapDrive는 다음 세 파일에 정보를 기록합니다.

* 감사 파일
* 복구 파일
* 추적 파일




 a| 
호스트와 스토리지 시스템 간의 액세스 제어 권한 설정 및 표시



 a| 
해당 호스트와 연결된 스토리지 시스템에서 액세스 제어 권한 파일(sd"_hostname_".prbac)을 편집합니다.
 a| 
호스트가 스토리지 시스템에 가지고 있는 액세스 제어 권한을 지정합니다. 스토리지 시스템의 호스트에 대해 다음 액세스 수준을 설정할 수 있습니다.

* 없음 -- 액세스할 수 없습니다.
* 스냅 생성 -- 스냅샷 복사본 생성
* 스냅샷 사용 -- 스냅샷 복사본을 삭제하고 이름을 바꿉니다.
* 모두 스냅 -- 스냅샷 복사본을 생성, 복원, 삭제, 이름 변경합니다.
* 스토리지 생성 삭제 -- 스토리지를 생성, 크기 조정 및 삭제합니다.
* 스토리지 사용 -- 스토리지 연결 및 연결 해제
* 모두 저장 -- 저장소를 생성, 삭제, 연결 및 연결 해제합니다.
* 모든 액세스 -- 모든 작업




 a| 
"* SnapDrive config access show <filer_name>*"
 a| 
호스트가 스토리지 시스템에 가지고 있는 액세스 제어 권한에 대한 정보를 표시합니다.



 a| 
(* SnapDrive config delete <filername>[<filername>. . .] * '
 a| 
UNIX용 SnapDrive에서 지정된 사용자 이름-암호 쌍을 제거합니다.

|===