---
permalink: solaris/reference_error_message_values.html 
sidebar: sidebar 
keywords: snap, snapdrive, error, message, value 
summary: UNIX용 SnapDrive를 사용할 때 자주 나타나는 몇 가지 오류 메시지를 알고 이를 해결하는 방법을 알고 있으면 도움이 됩니다. 
---
= 오류 메시지 값
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
UNIX용 SnapDrive를 사용할 때 자주 나타나는 몇 가지 오류 메시지를 알고 이를 해결하는 방법을 알고 있으면 도움이 됩니다.

다음 표에는 UNIX용 SnapDrive를 사용할 때 발생할 수 있는 가장 일반적인 오류에 대한 자세한 정보가 나와 있습니다.

[cols="15,20,15,25,40"]
|===
| 오류 코드 | 반환 코드 | 유형 | 메시지 | 해결 방법 


 a| 
0000-001
 a| 
해당 없음
 a| 
관리자
 a| 
스토리지 시스템 <storage-system-name>에 대해 다사가 구성되었습니다. SnapDrive config delete -mgmtpath 명령을 사용하여 삭제하고 다시 시도하십시오.
 a| 
스토리지 시스템을 삭제하기 전에 'SnapDrive config delete -mgmtd path' 명령을 사용하여 스토리지 시스템에 대해 구성된 관리 경로를 삭제하십시오.



 a| 
0001-242
 a| 
해당 없음
 a| 
관리자
 a| 
"https를 사용하여 스토리지 시스템에 접속할 수 없습니다: 10.72.197.213. 10.72.197.213이 유효한 스토리지 시스템 이름/주소인지 확인합니다. 그리고 구성한 스토리지 시스템이 7-Mode에서 작동하는 Data ONTAP에서 실행 중인 경우 신뢰할 수 있는 호스트(options trusted.hosts)에 호스트를 추가하고 스토리지 시스템 10.72.197.213에서 SSL을 설정하거나 SnapDrive.conf를 수정하여 통신에 http를 사용하고 SnapDrive 데몬을 재시작합니다. 구성하는 스토리지 시스템이 clustered Data ONTAP에서 실행 중인 경우 SVM 이름이 SVM 관리 LIF의 IP 주소에 매핑되어 있는지 확인합니다
 a| 
다음 상태를 점검하십시오.

* 접속된 스토리지 시스템이 유효한 스토리지 시스템인지 확인합니다.
* 구성하려는 스토리지 시스템이 7-Mode에서 작동하는 Data ONTAP에서 실행 중인 경우, 신뢰할 수 있는 호스트에 동일한 스토리지 시스템을 추가하고 스토리지 시스템에서 SSL을 설정하거나 통신에 HTTP를 사용하도록 'scapdrive.conf' 파일을 수정한 다음 SnapDrive 데몬을 재시작합니다.
* 구성하려는 스토리지 시스템이 clustered Data ONTAP에서 실행 중인 경우 SVM 이름이 SVM(관리 논리 인터페이스)의 IP 주소에 매핑되어 있는지 확인합니다.




 a| 
0003-004
 a| 
해당 없음
 a| 
관리자
 a| 
"게스트 OS에서 스토리지 시스템 <storage-system-name>의 LUN <lun-name>을(를) 디포트하지 못했습니다. 원인: CoreOS에서 입력된 매핑 장치 정보가 없습니다
 a| 
이 문제는 게스트 운영 체제에서 'SnapDrive 스냅 분리' 작업을 실행할 때 발생합니다.

ESX Server에 RDM LUN 매핑이 있는지 또는 ESX Server에 오래된 RDM 항목이 있는지 확인합니다.

ESX Server 및 게스트 운영 체제에서 RDM 매핑을 수동으로 삭제합니다.



 a| 
0001-019
 a| 
3
 a| 
명령
 a| 
'유효하지 않은 명령줄 -- 중복된 파일:<DG1/vol2 및 DG1/vol2>'
 a| 
이는 명령이 동일한 호스트 볼륨에 여러 호스트 엔터티를 가지고 있을 때 발생합니다.

예를 들어 명령은 호스트 볼륨과 파일 시스템을 동일한 호스트 볼륨에 명시적으로 지정했습니다.

다음 단계를 완료합니다.

. 호스트 요소의 모든 중복 인스턴스를 제거합니다.
. 명령을 다시 실행합니다.




 a| 
0001-023
 a| 
11
 a| 
관리자
 a| 
"디스크 그룹 DG1의 모든 LUN을 검색할 수 없습니다. 장치가 응답하지 않습니다: DG1 스토리지 시스템에서 LUN 상태를 확인하고 필요한 경우 LUN을 온라인으로 설정하거나 신뢰할 수 있는 호스트(options trusted.hosts)에 호스트를 추가하고 스토리지 시스템에서 SSL을 활성화하거나 스토리지 시스템 통신에 (http/https)를 사용하도록 SnapDrive.conf를 변경하고 SnapDrive 데몬을 다시 시작하십시오
 a| 
이 문제는 장치의 SCSI 문의가 실패할 때 발생합니다. 장치의 SCSI 문의는 여러 가지 이유로 실패할 수 있습니다.

다음 단계를 실행합니다.

. 장치 재시도 구성 변수를 더 높은 값으로 설정합니다.
+
예를 들어, 10으로 설정하고(기본값은 3) 명령을 다시 실행합니다.

. 장치에 대한 정보를 얻으려면 '-all' 옵션과 함께 'SnapDrive storage show' 명령을 사용합니다.
. 스토리지 시스템에서 FC 또는 iSCSI 서비스가 실행 중인지 확인합니다.
+
그렇지 않은 경우 스토리지 관리자에게 문의하여 스토리지 시스템을 온라인으로 전환합니다.

. FC 또는 iSCSI 서비스가 호스트에서 작동 중인지 확인합니다.


위의 방법으로도 문제가 해결되지 않으면 기술 지원 부서에 문의하십시오.



 a| 
'0001-218'
 a| 
 a| 
관리자
 a| 
device/dev/mapper - SCSI 문의에 실패했습니다. LUN이 응답하지 않습니다. 스토리지 시스템의 LUN 상태를 확인하고 필요한 경우 LUN을 온라인 상태로 전환합니다
 a| 
이 문제는 장치의 SCSI 문의가 SLES10 SP2에서 실패할 때 발생합니다. lvm2-2.02.17-7.27.8 및 '_filter_' 설정은 SLES10 SP2의 "lvm.conf" 파일에서 "=[A|/dev/mapper/.\ * |", "A|/dev/ciss/. * |", "r/. */"]로 지정됩니다.

lvm.conf 파일에서 '["r|/dev/.\ * /by-path/. * |", "r|/dev/.\ * /by-id/. * |", "r|/dev/ciss/.\ * |", "a/. */"]로 설정합니다.



 a| 
'0001-395'
 a| 
해당 없음
 a| 
관리자
 a| 
"이 호스트에 HBA가 없습니다!
 a| 
이 문제는 호스트 시스템에 많은 수의 LUN이 연결되어 있는 경우에 발생합니다.

'sapdrive.conf' 파일에서 변수 '_enable-fcp-cache_'가 ON으로 설정되어 있는지 확인합니다.



 a| 
0001-389
 a| 
해당 없음
 a| 
관리자
 a| 
HBA 보조자 solarisfcp에 대한 HBA 유형을 가져올 수 없습니다
 a| 
이 문제는 호스트 시스템에 많은 수의 LUN이 연결되어 있는 경우에 발생합니다.

'sapdrive.conf' 파일에서 변수 '_enable-fcp-cache_'가 ON으로 설정되어 있는지 확인합니다.



 a| 
0001-389
 a| 
해당 없음
 a| 
관리자
 a| 
HBA 보조자 vmwarfcp에 대한 HBA 유형을 가져올 수 없습니다
 a| 
다음 조건을 확인해야 합니다.

* 스토리지를 생성하기 전에 다음 명령을 사용하여 가상 인터페이스를 구성했는지 확인합니다.
+
'* SnapDrive config set_-viadmin <user><virtual_interface_ip or name>_ *'

* 가상 인터페이스에 대한 스토리지 시스템이 있고 동일한 오류 메시지가 계속 나타나는지 확인한 다음 스토리지 생성 작업을 성공적으로 수행하려면 UNIX용 SnapDrive를 다시 시작합니다.
* 에 설명된 대로 Virtual Storage Console의 구성 요구 사항을 충족하는지 확인합니다 link:https://www.netapp.com/pdf.html?item=/media/7350-ds-3057.pdf["VMware vSphere용 NetApp Virtual Storage Console을 참조하십시오"]




 a| 
0001-682
 a| 
해당 없음
 a| 
관리자
 a| 
새 LUN에 대한 호스트 준비가 실패했습니다. 이 기능 checkControllers는 지원되지 않습니다
 a| 
SnapDrive 작업이 성공적으로 수행되도록 명령을 다시 실행합니다.



 a| 
0001-859
 a| 
해당 없음
 a| 
관리자
 a| 
"호스트의 인터페이스 중 스토리지 시스템 <directory name> 디렉토리에 액세스할 수 있는 NFS 권한이 없는 것은 없습니다.
 a| 
'napdrive.conf' 파일에서 '_check-export-permission-nfs-clone_' 설정 변수가 'off'로 설정되어 있는지 확인합니다.



 a| 
0002-253
 a| 
 a| 
관리자
 a| 
Flex clone 생성에 실패했습니다
 a| 
스토리지 시스템 측 오류입니다. sd-trace.log 및 스토리지 시스템 로그를 수집하여 문제를 해결하십시오.



 a| 
0002-264
 a| 
 a| 
관리자
 a| 
"filer <filer name> 파일러에서는 FlexClone이 지원되지 않습니다.
 a| 
FlexClone은 스토리지 시스템의 현재 Data ONTAP 버전에서는 지원되지 않습니다. 스토리지 시스템의 Data ONTAP 버전을 7.0 이상으로 업그레이드한 다음 명령을 재시도하십시오.



 a| 
0002-265
 a| 
 a| 
관리자
 a| 
'filername> 파일러에서 flex_clone 라이센스를 확인할 수 없습니다.
 a| 
스토리지 시스템 측 오류입니다. sd-trace.log 및 스토리지 시스템 로그를 수집하여 문제를 해결합니다.



 a| 
0002-266
 a| 
해당 없음
 a| 
관리자
 a| 
"filername> 파일러에 FlexClone 라이센스가 없습니다.
 a| 
FlexClone은 스토리지 시스템에 라이센스가 없습니다. 스토리지 시스템에 FlexClone 라이센스를 추가한 후 명령을 재시도하십시오.



 a| 
0002-267
 a| 
해당 없음
 a| 
관리자
 a| 
'FlexClone은 루트 볼륨 <volume-name>에서 지원되지 않습니다.
 a| 
FlexClone은 루트 볼륨에 대해 생성할 수 없습니다.



 a| 
0002-270
 a| 
해당 없음
 a| 
관리자
 a| 
"Aggregate-name>의 여유 공간은 diskgroup/FlexClone 메타데이터에 필요한 <size>MB(메가바이트) 미만입니다.
 a| 
. FlexClone을 사용하여 원시 LUN에 연결하려면 애그리게이트에 2MB의 여유 공간이 필요합니다.
. 1단계와 2단계에 따라 Aggregate의 일부 공간을 확보한 후 명령을 재시도하십시오.




 a| 
0002-332
 a| 
해당 없음
 a| 
관리자
 a| 
's.snapshot.restore access denied on qtree storage_array1:/vol/vol1/qtree1 for user lnx197-142\john'
 a| 
필요한 기능을 사용자에게 부여하려면 Operations Manager 관리자에게 문의하십시오.



 a| 
'0002-364'
 a| 
해당 없음
 a| 
관리자
 a| 
"DFM: lnx197-146에 연락할 수 없습니다. 사용자 이름 및/또는 암호를 변경하십시오.
 a| 
SD-admin 사용자의 사용자 이름 및 암호를 확인하고 수정합니다.



 a| 
0002-268
 a| 
해당 없음
 a| 
관리자
 a| 
'<volume-Name>은(는) 유연한 볼륨이 아닙니다
 a| 
FlexClone은 기존 볼륨에 대해 생성할 수 없습니다.



 a| 
0003-003
 a| 
 a| 
관리자
 a| 
. "스토리지 시스템 <storage_name>의 LUN <lun_name>을 게스트 OS로 내보내지 못했습니다.


또는
 a| 
* ESX Server의 ESX Server(또는) 오래된 RDM 항목에 RDM LUN 매핑이 있는지 확인합니다.
* ESX Server 및 게스트 운영 체제에서 RDM 매핑을 수동으로 삭제합니다.




 a| 
0003-012
 a| 
 a| 
관리자
 a| 
"가상 인터페이스 서버 Win2K3-225-238 에 연결할 수 없습니다.
 a| 
호스트/게스트 OS에 대해 NIS가 구성되지 않았습니다.

'/etc/hosts'에 있는 파일에 이름과 IP 매핑을 제공해야 합니다

예: `#cat/etc/hosts10.72.225.238 win2k3-225-238.eng.org.com Win2K3-225-238'



 a| 
'0001-552'
 a| 
해당 없음
 a| 
명령
 a| 
"볼륨-클론 또는 LUN-클론이 올바르지 않습니다.
 a| 
기존 볼륨에 대해 클론 분할을 생성할 수 없습니다.



 a| 
0001-553
 a| 
해당 없음
 a| 
명령
 a| 
파일러 이름>에 저장 공간이 부족하여 "FS-이름"을 분할할 수 없습니다
 a| 
클론 분할은 분할 프로세스를 계속하며 스토리지 시스템에서 사용 가능한 스토리지 공간이 부족하여 갑자기 클론 분할이 중지됩니다.



 a| 
0003-002
 a| 
 a| 
명령
 a| 
더 이상 LUN을 게스트 OS로 내보낼 수 없습니다
 a| 
컨트롤러에 대한 ESX Server에서 지원하는 디바이스 수가 최대 한도에 도달했으므로 게스트 운영 체제에 대해 더 많은 컨트롤러를 추가해야 합니다.

* 참고: * ESX Server는 게스트 운영 체제당 최대 컨트롤러를 4개로 제한합니다.



 a| 
9000023
 a| 
1
 a| 
명령
 a| 
키워드 LUN에 대한 인수 없음
 a| 
이 오류는 '-lun' 키워드의 명령에 '_lun_name_' 인수가 없을 때 발생합니다.

실행할 작업: 다음 중 하나를 수행합니다.

. '-lun' 키워드를 사용하여 명령에 대한 '_lun_name_' 인수를 지정하십시오.
. SnapDrive for UNIX 도움말 메시지를 확인합니다




 a| 
'0001-028'
 a| 
1
 a| 
명령
 a| 
"파일 시스템</mnt/QA/dg4/vol1>은 SnapDrive에서 관리하지 않는 형식(HFS)입니다. 파일 시스템 <mnt/qa/dg4/vol1>'을(를) 제외하고 요청을 다시 제출하십시오
 a| 
이 오류는 지원되지 않는 파일 시스템 유형이 명령의 일부일 때 발생합니다.

실행할 작업: 파일 시스템 유형을 제외하거나 업데이트한 다음 명령을 다시 사용합니다.

최신 소프트웨어 호환성 정보는 상호 운용성 매트릭스 를 참조하십시오.



 a| 
9000-030
 a| 
1
 a| 
명령
 a| 
'-LUN은 다른 키워드와 결합할 수 없습니다.
 a| 
이 오류는 '-lun' 키워드를 '-fs' 또는 '-dg' 키워드와 결합할 때 발생합니다. 구문 오류이며 명령을 잘못 사용하고 있음을 나타냅니다.

실행할 작업: '-lun' 키워드로만 명령을 다시 실행합니다.



 a| 
0001-034
 a| 
1
 a| 
명령
 a| 
'마운트 실패: 마운트: <device name>은(는) 유효한 블록 디바이스가 아닙니다.
 a| 
이 오류는 복제된 LUN이 스냅샷 복사본에 있는 동일한 파일 사양에 이미 연결되어 있는 경우 "SnapDrive snap restore" 명령을 실행하려고 할 때만 발생합니다.

클론 복제된 LUN을 삭제할 때 iSCSI 데몬이 복원된 LUN에 대한 디바이스 항목을 다시 매핑하므로 명령이 실패합니다.

실행할 작업: 다음 중 하나를 수행합니다.

. SnapDrive snap restore 명령을 다시 수행한다.
. 원래 LUN의 스냅샷 복사본을 복구하려고 시도하기 전에 연결된 LUN(스냅샷 복사본의 동일한 파일 사양에 마운트된 경우)을 삭제합니다.




 a| 
0001-046, 0001-047
 a| 
1
 a| 
명령
 a| 
"잘못된 스냅샷 이름:</vol/vol1/no_filer_pre fix> 또는 잘못된 스냅샷 이름: no_long_FILERNAME - 파일러 볼륨 이름이 없습니다.
 a| 
잘못된 스냅샷 이름으로 스냅샷 작업이 시도되는 잘못된 명령 사용을 나타내는 구문 오류입니다.

실행할 작업: 다음 단계를 완료합니다.

. SnapDrive snap list -filer <filer-volume-name> 명령을 사용하여 스냅샷 복사본 목록을 가져옵니다.
. long_snap_name 인수를 사용하여 명령을 실행합니다.




 a| 
9000047
 a| 
1
 a| 
명령
 a| 
'한 스냅이름 이상의 논쟁'이 있습니다
 a| 
UNIX용 SnapDrive에서는 스냅샷 작업을 수행하기 위해 명령줄에 둘 이상의 스냅샷 이름을 사용할 수 없습니다.

실행할 작업: 하나의 스냅샷 이름만 사용하여 명령을 다시 실행합니다.



 a| 
9000049
 a| 
1
 a| 
명령
 a| 
``DG와 -v는 결합될 수 없다’’고 밝혔습니다
 a| 
이 오류는 '-dg'와 '-vg' 키워드를 함께 사용할 때 발생합니다. 구문 오류이며 명령을 잘못 사용하고 있음을 나타냅니다.

실행할 작업 -dg 또는 -vg 키워드를 사용하여 명령을 실행합니다.



 a| 
9,000-050
 a| 
1
 a| 
명령
 a| 
'-lvol과 -hostvo는 함께 사용할 수 없습니다
 a| 
이 오류는 '-lvol'과 '-hostvol' 키워드를 함께 사용할 때 발생합니다. 구문 오류이며 명령을 잘못 사용하고 있음을 나타냅니다. 실행할 작업: 다음 단계를 완료합니다.

. 명령행에서 '-lvol' 옵션을 '-hostvol' 옵션으로 변경하거나 반대로 변경합니다.
. 명령을 실행합니다.




 a| 
9000057입니다
 a| 
1
 a| 
명령
 a| 
필수 스냅 이름 인수 표시
 a| 
snap_name 인수를 제공하지 않고 스냅샷 작업이 시도되는 명령을 사용할 수 없음을 나타내는 구문 오류입니다.

실행할 작업: 적절한 스냅샷 이름을 사용하여 명령을 실행합니다.



 a| 
0001-067
 a| 
6
 a| 
명령
 a| 
스냅샷 매시간 0은 SnapDrive가 제작하지 않았습니다
 a| 
Data ONTAP에서 생성하는 자동 시간별 스냅샷 복사본입니다.



 a| 
0001-092
 a| 
6
 a| 
명령
 a| 
'filervol exocet:</vol/vol1>'에 'napshot <non_existent_24965>이 없습니다
 a| 
지정한 스냅샷 복사본을 스토리지 시스템에서 찾을 수 없습니다. 실행할 작업: 'SnapDrive snap list' 명령을 사용하여 스토리지 시스템에 있는 스냅샷 복사본을 찾을 수 있습니다.



 a| 
0001-099
 a| 
10
 a| 
관리자
 a| 
"잘못된 스냅샷 이름:<exocet:/vol2/dbvol:New SnapName>이(가) 파일러 볼륨 이름 <exocet:/vol/vol1>과(와) 일치하지 않습니다.
 a| 
잘못된 스냅샷 이름으로 스냅샷 작업이 시도되는 명령의 잘못된 사용을 나타내는 구문 오류입니다.

실행할 작업: 다음 단계를 완료합니다.

. 스냅샷 복사본 목록을 보려면 "SnapDrive snap list -filer_<filer-volume-name>_" 명령을 사용하십시오.
. SnapDrive for UNIX에서 검증된 올바른 형식의 스냅샷 이름으로 명령을 실행합니다. 정규화된 형식은 '_long_snap_name_'과 '_short_snap_name_'입니다.




 a| 
'0001-122'
 a| 
6
 a| 
관리자
 a| 
"filer <exocet>: 지정한 볼륨이 없습니다.
 a| 
이 오류는 지정된 스토리지 시스템(파일러) 볼륨이 없을 때 발생합니다.

실행할 작업: 다음 단계를 완료합니다.

. 유효한 스토리지 시스템 볼륨 목록을 보려면 스토리지 관리자에게 문의하십시오.
. 유효한 스토리지 시스템 볼륨 이름을 사용하여 명령을 실행합니다.




 a| 
0001-124
 a| 
111
 a| 
관리자
 a| 
"filer <exocet>:LUN clone에서 <snap_delete_multi_inuse_24374>를 리모델링하지 못했습니다.
 a| 
LUN 클론이 존재하기 때문에 지정된 스냅샷 복사본에 대한 '스냅샷 삭제' 작업이 실패했습니다.

실행할 작업: 다음 단계를 완료합니다.

. SnapDrive storage show 명령을 `-all' 옵션과 함께 사용하여 스냅샷 복사본의 LUN 클론(스냅샷 복사본 출력 백업의 일부)을 찾습니다.
. 클론에서 LUN을 분할하려면 스토리지 관리자에게 문의하십시오.
. 명령을 다시 실행합니다.




 a| 
'0001-155'
 a| 
4
 a| 
명령
 a| 
's냅샷 <dup_snapname23980>이(가) 이미 <exocet:/vol/vol1>에 있습니다. 기존 스냅샷을 덮어쓰려면 -f(강제) 플래그를 사용하십시오
 a| 
이 오류는 명령에 사용된 스냅샷 복사본 이름이 이미 있는 경우에 발생합니다.

실행할 작업: 다음 중 하나를 수행합니다.

. 다른 스냅샷 이름으로 명령을 다시 실행합니다.
. 기존 스냅샷 복사본을 덮어쓰려면 "-f"(force) 플래그를 사용하여 명령을 다시 실행합니다.




 a| 
'0001-158'
 a| 
84
 a| 
명령
 a| 
snapshotexocet:/vol/VO L1: overwrite_nocforce_25 078>을(를) 가져온 이후 dkgroup 구성이 변경되었습니다. hostvol</dev/dg3/vol4>경고를 무시하고 복원을 완료하려면 '-f'(강제) 플래그를 사용하십시오
 a| 
디스크 그룹에는 여러 개의 LUN이 포함될 수 있으며 디스크 그룹 구성이 변경되면 이 오류가 발생합니다. 예를 들어, 스냅샷 복사본을 생성할 때 디스크 그룹은 LUN의 X 개수로 구성되어 있고 복제본을 생성한 후에는 디스크 그룹에 X+Y 개수의 LUN을 포함할 수 있습니다.

실행할 작업 -f(force) 플래그로 명령을 다시 사용합니다.



 a| 
'0001-185'
 a| 
해당 없음
 a| 
명령
 a| 
"Storage show failed: no NetApp devices to show or enable SSL on the filers or retry after Changing SnapDrive.conf to use http for filer communication.
 a| 
이 문제는 다음과 같은 이유로 발생할 수 있습니다. iSCSI 데몬이나 호스트의 FC 서비스가 중지되었거나 제대로 작동하지 않는 경우 호스트에 구성된 LUN이 있어도 SnapDrive storage show-all 명령이 실패합니다.

수행할 작업: 작동하지 않는 iSCSI 또는 FC 서비스 해결 LUN이 구성된 스토리지 시스템이 다운되었거나 재부팅 중입니다.

수행할 작업: LUN이 가동될 때까지 기다립니다. '_usehttps-to-filer_' 구성 변수에 설정된 값이 지원되는 구성이 아닐 수 있습니다.

실행할 작업: 다음 단계를 완료합니다.

. 'anlun lun show all' 명령을 사용하여 호스트에 매핑된 LUN이 있는지 확인합니다.
. 호스트에 매핑된 LUN이 있는 경우 오류 메시지에 설명된 지침을 따릅니다.


"_usehttps-to-filer_" 구성 변수 값을 (""off""인 경우 ""on""으로, 값이 ""on""인 경우 ""off""로 변경).



 a| 
0001-226
 a| 
3
 a| 
명령
 a| 
''스냅 생성'을 사용하려면 모든 파일 시스템에 액세스할 수 있어야 합니다. 파일 시스템:</mnt/QA/DG1/vol3>'에 액세스할 수 없는 파일 사양을 확인하십시오
 a| 
이 오류는 지정된 호스트 엔터티가 없을 때 발생합니다.

실행할 작업: 호스트에 있는 호스트 엔터티를 찾으려면 '-ALL' 옵션과 함께 'SnapDrive storage show' 명령을 다시 사용합니다.



 a| 
0001-242
 a| 
18
 a| 
관리자
 a| 
"파일러에 연결할 수 없습니다: <filername>"
 a| 
UNIX용 SnapDrive는 보안 HTTP 프로토콜을 통해 스토리지 시스템에 연결을 시도합니다. 호스트가 스토리지 시스템에 접속할 수 없는 경우 오류가 발생할 수 있습니다. 실행할 작업: 다음 단계를 완료합니다.

. 네트워크 문제:
+
.. nslookup 명령을 사용하여 호스트를 통해 작동하는 스토리지 시스템의 DNS 이름 확인을 확인합니다.
.. 스토리지 시스템이 없는 경우 DNS 서버에 스토리지 시스템을 추가합니다.




호스트 이름 대신 IP 주소를 사용하여 스토리지 시스템에 접속할 수도 있습니다.

. 스토리지 시스템 구성:
+
.. UNIX용 SnapDrive가 작동하려면 보안 HTTP 액세스를 위한 라이센스 키가 있어야 합니다.
.. 라이센스 키를 설정한 후 웹 브라우저를 통해 스토리지 시스템에 액세스할 수 있는지 확인합니다.


. 1단계 또는 2단계 또는 두 단계 모두를 수행한 후 명령을 실행합니다.




 a| 
0001-243
 a| 
10
 a| 
명령
 a| 
"잘못된 DG 이름:<SDU_DG1>"
 a| 
이 오류는 디스크 그룹이 호스트에 존재하지 않고 명령이 실패한 경우에 발생합니다. 예를 들어, 호스트에 '_SDU_DG1_'이(가) 없습니다.

실행할 작업: 다음 단계를 완료합니다.

. SnapDrive storage show -all 명령을 사용하여 모든 디스크 그룹 이름을 가져옵니다.
. 올바른 디스크 그룹 이름으로 명령을 다시 실행합니다.




 a| 
0001-246
 a| 
10
 a| 
명령
 a| 
"유효하지 않은 hostvolume 이름:</mnt/QA/dg2/BADFS>, 유효한 형식은 <vgname/hostvolname>(예: <mygroup/vol2>)입니다
 a| 
실행할 작업: 호스트 볼륨 이름에 다음과 같은 적절한 형식으로 명령을 다시 실행합니다. 'vgname/hostvolname'



 a| 
0001-360도
 a| 
34
 a| 
관리자
 a| 
"filer <exocet>:No such volume"에 LUN </vol/badvol1/nanehp13_unnewDg_FVE_SdLun>을 생성하지 못했습니다
 a| 
이 오류는 지정된 경로에 존재하지 않는 스토리지 시스템 볼륨이 포함되어 있을 때 발생합니다.

실행할 작업: 스토리지 관리자에게 문의하여 사용 가능한 스토리지 시스템 볼륨 목록을 확인하십시오.



 a| 
0001-372
 a| 
58
 a| 
명령
 a| 
"Bad LUN name"::"</vol/vol1/SCE_lun2a> - 형식을 인식할 수 없습니다.
 a| 
이 오류는 명령에 지정된 LUN 이름이 SnapDrive for UNIX에서 지원하는 미리 정의된 형식을 따르지 않는 경우에 발생합니다. UNIX용 SnapDrive를 사용하려면 미리 정의된 형식("<filer-name:/vol/<volname>/<lun-name>')으로 LUN 이름을 지정해야 합니다

실행할 작업: 다음 단계를 완료합니다.

. "SnapDrive help" 명령을 사용하여 SnapDrive for UNIX가 지원하는 LUN 이름의 미리 정의된 형식을 알 수 있습니다.
. 명령을 다시 실행합니다.




 a| 
0001-373
 a| 
6
 a| 
명령
 a| 
"다음 필수 LUN 1개를 찾을 수 없습니다: exocet:</vol/vol1/NotRealLun>
 a| 
이 오류는 스토리지 시스템에서 지정한 LUN을 찾을 수 없을 때 발생합니다.

실행할 작업: 다음 중 하나를 수행합니다.

. 호스트에 접속된 LUN을 보려면 'SnapDrive storage show-dev' 명령 또는 'SnapDrive storage show-all' 명령을 사용합니다.
. 스토리지 시스템의 전체 LUN 목록을 보려면 스토리지 관리자에게 문의하여 스토리지 시스템에서 lun show 명령의 출력을 확인하십시오.




 a| 
0001-377
 a| 
43
 a| 
명령
 a| 
"디스크 그룹 이름 <name>이(가) 이미 사용 중이거나 다른 엔티티와 충돌합니다.
 a| 
이 오류는 디스크 그룹 이름이 이미 사용 중이거나 다른 엔티티와 충돌할 때 발생합니다. 해야 할 일:

다음 중 하나를 수행합니다.

'-autorename' 옵션을 사용하여 명령을 실행합니다

호스트가 사용하고 있는 이름을 찾으려면 '-all' 옵션과 함께 'SnapDrive storage show' 명령을 사용합니다. 호스트에서 사용하지 않는 다른 이름을 지정하는 명령을 실행합니다.



 a| 
'0001-380'
 a| 
43
 a| 
명령
 a| 
"호스트 볼륨 이름 <dg3/vol1>이(가) 이미 사용 중이거나 다른 엔티티와 충돌합니다.
 a| 
이 오류는 호스트 볼륨 이름이 이미 사용 중이거나 다른 엔티티와 충돌할 때 발생합니다

실행할 작업: 다음 중 하나를 수행합니다.

. '-autorename' 옵션을 사용하여 명령을 실행합니다.
. 호스트가 사용하고 있는 이름을 찾으려면 '-all' 옵션과 함께 'SnapDrive storage show' 명령을 사용합니다. 호스트에서 사용하지 않는 다른 이름을 지정하는 명령을 실행합니다.




 a| 
'0001-417'
 a| 
51
 a| 
명령
 a| 
"다음 이름이 이미 사용 중입니다: <mydg1>. 다른 이름을 지정하십시오
 a| 
실행할 작업: 다음 중 하나를 수행합니다.

. '-autorename' 옵션을 사용하여 명령을 다시 실행합니다.
. SnapDrive storage show -all 명령을 사용하여 호스트에 있는 이름을 찾습니다. 명령을 다시 실행하여 호스트가 사용하지 않는 다른 이름을 명시적으로 지정합니다.




 a| 
0001-422
 a| 
해당 없음
 a| 
명령
 a| 
"LUN의 LVM 초기화 실패: c2t500A09818667B9DAd0 VxVM vxdisksetup 오류 V-5-2-5241은 디스크 구조를 가져올 수 없기 때문에 레이블을 지정할 수 없습니다.
 a| 
실행할 작업: Solaris SPARC(Scalable Processor Architecture)용 최신 패치 146019-02를 설치했는지 확인합니다.



 a| 
0001-430
 a| 
51
 a| 
명령
 a| 
'dg/vg dg와 -lvol/hostvol dG/vol 둘 다 지정할 수 없습니다.
 a| 
잘못된 명령 사용을 나타내는 구문 오류입니다. 명령줄에는 '-dg/vg' 키워드 또는 '-lvol/hostvol' 키워드를 사용할 수 있지만 둘 다 사용할 수는 없습니다.

실행할 작업: '-dg/vg' 또는 '-lvol/hostvol' 키워드만으로 명령을 실행합니다.



 a| 
0001-434
 a| 
6
 a| 
명령
 a| 
'스냅샷 엑소셋:/vol/vol1: NOT_E IST가 스토리지 볼륨 엑소셋:/vol/vol1'에 없습니다
 a| 
이 오류는 지정된 스냅샷 복사본을 스토리지 시스템에서 찾을 수 없을 때 발생합니다.

실행할 작업: 'SnapDrive snap list' 명령을 사용하여 스토리지 시스템에 있는 스냅샷 복사본을 찾을 수 있습니다.



 a| 
0001-435
 a| 
3
 a| 
명령
 a| 
명령줄에서 모든 호스트 볼륨 및/또는 모든 파일 시스템을 지정하거나 -autostExpand 옵션을 지정해야 합니다

"명령줄에 다음 이름이 누락되었지만 스냅샷 <Snap2_5VG_SINGLELUN_REMOTE>에서 발견되었습니다. 호스트 볼륨:<dg3/vol2> 파일 시스템:</mnt/QA/dg3/vol2>.
 a| 
지정한 디스크 그룹에 여러 호스트 볼륨 또는 파일 시스템이 있지만 전체 세트는 명령에 언급되지 않습니다.

실행할 작업: 다음 중 하나를 수행합니다.

. '-autoexpand' 옵션을 사용하여 명령을 다시 실행하십시오.
. 'SnapDrive snap show' 명령을 사용하여 호스트 볼륨 및 파일 시스템의 전체 목록을 찾을 수 있습니다. 모든 호스트 볼륨 또는 파일 시스템을 지정하는 명령을 실행합니다.




 a| 
0001-440
 a| 
6
 a| 
명령
 a| 
'스냅샷 Snap2__5VG_SINGLELUN__REMOTE에 디스크 그룹 'dgBAD'가 없습니다
 a| 
이 오류는 지정된 디스크 그룹이 지정된 스냅샷 복사본에 포함되지 않은 경우에 발생합니다.

수행할 작업: 지정된 디스크 그룹에 대한 스냅샷 복사본이 있는지 확인하려면 다음 중 하나를 수행합니다.

. "SnapDrive snap list" 명령을 사용하여 스토리지 시스템의 스냅샷 복사본을 찾을 수 있습니다.
. "SnapDrive snap show" 명령을 사용하여 스냅샷 복사본에 있는 디스크 그룹, 호스트 볼륨, 파일 시스템 또는 LUN을 찾을 수 있습니다.
. 디스크 그룹에 대한 스냅샷 복사본이 있는 경우 스냅샷 이름을 사용하여 명령을 실행합니다.




 a| 
0001-442
 a| 
1
 a| 
명령
 a| 
단일 스냅 연결 소스 <src>에 대해 둘 이상의 대상 <dis> 및 <ddis1>이(가) 지정되었습니다. 별도의 명령을 사용하여 다시 시도하십시오
 a| 
실행할 작업: 별도의 SnapDrive snap connect 명령을 실행하여 새 대상 디스크 그룹 이름('snap connect' 명령의 일부임)이 동일한 "SnapDrive snap connect" 명령의 다른 디스크 그룹 단위에 이미 포함되어 있는 이름과 동일하지 않도록 합니다.



 a| 
'0001-465'
 a| 
1
 a| 
명령
 a| 
디스크 그룹:<nanehp13_dg1>
 a| 
지정된 디스크 그룹이 호스트에 없으므로 지정된 디스크 그룹에 대한 삭제 작업이 실패했습니다.

실행할 작업: "모두" 옵션과 함께 "SnapDrive storage show" 명령을 사용하여 호스트의 엔터티 목록을 확인합니다.



 a| 
0001-476
 a| 
해당 없음
 a| 
관리자
 a| 
경로 다중화가 사용 중인 경우 <long lun name>과 연결된 장치를 검색할 수 없습니다. 다중 경로 구성 오류가 발생할 수 있습니다. 구성을 확인한 후 다시 시도하십시오
 a| 
이 실패의 원인은 여러 가지가 있을 수 있습니다.

* 잘못된 호스트 구성:
+
iSCSI, FC 또는 다중 경로 솔루션이 제대로 설정되지 않았습니다.

* 잘못된 네트워크 또는 스위치 구성:
+
IP 네트워크가 iSCSI 트래픽에 대한 적절한 전달 규칙 또는 필터를 사용하여 설정되지 않았거나 FC 스위치가 권장 조닝 구성으로 구성되지 않았습니다.



이전 문제는 알고리즘 또는 순차 방식으로 진단하기가 매우 어렵습니다.

실행할 작업: SnapDrive for UNIX를 사용하기 전에 LUN을 수동으로 검색하기 위해 호스트 유틸리티 설정 가이드(특정 운영 체제용)에서 권장하는 단계를 따를 것을 권장합니다.

LUN을 발견한 후 SnapDrive for UNIX 명령을 사용합니다.



 a| 
0001-486
 a| 
12
 a| 
관리자
 a| 
'LUN이 사용 중입니다. 삭제할 수 없습니다. 먼저 Volume Manager 제어에서 LUN을 제대로 제거하지 않고 볼륨 관리자 제어 하에 있는 LUN을 제거하는 것은 위험합니다
 a| 
UNIX용 SnapDrive에서는 볼륨 그룹에 속한 LUN을 삭제할 수 없습니다.

실행할 작업: 다음 단계를 완료합니다.

. 'SnapDrive storage delete -dg <DgName>' 명령을 사용하여 디스크 그룹을 삭제합니다.
. LUN을 삭제합니다.




 a| 
'0001-494'
 a| 
12
 a| 
명령
 a| 
"SnapDrive cannot delete <mydg1>, 왜냐하면 1개의 호스트 볼륨이 아직 남아 있기 때문입니다. mydg1>'과(와) 연결된 모든 파일 시스템 및 호스트 볼륨을 삭제하려면 -full 플래그를 사용하십시오
 a| 
SnapDrive for UNIX는 디스크 그룹의 모든 호스트 볼륨을 삭제하도록 명시적으로 요청할 때까지 디스크 그룹을 삭제할 수 없습니다.

실행할 작업: 다음 중 하나를 수행합니다.

. 명령에 '-full' 플래그를 지정합니다.
. 다음 단계를 완료합니다.
+
.. SnapDrive storage show -all 명령을 사용하여 디스크 그룹에 있는 호스트 볼륨의 목록을 가져옵니다.
.. UNIX용 SnapDrive 명령에서 각 명령을 명시적으로 언급합니다.






 a| 
0001-541
 a| 
65
 a| 
명령
 a| 
"파일러에 LUN을 생성할 수 있는 액세스 권한이 없습니다.
 a| 
UNIX용 SnapDrive는 유사 액세스 제어 메커니즘을 위해 루트 스토리지 시스템(파일러) 볼륨의 'dshostname.prbac' 또는 'dsgeneric.prbac' 파일을 사용합니다.

실행할 작업: 다음 중 하나를 수행합니다.

. 스토리지 시스템에서 'd-hostname.prbac' 또는 'dsgeneric.prbac' 파일을 수정하여 다음과 같은 필수 권한을 포함시킵니다(하나 이상 가능).
+
.. 없음
.. 스냅 생성
.. 스냅 사용
.. 모두 스냅
.. 스토리지 생성 삭제
.. 스토리지 사용
.. 모두 보관
.. 모든 액세스
+
* 참고: *

+
====
*** 'd-hostname.prbac' 파일이 없으면 스토리지 시스템에서 'dgeneric.prbac' 파일을 수정합니다.
*** 'd-hostname.prbac'과 'dgeneric.prbac' 파일이 모두 있는 경우 스토리지 시스템의 'dhostname.prbac' 파일에서만 설정을 수정합니다.


====


. 'napdrive.conf' 파일에서 '_all-access-if-rbacunspecified_' 설정 변수가 ''on'으로 설정되어 있는지 확인합니다.




 a| 
0001-559
 a| 
해당 없음
 a| 
관리자
 a| 
스냅샷을 생성하는 동안 선택된 입출력입니다. 응용 프로그램을 정지하십시오. SnapDrive 관리자 를 참조하십시오 자세한 내용은 가이드를 참조하십시오
 a| 
이 오류는 스냅샷 복사본을 생성하려고 하지만 파일 사양에 병렬 입력/출력 작업이 발생하고 '_snapcreate-cg-timeout_' 값이 긴급으로 설정된 경우에 발생합니다.

실행할 작업: 정합성 보장 그룹의 시간 초과 값을 'napcreate-cg-timeout'으로 설정하여 시간 초과를 늘립니다.



 a| 
'0001-570'
 a| 
6
 a| 
명령
 a| 
disk group <DG1>이 존재하지 않아 크기를 조정할 수 없습니다
 a| 
이 오류는 디스크 그룹이 호스트에 존재하지 않고 명령이 실패한 경우에 발생합니다.

실행할 작업: 다음 단계를 완료합니다.

. SnapDrive storage show -all 명령을 사용하여 모든 디스크 그룹 이름을 가져옵니다.
. 올바른 디스크 그룹 이름으로 명령을 실행합니다.




 a| 
0001-574
 a| 
1
 a| 
명령
 a| 
'<VmAssistant>lvm은 디스크 그룹에서 LUN 크기를 조정하는 기능을 지원하지 않습니다.
 a| 
이 오류는 이 작업을 수행하는 데 사용되는 볼륨 관리자가 LUN 크기 조정을 지원하지 않는 경우에 발생합니다.

SnapDrive for UNIX는 LUN이 디스크 그룹에 포함된 경우 LUN 크기 조정을 지원하는 볼륨 관리자 솔루션에 따라 다릅니다.

실행할 작업: 사용 중인 볼륨 관리자가 LUN 크기 조정을 지원하는지 확인합니다.



 a| 
0001-616
 a| 
6
 a| 
명령
 a| 
"filer:exocet:/vol/vol1:MySnapName>에서 1개의 스냅샷을 찾을 수 없습니다.
 a| 
UNIX용 SnapDrive에서는 스냅샷 작업을 수행하기 위해 명령줄에 둘 이상의 스냅샷 이름을 사용할 수 없습니다. 이 오류를 해결하려면 스냅샷 이름 하나로 명령을 다시 실행하십시오.

잘못된 스냅샷 이름으로 스냅샷 작업이 시도되는 잘못된 명령 사용을 나타내는 구문 오류입니다. 이 오류를 해결하려면 다음 단계를 수행하십시오.

. 스냅샷 복사본 목록을 보려면 "SnapDrive snap list-filer<filer-volume-name>" 명령을 사용하십시오.
. ' * long_snap_name * ' 인수를 사용하여 명령을 실행합니다.




 a| 
0001-640
 a| 
1
 a| 
명령
 a| 
루트 파일 시스템/은 SnapDrive에서 관리하지 않습니다
 a| 
이 오류는 호스트의 루트 파일 시스템이 SnapDrive for UNIX에서 지원되지 않는 경우에 발생합니다. UNIX용 SnapDrive에 대한 잘못된 요청입니다.



 a| 
0001-684
 a| 
45
 a| 
관리자
 a| 
마운트 테이블에 이미 있는 마운트 지점 <fs_spec>
 a| 
실행할 작업: 다음 중 하나를 수행합니다.

. 다른 마운트 지점을 사용하여 SnapDrive for UNIX 명령을 실행합니다.
. 마운트 지점이 사용 중이 아닌 것을 확인한 후 편집기를 사용하여 다음 파일에서 항목을 수동으로 삭제합니다.


Solaris: /etc/vfstab



 a| 
0001-796, 0001-767
 a| 
3
 a| 
명령
 a| 
0001-796 및 0001-767
 a| 
UNIX용 SnapDrive는 '-nolvm' 옵션을 사용하여 동일한 명령에서 둘 이상의 LUN을 지원하지 않습니다.

실행할 작업: 다음 중 하나를 수행합니다.

. 명령을 다시 사용하여 '-nolvm' 옵션으로 하나의 LUN만 지정하십시오.
. '-nolvm' 옵션 없이 명령을 사용합니다. 이 경우 호스트에 있는 지원되는 볼륨 관리자가 사용됩니다(있는 경우).




 a| 
2715
 a| 
해당 없음
 a| 
해당 없음
 a| 
"파일러에 볼륨 복원 Zephyr을 사용할 수 없습니다. LUN 복원을 계속 진행하십시오.
 a| 
이전 Data ONTAP 버전의 경우 볼륨 복원 ZAPI를 사용할 수 없습니다. SFSR을 사용하여 명령을 다시 실행하십시오.



 a| 
2278
 a| 
해당 없음
 a| 
해당 없음
 a| 
snapname> 다음에 생성된 스냅샷에는 볼륨 클론이 없습니다. 실패
 a| 
클론을 분할 또는 삭제합니다



 a| 
2280
 a| 
해당 없음
 a| 
해당 없음
 a| 
"매핑된 LUN이 활성 또는 스냅샷 <filespec-name>에 없습니다."라는 오류가 발생했습니다
 a| 
매핑 해제/저장 - 호스트 엔터티의 연결을 해제합니다



 a| 
2282
 a| 
해당 없음
 a| 
해당 없음
 a| 
'SnapMirror 관계가 없습니다... 실패
 a| 
. 관계 삭제 또는
. Operations Manager를 사용하는 UNIX용 SnapDrive RBAC가 구성된 경우 운영 관리자 에게 사용자에게 'D. Snapshot.DisruptBaseline' 기능을 부여하도록 요청합니다.




 a| 
2286
 a| 
해당 없음
 a| 
해당 없음
 a| 
"<fsname>이(가) 소유하지 않은 LUN은 스냅샷 볼륨에서 애플리케이션 정합성이 보장됩니다... 실패했습니다. 스냅샷 LUN이 <fsname>이(가) 소유하지 않아 애플리케이션 정합성이 보장되지 않을 수 있습니다
 a| 
검사 결과에 언급된 LUN이 사용 중이 아닌지 확인합니다. 그 이후에만 '-force' 옵션을 사용합니다.



 a| 
2289
 a| 
해당 없음
 a| 
해당 없음
 a| 
"스냅샷 <snapname> 뒤에 새 LUN이 생성되지 않았습니다... 실패
 a| 
검사 결과에 언급된 LUN이 사용 중이 아닌지 확인합니다. 그 이후에만 '-force' 옵션을 사용합니다.



 a| 
2290
 a| 
해당 없음
 a| 
해당 없음
 a| 
"일치하지 않는 최신 LUN 검사를 수행할 수 없습니다. SnapShot version is prior to SDU 4.0'
 a| 
이 문제는 UNIX 스냅샷에 대한 SnapDrive 3.0에서 -- vbsr 와 함께 사용할 때 발생합니다. 생성된 최신 LUN이 더 이상 사용되지 않는지 수동으로 확인한 다음 "-force" 옵션을 진행합니다.



 a| 
2292
 a| 
해당 없음
 a| 
해당 없음
 a| 
"새 스냅샷이 없습니다... 실패했습니다. 생성된 스냅샷이 손실됩니다
 a| 
검사 결과에 언급된 스냅샷이 더 이상 사용되지 않는지 확인합니다. 그런 경우 -force 옵션을 사용합니다.



 a| 
2297
 a| 
해당 없음
 a| 
해당 없음
 a| 
'일반 파일 및 LUN 모두 있음... 실패
 a| 
검사 결과에 언급된 파일 및 LUN이 더 이상 사용되지 않는지 확인합니다. 그런 경우 -force 옵션을 사용합니다.



 a| 
2302
 a| 
해당 없음
 a| 
해당 없음
 a| 
"NFS 내보내기 목록에 외부 호스트가 없습니다... 실패
 a| 
스토리지 관리자에게 문의하여 내보내기 목록에서 외부 호스트를 제거하거나 외부 호스트가 NFS를 통해 볼륨을 사용하고 있지 않은지 확인하십시오.



 a| 
9000305
 a| 
해당 없음
 a| 
명령
 a| 
/mnt/my_fs 엔터티의 유형을 감지할 수 없습니다. 엔티티 유형을 알고 있는 경우 특정 옵션(-lun, -dg, -fs 또는 -lvol)을 제공합니다
 a| 
엔터티가 호스트에 이미 있는지 확인합니다. 요소 유형을 알고 있으면 파일 사양 유형을 제공합니다.



 a| 
9000303입니다
 a| 
해당 없음
 a| 
명령
 a| 
이름이 같은 여러 엔터티가 이 호스트에 있습니다. /mnt/my_fs. 지정한 엔터티에 대한 특정 옵션(-lun, -dg, -fs 또는 -lvol)을 제공합니다
 a| 
사용자가 같은 이름의 여러 요소를 가지고 있습니다. 이 경우 사용자는 파일 사양 유형을 명시적으로 제공해야 합니다.



 a| 
9000304
 a| 
해당 없음
 a| 
명령
 a| 
'/mnt/my_fs는 이 명령으로 지원되지 않는 파일 시스템 유형의 키워드로 감지됩니다.
 a| 
자동 감지 file_spec에 대한 작업은 이 명령에서 지원되지 않습니다. 작업에 대한 각 도움말을 확인합니다.



 a| 
9000301
 a| 
해당 없음
 a| 
명령
 a| 
자동 망명에 내부 오류가 있습니다
 a| 
자동 감지 엔진 오류입니다. 추가 분석을 위해 추적 및 데몬 로그를 제공합니다.



 a| 
해당 없음
 a| 
해당 없음
 a| 
명령
 a| 
'RHEL 5Ux 환경에서 데이터를 압축할 수 없는 napdrive.dc 도구'
 a| 
압축 유틸리티는 기본적으로 설치되지 않습니다. 압축 유틸리티 ncompress를 설치해야 합니다(예: ncompress-4.2.4-47.i386.rpm).

압축 유틸리티를 설치하려면 "rpm-ivh ncompress-4.2.4-47.i386.rpm" 명령을 입력합니다



 a| 
해당 없음
 a| 
해당 없음
 a| 
명령
 a| 
잘못된 파일 지정입니다
 a| 
이 오류는 지정된 호스트 엔터티가 없거나 액세스할 수 없을 때 발생합니다.



 a| 
해당 없음
 a| 
해당 없음
 a| 
명령
 a| 
작업 ID가 유효하지 않습니다
 a| 
지정된 작업 ID가 잘못된 작업이거나 작업 결과가 이미 쿼리된 경우 클론 분할 상태, 결과 또는 중지 작업에 대해 이 메시지가 표시됩니다. 유효하거나 사용 가능한 작업 ID를 지정하고 이 작업을 다시 시도해야 합니다.



 a| 
해당 없음
 a| 
해당 없음
 a| 
명령
 a| 
이미 진행 중인 것
 a| 
이 메시지는 다음과 같은 경우에 표시됩니다.

* 지정된 볼륨 클론 또는 LUN 클론에 대해 클론 분할이 이미 진행 중입니다.
* 클론 분할이 완료되었지만 작업이 제거되지 않았습니다.




 a| 
해당 없음
 a| 
해당 없음
 a| 
명령
 a| 
"유효하지 않은 볼륨 - 클론 또는 LUN - 클론"
 a| 
지정된 filespec 또는 LUN 경로 이름은 유효한 볼륨 클론 또는 LUN 클론이 아닙니다.



 a| 
해당 없음
 a| 
해당 없음
 a| 
명령
 a| 
볼륨을 나눌 공간이 없습니다
 a| 
이 오류 메시지는 볼륨을 분할하는 데 필요한 저장소 공간을 사용할 수 없기 때문입니다. Aggregate에서 볼륨 클론을 분할할 만큼 충분한 공간을 확보하십시오.



 a| 
해당 없음
 a| 
해당 없음
 a| 
해당 없음
 a| 
"filer-data:junction_dbsw 정보를 사용할 수 없음 -- LUN이 오프라인일 수 있음
 a| 
이 오류는 '/etc/fstab' 파일이 잘못 구성된 경우 발생할 수 있습니다. 이 경우 마운트 경로가 NFS인 반면, UNIX용 SnapDrive에서는 LUN으로 간주됩니다.

실행할 작업: 파일러 이름과 접합 경로 사이에 "/"를 추가합니다.



 a| 
0003-013
 a| 
해당 없음
 a| 
명령
 a| 
"가상 인터페이스 서버에서 연결 오류가 발생했습니다. 가상 인터페이스 서버가 실행 중인지 확인하십시오
 a| 
이 오류는 ESX Server의 라이센스가 만료되고 VSC 서비스가 실행되고 있지 않을 때 발생할 수 있습니다.

수행 작업: ESX Server 라이센스를 설치하고 VSC 서비스를 다시 시작합니다.



 a| 
0002-137
 a| 
해당 없음
 a| 
명령
 a| 
"스냅샷 10.231.72.21:/vol/IPS_vol3에 대한 fstype 및 mntOpts를 스냅샷 10.231.72.21:/vol/IPS_vol3:T5120-206-66_nfssnap에서 가져올 수 없습니다.
 a| 
실행할 작업: 다음 중 하나를 수행합니다

. datapath 인터페이스의 IP 주소 또는 특정 IP 주소를 호스트 이름으로 '/etc/hosts' 파일에 추가합니다.
. DNS에서 datapath 인터페이스 또는 호스트 이름 IP 주소에 대한 항목을 생성합니다.
. SVM의 데이터 LIFS를 구성하여 Vserver 관리(firewall-policy=mgmt)를 지원합니다.
+
'* net int modify_-vserver Vserver_name LIF_name-firewall-policy_mgmt * '

. SVM의 엑스포트 규칙에 호스트의 관리 IP 주소를 추가합니다.




 a| 
13003
 a| 
해당 없음
 a| 
명령
 a| 
''권한 부족: 사용자가 이 리소스에 대한 읽기 권한을 가지고 있지 않습니다.
 a| 
이 문제는 UNIX용 SnapDrive 5.2.2에서 나타납니다. UNIX용 SnapDrive 5.2.2를 사용하기 전에 UNIX용 SnapDrive에서 구성된 vsadmin 사용자에게 'vsadmin_volume' 역할이 있어야 합니다. UNIX용 SnapDrive 5.2.2에서 vsadmin 사용자는 상승된 액세스 역할이 필요합니다. 그렇지 않으면 SnapMirror-get-ITER ZAPI가 실패합니다.

실행할 작업: vsadmin_volume 대신 vsadmin 역할을 생성하고 vsadmin 사용자에게 할당합니다.



 a| 
0001-016
 a| 
해당 없음
 a| 
명령
 a| 
스토리지 시스템에서 잠금 파일을 얻을 수 없습니다
 a| 
볼륨의 공간이 부족하여 스냅샷을 생성하지 못했습니다. 또는 스토리지 시스템에 '.SnapDrive_lock' 파일이 존재하기 때문입니다.

실행할 작업: 다음 중 하나를 수행합니다.

. 스토리지 시스템에서 파일 '/vol/<volname>/.SnapDrive_lock'을 삭제하고 스냅 생성 작업을 재시도하십시오. 파일을 삭제하려면 스토리지 시스템에 로그인하고 고급 권한 모드를 입력한 다음 스토리지 시스템 프롬프트에서 "rm/vol/<volname>/.SnapDrive_lock" 명령을 실행합니다.
. 스냅샷을 생성하기 전에 볼륨에서 충분한 공간을 사용할 수 있는지 확인하십시오.




 a| 
0003-003
 a| 
해당 없음
 a| 
관리자
 a| 
"스토리지 시스템 <컨트롤러 이름>의 LUN을 게스트 OS로 내보내지 못했습니다. 원인: flow-11019: MapStorage에서 실패: 인터페이스로 구성된 스토리지 시스템이 없습니다
 a| 
이 오류는 ESX Server에 구성된 스토리지 컨트롤러가 없기 때문에 발생합니다.

수행할 작업: ESX Server에 스토리지 컨트롤러 및 자격 증명을 추가합니다.



 a| 
0001-493
 a| 
해당 없음
 a| 
관리자
 a| 
"마운트 지점 생성 중 오류 발생: mkdir: mkdir: 디렉토리를 생성할 수 없음: 권한 거부 마운트 지점이 automount 경로에 있는지 여부를 확인하십시오.
 a| 
대상 파일 사양이 automount 경로에 있으면 클론 작업이 실패합니다.

실행할 작업: 대상 filespec /mount 지점이 automount 경로 아래에 있지 않은지 확인합니다.



 a| 
0009-049
 a| 
해당 없음
 a| 
관리자
 a| 
"스토리지 시스템의 스냅샷에서 복구하는 데 실패했습니다. SVM의 볼륨에 대한 스냅샷 복사본에서 파일을 복원하지 못했습니다.
 a| 
이 오류는 볼륨 크기가 꽉 찼거나 볼륨이 자동 삭제 임계값을 초과한 경우에 발생합니다.

실행할 작업: 볼륨 크기를 늘리고 볼륨에 대한 임계값이 자동 삭제 값 미만으로 유지되도록 하십시오.



 a| 
0001-682
 a| 
해당 없음
 a| 
관리자
 a| 
새 LUN에 대한 호스트 준비가 실패했습니다. 이 기능은 지원되지 않습니다
 a| 
이 오류는 새 LUN ID 생성이 실패할 때 발생합니다.

수행할 작업: 을 사용하여 생성할 LUN의 수를 늘립니다

`* SnapDrive config prepare LUNs -_count_value_ * '

명령.



 a| 
0001-060
 a| 
해당 없음
 a| 
관리자
 a| 
"디스크 그룹에 대한 정보를 가져오지 못했습니다. 볼륨 관리자 linuxlvm이 vgdisplay 명령을 반환하지 못했습니다.
 a| 
이 오류는 UNIX용 SnapDrive 4.1.1 이하 버전이 RHEL 5 이상 버전에서 사용될 때 발생합니다.

방법: UNIX용 SnapDrive 4.1.1 이하 버전에서 RHEL5 이상에서 지원되지 않으므로 SnapDrive 버전을 업그레이드한 후 다시 시도하십시오.



 a| 
0009-045
 a| 
해당 없음
 a| 
관리자
 a| 
"스토리지 시스템에 스냅샷을 생성하지 못했습니다. 스냅샷으로 백업된 클론으로 인해 스냅샷 작업이 허용되지 않습니다. 잠시 후에 다시 시도하십시오
 a| 
이 오류는 SFSR(Single-File Snap Restore) 작업 후 즉시 스냅샷을 생성하는 동안 발생합니다.

수행할 작업: 나중에 스냅샷 생성 작업을 재시도하십시오.



 a| 
0001-304
 a| 
해당 없음
 a| 
관리자
 a| 
"디스크/볼륨 그룹 생성 오류: 볼륨 관리자가 다음 메시지와 함께 실패했습니다: metainit: 해당 파일 또는 디렉토리가 없습니다.
 a| 
이 오류는 SnapDrive 스토리지가 Sun Cluster 환경에서 DG, hostvol 및 fs Solaris를 생성하는 동안 발생합니다.

수행할 작업: Sun Cluster 소프트웨어를 제거하고 작업을 재시도하십시오.



 a| 
'0001-122'
 a| 
해당 없음
 a| 
관리자
 a| 
"지정된 볼륨 <volname>이(가) 없는 파일러에 스냅샷 목록을 가져오지 못했습니다.
 a| 
이 오류는 SnapDrive for UNIX가 내보낸 더미 볼륨 경로가 아닌 볼륨의 내보낸 활성 파일 시스템 경로(실제 경로)를 사용하여 스냅샷을 생성하려고 할 때 발생합니다.

실행할 작업: 내보낸 액티브 파일 시스템 경로와 함께 볼륨을 사용합니다.



 a| 
0001-476
 a| 
해당 없음
 a| 
관리자
 a| 
"장치를 찾을 수 없습니다. 다중 경로를 사용하는 경우 다중 경로 구성 오류가 발생할 수 있습니다. 구성을 확인한 후 다시 시도하십시오
 a| 
이 오류의 원인은 여러 가지가 있습니다.

다음 조건을 확인해야 합니다. 스토리지를 생성하기 전에 조닝이 적절한지 확인합니다.

'napdrive.conf' 파일에서 전송 프로토콜과 다중경로 유형을 확인하고 적절한 값이 설정되었는지 확인합니다.

다중 경로 데몬 상태를 확인하고 다중 경로 유형이 naivempio start multipathd로 설정된 경우 snapdrived 데몬을 다시 시작합니다.



 a| 
해당 없음
 a| 
해당 없음
 a| 
해당 없음
 a| 
LV를 사용할 수 없어 재부팅 후 FS를 마운트하지 못했습니다
 a| 
이 문제는 재부팅 후 LV를 사용할 수 없을 때 발생합니다. 따라서 파일 시스템이 마운트되지 않았습니다.

실행할 작업: 재부팅 후 vgchange를 수행하고 LV를 실행한 다음 파일 시스템을 마운트합니다.



 a| 
해당 없음
 a| 
해당 없음
 a| 
해당 없음
 a| 
SDU 디몬에 대한 상태 호출에 실패했습니다
 a| 
이 오류가 발생하는 이유는 여러 가지가 있습니다. 이 오류는 작업을 완료하기 전에 특정 작업과 관련된 UNIX용 SnapDrive 작업이 갑자기 실패했음을 나타냅니다(하위 데몬이 종료됨).

"SnapDrive for UNIX daemon에 대한 상태 호출 실패"로 인해 스토리지 생성 또는 삭제가 실패하는 경우 ONTAP를 호출하여 볼륨 정보를 가져오지 못했기 때문일 수 있습니다. Volume-Get-ITER ZAPI가 실패할 수 있습니다. 나중에 SnapDrive 작업을 다시 시도하십시오.

부적절한 'multitpath.conf' 값으로 인해 파티션 또는 기타 운영 체제 명령을 생성하는 동안 "kpartx-l"을 실행하는 동안 SnapDrive for UNIX 작업이 실패할 수 있습니다. 올바른 값이 설정되어 있고 'multitpath.conf' 파일에 중복 키워드가 없는지 확인합니다.

SFSR을 수행하는 동안 UNIX용 SnapDrive는 스냅샷 값의 최대 수에 도달하면 실패할 수 있는 임시 스냅샷을 생성합니다. 이전 스냅샷을 삭제하고 복구 작업을 다시 시도하십시오.



 a| 
해당 없음
 a| 
해당 없음
 a| 
해당 없음
 a| 
'사용 중, 플러싱할 수 없음
 a| 
이 오류는 스토리지 삭제 또는 연결 해제 작업 중에 다중 경로 디바이스를 플러시하려고 할 때 남아 있는 오래된 디바이스가 있는 경우에 발생합니다.

실행할 작업: 명령을 실행하여 오래된 디바이스가 있는지 확인합니다

' * multipath * '

'_-l egrep-i fail_'을 선택한 후 'multitpath.conf' 파일에서 '_flush_on_last_del_'이 'yes'로 설정되어 있는지 확인합니다.

|===
* 관련 정보 *

https://mysupport.netapp.com/NOW/products/interoperability["NetApp 상호 운용성"]

https://library.netapp.com/ecm/ecm_download_file/ECMP1148981["Solaris Host Utilities 6.1 설치 및 설정 가이드"]
