---
permalink: solaris/reference_informationrequired_forusing_the_snapdrive_storagedelete_command.html 
sidebar: sidebar 
keywords: snap, snapdrive, storage, delete, command, information, requirement 
summary: SnapDrive storage delete 명령을 사용하려면 먼저 몇 가지 정보를 제공해야 합니다. 이 정보는 명령을 올바르게 사용하는 데 도움이 됩니다. 
---
= SnapDrive storage delete 명령을 사용하는 데 필요한 정보입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapDrive storage delete 명령을 사용하기 전에 제공해야 할 정보가 몇 가지 있습니다. 이 정보는 명령을 올바르게 사용하는 데 도움이 됩니다.

|===
| 요구 사항 | 인수 


 a| 
입력한 명령에 따라 다음 스토리지 유형을 삭제할 수 있습니다.

* LUN을 클릭합니다
+
스토리지 시스템에서 삭제할 LUN을 하나 이상 지정합니다.

+
하나 이상의 LUN을 삭제하는 경우 첫 번째 인수는 긴 형식의 LUN 이름을 사용해야 합니다. 이 이름은 스토리지 시스템 이름, 볼륨 이름 및 볼륨 내의 LUN 이름을 지정합니다.

+
새 LUN이 이전 LUN과 동일한 스토리지 시스템 및 볼륨에 있는 경우 추가 LUN을 지정하려면 LUN 이름만 사용할 수 있습니다. 그렇지 않으면 새 스토리지 시스템 이름과 볼륨 이름(또는 볼륨 이름)을 지정하여 이전 값을 바꿀 수 있습니다.

* LUN에 직접 생성된 파일 시스템입니다
* 디스크 또는 볼륨 그룹
* 디스크 또는 볼륨 그룹의 파일 시스템입니다
* 호스트 또는 논리 볼륨


file_spec 인수에 입력한 값은 삭제할 스토리지 엔터티를 식별해야 합니다.



 a| 
LUN('-lun')
 a| 
'_long_lun_name _'



 a| 
추가 LUN
 a| 
'_LUN_name_'(긴 형태 또는 짧은 형태)



 a| 
디스크 그룹('-dg_file_spec_') 또는 볼륨 그룹('-vg_file_spec')
 a| 
디스크 그룹 또는 볼륨 그룹의 이름입니다



 a| 
파일 시스템('-fs_file_spec_')
 a| 
'_filesystem_name_'



 a| 
호스트 볼륨('-hostvol_file_spec_') 또는 논리 볼륨('-lvol_file_spec_')
 a| 
호스트 볼륨 또는 논리 볼륨의 이름입니다


NOTE: 요청된 볼륨과 해당 볼륨이 포함된 디스크 그룹(예: '-hostvol dg3/acct_volume')을 모두 제공해야 합니다.



 a| 
명령 프롬프트에 호스트 볼륨이 하나 이상 있는 디스크 그룹과 같은 다른 엔터티가 있는 호스트 측 엔터티를 포함하더라도 SnapDrive for UNIX에서 지정한 스토리지를 삭제하려면 명령 프롬프트에 '-full' 옵션을 포함합니다.

이 옵션을 포함하지 않으면 빈 호스트쪽 요소만 지정해야 합니다.



 a| 
'-가득 참'
 a| 
~



 a| 
스토리지를 삭제할 공유 호스트 엔티티를 지정합니다.



 a| 
'-장치 유형'
 a| 



 a| 
'-fstype'입니다
 a| 
'_type_'



 a| 
'-vmtype'입니다
 a| 
'_type_'



 a| 
*선택 사항:* UNIX용 SnapDrive 작업에 사용할 파일 시스템 및 볼륨 관리자의 유형을 지정합니다.

|===