---
permalink: solaris/task_adding_host_entries_for_new_luns.html 
sidebar: sidebar 
keywords: snap, snapdrive, add, host, lun, entry 
summary: UNIX용 SnapDrive를 사용하여 특정 수의 새 LUN을 생성할 수 있습니다. UNIX용 SnapDrive에서는 이러한 용도로 사용할 수 있는 특정 명령을 제공합니다. 
---
= 새 LUN에 대한 호스트 항목 추가
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
UNIX용 SnapDrive를 사용하여 특정 수의 새 LUN을 생성할 수 있습니다. UNIX용 SnapDrive에서는 이러한 용도로 사용할 수 있는 특정 명령을 제공합니다.

호스트가 특정 수의 새 LUN을 생성할 준비가 되어 있는지 확인합니다. 이러한 LUN은 호스트에 매핑된 스토리지 시스템에 있습니다.

.단계
. SnapDrive config prepare LUNs-count count [-DeviceType shared]입니다
+
count는 호스트를 준비할 새 LUN의 수입니다. '-DeviceType' 공유 옵션은 SFRAC가 있는 Solaris 플랫폼에서 지원됩니다.

+
'-DeviceType'은 UNIX용 SnapDrive 작업에 사용되는 디바이스의 유형입니다. '-DeviceType shared'로 지정하면 SnapDrive config prepare LUNs 명령이 호스트 클러스터의 모든 노드에서 실행됩니다.

+

NOTE: SFRAC 환경에서 이 명령은 호스트 클러스터의 모든 노드에서 실행됩니다.

+
Solaris에서 이 명령은 필요한 경우 항목이 없는 각 잠재적 새 LUN에 대해 파일 '/kernel/drv/sd.conf'에 항목을 추가합니다. 또한 스토리지 시스템이 매핑되는 각 SCSI 타겟에 대한 항목을 생성합니다. Solaris 8에서는 's.conf' 항목을 추가한 후 호스트를 재부팅해야 합니다. 이 명령은 재부팅이 필요할 때마다 경고를 표시합니다.

+
[NOTE]
====
영구 바인딩을 위해 '/kernel/drv/lpfc.conf' 파일을 수동으로 편집한 경우 FC-bind-WWPN 항목이 뒤에 있는지 확인합니다

'#BEGIN:LPUTIL- 관리형 영구 바인딩.

====

