---
permalink: solaris/task_connecting_to_asnapshot_copy_ofstorage_entitiesother_than_luns.html 
sidebar: sidebar 
keywords: snap, snapdrive, connect, snapshot, copy, lun, storage, entities 
summary: SnapDrive snap connect 명령을 사용하여 LUN 이외의 스토리지 엔터티가 포함된 스냅샷 복사본에 연결할 수 있습니다. 지정한 대상 이름이 현재 사용 중이거나 마운트 지점으로 사용되는 파일 시스템 이름이 있는 경우에는 이 명령을 사용할 수 없습니다. 
---
= LUN이 아닌 스토리지 엔터티의 스냅샷 복사본에 연결하는 중입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
"SnapDrive snap connect" 명령을 사용하여 LUN 이외의 스토리지 엔터티가 포함된 스냅샷 복제본에 연결할 수 있습니다. 지정한 대상 이름이 현재 사용 중이거나 마운트 지점으로 사용되는 파일 시스템 이름이 있는 경우에는 이 명령을 사용할 수 없습니다.

기본 마운트 "qio" 옵션으로 마운트된 VxFS 파일 시스템이 포함된 스냅샷 복사본으로 비소스 호스트에서 연결하는 경우 VxFDD(Veritas File Device Driver)용 Veritas 라이센스가 설치되어 있어야 합니다.

.단계
. 다음 명령을 입력합니다.
+
(* SnapDrive snap connect-snapname fspec_set [_fspec_set..._] -snapname_long_snap_name_[-igroup_IG_name_[_IG_name..._]] [-autostExpand] [-autorename] [{-nostist|-noreserve}] [-readonly] *] *

+
이전 사용 시 '_fspec_set_'의 형식은 다음과 같습니다.

+
"*{-dg|-fs|-hostvol}_src_file_spec_[dest_file_spec] [{-destdg|-destvg}_DgName_] [{-destlv|-desthv} lvname] *

+
이 명령은 항상 접속하려는 스토리지 엔터티의 이름(예: '-DG', '-hostvol' 또는 '-fs')으로 시작해야 합니다. NFS 마운트 지점을 지정하는 경우 동일한 명령줄에 NFS가 아닌 엔터티('-vg', '-dg', '-fs', '-lvol' 또는 '-hostvol')를 지정할 수 없습니다.



SnapDrive for UNIX는 지정한 LUN을 복제하여 새 위치에 연결합니다.

다음 명령줄은 디스크 그룹을 연결하고 기본 이름을 대상 이름으로 사용합니다(즉, 소스 이름에서 생성됨).

[listing]
----
# snapdrive snap connect -vg vg1 -snapname
filer1:/vol/vol1:vg1snapshot
connecting vg1:
LUN copy vg1_lun1_0 ... created
(original: filer1:/vol/vol1/vg1_lun1)
mapping new lun(s) ... done
discovering new lun(s) ... done
Importing vg1
----
다음 명령줄은 디스크 그룹을 단일 호스트 볼륨에 연결합니다. 또한 대상 호스트 볼륨 및 디스크 그룹의 이름을 지정합니다.

[listing]
----
# snapdrive snap connect -lvol vg1/vol1 vg1copy/vol1copy -snapname
filer1:/vol/vol1:vg1snapshot
connecting vg1:
LUN copy vg1_lun1_0 ... created
(original: filer1:/vol/vol1/vg1_lun1)
mapping new lun(s) ... done
discovering new lun(s) ... done
Importing vg1copy
----
다음 명령줄은 디스크 그룹을 2개의 LUN과 2개의 파일 시스템으로 연결합니다. 각 파일 시스템의 대상 이름, 파일 시스템 중 하나의 호스트 볼륨 및 두 파일 시스템의 디스크 그룹을 지정합니다.

[listing]
----
# snapdrive snap connect -fs mnt/fs1 /mnt/fs1copy -destvg vg1copy \
-fs /mnt/fs2 /mnt/fs2copy -destlv vg1copy/vol2copy -destvg vg1copy
\ -snapname filer1:/vol/vol1:vg1snapshot
connecting vg1:
LUN copy vg1_lun1_0 ... created
(original: filer1:/vol/vol1/vg1_lun1)
LUN copy vg1_lun2_0 ... created
(original: filer1:/vol/vol1/vg1_lun2)
mapping new lun(s) ... done
discovering new lun(s) ... done
Importing vg1copy
----
다음 명령줄에는 디스크 그룹을 두 개의 파일 시스템에 연결할 때 사용하는 '-autostExpand' 옵션이 포함되어 있습니다. 기본 이름을 대상 이름으로 사용합니다(즉, 소스 이름에서 생성).

[listing]
----
# snapdrive snap connect -lvol mnt/fs1 -snapname
filer1:/vol/vol1:vg1snapshot \
-autoexpand
connecting vg1:
LUN copy vg1_lun1_0 ... created
(original: filer1:/vol/vol1/vg1_lun1)
LUN copy vg1_lun2_0 ... created
(original: filer1:/vol/vol1/vg1_lun2)
mapping new lun(s) ... done
discovering new lun(s) ... done
Importing vg1
----
다음 명령줄에는 디스크 그룹을 두 개의 파일 시스템 및 두 개의 LUN과 연결하므로 -autorename 옵션이 포함되어 있습니다.

[listing]
----
# snapdrive snap connect -fs mnt/fs1 -snapname
filer1:/vol/vol1:vg1snapshot \
-autorename
connecting vg1:
LUN copy vg1_lun1_0 ... created
(original: filer1:/vol/vol1/vg1_lun1)
LUN copy vg1_lun2_0 ... created
(original: filer1:/vol/vol1/vg1_lun2)
mapping new lun(s) ... done
discovering new lun(s) ... done
Importing vg1_0
----
다음 예에서는 Veritas 스택에서 생성된 파일 시스템, 디스크 그룹을 사용하여 스냅샷 복사본에 연결합니다.

[listing]
----
# snapdrive snap connect -fs /mnt/vxfs1 /mnt/vxfs1_clone -snapname
snoopy:/vol/vol1:snapVxvm -autorename
connecting vxvm1:
LUN copy lunVxvm1_0 ... created
(original: snoopy:/vol/vol1/lunVxvm1)
mapping new lun(s) ... done
discovering new lun(s) ... done
Importing vxvm1_0
Successfully connected to snapshot snoopy:/vol/vol1:snapVxvm
disk group vxvm1_0 containing host volumes
vxfs1_SdHv_0 (filesystem: /mnt/vxfs1_clone)
----
다음 예에서는 파일 시스템 1(fs1)이 스토리지 시스템1에 상주하고 파일 시스템 2(fs2)가 스토리지 시스템1과 파트너 스토리지 시스템인 스토리지 시스템2에 상주합니다. 파일 시스템 3(fs3)은 스토리지 시스템1, 파트너 스토리지 시스템 2, 스토리지 시스템 3에 상주하며, 이 시스템은 HA 쌍의 일부가 아닙니다. 추가 파일 시스템인 fs4는 전적으로 스토리지 시스템 4에 있습니다.

다음 명령을 실행하면 fs1, fs2, fs3 및 fs4의 스냅샷 복사본이 생성됩니다.

[listing]
----
snapdrive snap create -fs /mnt/fs1 /mnt/fs2 /mnt/fs3 /mnt/fs4
-snapname fs_all_snap
----
다음 명령은 대상 스토리지 시스템에서 fs1과 fs2를 연결합니다. fs1과 fs2는 모두 HA 페어에 상주하므로 하나의 명령으로 복구할 수 있습니다.

[listing]
----
snapdrive snap connect -fs /mnt/fs1 /mt/fs2 -snapname fs_all_snap
----
다음 명령을 실행하면 fs4가 복구됩니다.

[listing]
----
snapdrive snap connect -fs /mnt/fs4 -snapname fs_all_snap
----
이 파일 시스템은 스토리지 시스템 1, 스토리지 시스템 2 및 스토리지 시스템 3에 상주하므로 UNIX용 SnapDrive는 대상 스토리지 시스템에서 fs3을 접속할 수 없습니다.
