---
permalink: solaris/task_guidelines_fordisplayingsnapshot_copies.html 
sidebar: sidebar 
keywords: snap, snapdrive, display, snapshot, copy, guidelines 
summary: 와일드카드를 사용하여 스냅샷 복사본을 표시할 수 있습니다. 특정 개체에 있는 모든 스냅샷 복사본을 표시할 수 있습니다. 
---
= 스냅샷 복사본 표시 지침
:icons: font
:imagesdir: ../media/


[role="lead"]
와일드카드를 사용하여 스냅샷 복사본을 표시할 수 있습니다. 특정 개체에 있는 모든 스냅샷 복사본을 표시할 수 있습니다.

스냅샷 복사본을 사용하기 전에 다음 사항을 염두에 두십시오.

* 스냅샷 복사본 이름에 와일드카드(*) 문자를 사용할 수 있습니다. 스냅샷 표시 작업에서는 와일드카드 문자를 사용하여 특정 볼륨의 특정 패턴 또는 모든 스냅샷 복사본 이름과 일치하는 모든 스냅샷 복사본 이름을 표시할 수 있습니다. 스냅샷 복사본 이름에 와일드카드를 사용하는 경우 다음 규칙이 적용됩니다.
+
** 이름 끝에만 와일드카드를 사용할 수 있습니다. 스냅샷 복사본 이름의 앞이나 중간에 와일드카드를 사용할 수 없습니다.
** 스냅샷 복사본 이름의 스토리지 시스템 또는 스토리지 시스템 볼륨 필드에는 와일드카드를 사용할 수 없습니다.


* 이 명령을 사용하여 스토리지 시스템과 해당 볼륨, 디스크 그룹, 호스트 볼륨 그룹, 파일 시스템, 호스트 볼륨, 호스트 볼륨 등 특정 개체에 대한 모든 스냅샷 복사본을 나열할 수도 있습니다. 논리적 볼륨을 지원합니다.
* SnapDrive snap show 명령을 입력하고 UNIX용 SnapDrive가 스냅샷 복사본을 찾지 못하면 ""일치하는 스냅샷 복사본이 없습니다.""라는 메시지가 표시됩니다. 명령줄에서 인수를 지정하고 이 인수의 일부가 없으면 SnapDrive for UNIX는 스냅샷 복사본이 있는 인수의 부분 목록을 반환합니다. 또한 유효하지 않은 인수도 나열됩니다.
* SnapDrive snap create 명령이 갑자기 중단되면 스토리지 시스템의 볼륨에 불완전한 .stoc.xml 파일이 저장됩니다. 따라서 스토리지 시스템에서 생성하는 예약된 모든 스냅샷 복사본에는 완료되지 않은 .stoc.xml 파일의 복사본이 있습니다. 'SnapDrive snap list' 명령이 제대로 작동하려면 다음 단계를 완료하십시오.


.단계
. 볼륨에서 불완전한 '.stoc.xml' 파일을 삭제합니다.
. 완료되지 않은 '.stoc.xml' 파일이 포함된 스토리지 시스템에서 생성한 예약된 스냅샷 복사본을 삭제합니다.

