---
permalink: solaris/task_installing_snapdrivefor_unix_on_asolaris_host.html 
sidebar: sidebar 
keywords: snap, snapdrive, install, solaris, host, unix 
summary: Solaris 호스트에 UNIX용 SnapDrive를 설치하려면 루트로 로그인되어 있는지 확인해야 합니다. 이 파일을 원격으로 실행 중인 경우 시스템 구성에서 루트로 로그인할 수 없는 경우 su 명령을 사용하여 root로 로그인할 수 있습니다. 설치 파일은 표준 Solaris.pkg 파일입니다. 
---
= Solaris 호스트에 UNIX용 SnapDrive 설치
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Solaris 호스트에 UNIX용 SnapDrive를 설치하려면 루트로 로그인되어 있는지 확인해야 합니다. 이 파일을 원격으로 실행하고 있고 시스템 구성에서 루트로 로그인할 수 없는 경우 'u' 명령을 사용하여 root로 로그인할 수 있습니다. 설치 파일은 표준 Solaris.pkg 파일입니다.

UNIX용 SnapDrive가 설치된 디렉토리는 삭제하지 마십시오. 디렉토리를 삭제하면 데몬을 시작 및 중지하는 데 문제가 발생할 수 있습니다. UNIX용 SnapDrive를 설치하기 전에 Solaris 호스트 유틸리티도 설치해야 합니다.

스파스 루트 존에서는 일부 파일 시스템이 스파스 루트 존에서 읽기 전용 액세스 권한을 가지고 있기 때문에 UNIX용 SnapDrive 설치가 부분적으로 성공할 수 있습니다. 이러한 상황을 방지하려면 전역 영역에 몇 가지 기호 링크를 만들어 스파스 루트 영역에 대한 링크를 사용할 수 있습니다.

'ln-s /opt/NTAPsnapdrive/bin/SnapDrive/usr/bin/SnapDrive'

"ln-s /opt/NTAPsnapdrive/bin/SnapDrive/usr/sbin/SnapDrive"

'ln-s /opt/NTAPsnapdrive/bin/snapdrived/usr/sbin/snapdred'

.단계
. NetApp Support 사이트에서 다운로드한 소프트웨어를 Solaris 호스트의 디렉토리로 이동합니다.
. UNIX용 SnapDrive를 설치하려면 다음 명령을 입력합니다.
+
'*./install * '

+
이 스크립트는 문제 없이 UNIX용 SnapDrive 소프트웨어를 설치합니다. 로그 파일에 설치 정보를 씁니다.

+
[listing]
----
# ./install
		Installing NTAPsnapdrive now ...
		NTAPsnapdrive install completed successfully.
		snapdrive Installation complete. Log is in
		/tmp/snapdrive_install_log.23752.
----
. 시스템에 대해 SnapDrive for UNIX를 구성하여 설치를 완료합니다.
+
이 정보의 대부분은 기본적으로 설정되지만 다음 정보를 지정해야 합니다.

+
** 스토리지 시스템의 로그인 정보입니다.
** AutoSupport 설정(AutoSupport는 옵션 기능이지만 활성화하는 것이 좋습니다.)



