---
permalink: linux-installation-cmode/task_connecting_linux_host_to_the_storage_system.html 
sidebar: sidebar 
keywords: snapdrive, snap, connect, hosts, storage, system 
summary: 'UNIX용 SnapDrive 작업을 성공적으로 수행하려면 스토리지 가상 머신(SVM, 이전 명칭: vservers\)을 설정해야 합니다.' 
---
= 스토리지 시스템에 Linux 호스트 접속
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
UNIX용 SnapDrive가 성공적으로 운영되려면 SVM(이전의 SVM)을 SVM(스토리지 가상 머신)으로 설정해야 합니다.

* UNIX용 SnapDrive 작업을 실행하려면 SVM 애그리게이트 목록에 볼륨이 포함된 애그리게이트를 할당해야 합니다.
* 클러스터에서 데이터를 제공하려면 하나 이상의 SVM이 생성되어야 합니다.
+
SVM 관리 논리 인터페이스(LIF)의 IP 주소는 DNS(Domain Name Service) 또는 '/etc/hosts' 파일에서 SVM 이름과 매핑되어야 합니다.



.단계
. ONTAP 8.2.2 이하를 실행 중인 경우 adminSVM:+라고도 하는 클러스터 관리 서버에 사용자를 생성합니다
+
'* SnapDrive config set-cserver_csadmin_name cserver_name_*'

+
ONTAP 8.2.3 이상을 실행 중인 경우 이 단계를 건너뛰십시오.

. 데이터 SVM에서 사용자 생성:
+
'* SnapDrive 구성 세트 * '

+
'_vsadmin_name Vserver_NAME_'

. SVM이 SnapDrive for UNIX에서 구성되었는지 확인합니다.
+
'* SnapDrive 구성 목록 * '

+
이 명령을 실행하면 클러스터 관리 서버 및 데이터 SVM의 사용자 이름과 IP 주소가 나열됩니다.

. SVM의 데이터 인터페이스 경로에 대한 관리 인터페이스 경로를 수정합니다.
+
'* SnapDrive config set-mgmtpath_management_interface_path data_interface_path_ *'

. 모든 데이터 및 관리 인터페이스가 올바르게 구성되었는지 확인합니다.
+
'* SnapDrive 구성 목록 - mgmtd path*'


